### ISSUE TITLE
NCO does not allow `_vrfy` functions for cp, cd, mv, ln, rm, and mkdir

### ISSUE THREAD

**Issue by chan-hoo** [ufs-community/ufs-srweather-app#1021]
## Description

 
NCO does not allow `cp_vrfy`, `cd_vrfy`, `mv_vrfy`, `ln_vrfy`, `rm_vrfy`, and `mkdir_vrfy` in production

## Solution

Remove `_vrfy` from the basic unix commands `cp`, `cd`, `mv`, `ln`, `rm`, and `mkdir`.

**Comment by mkavulich** [comment]
See also #861, another good reason to remove these functions.
