### ISSUE TITLE
[SRW-AQM] Build Errors on Hera after Rocky8 Update

### ISSUE THREAD

**Issue by drnimbusrain** [ufs-community/ufs-srweather-app#1057]
## Expected behavior
UFS-SRW-App should compile on Hera with [aqm_dev] branch.

## Current behavior
UFS-SRW-App does not compile on Hera with [aqm_dev] branch after the recent Rocky8 update.

[ 52%] Building Fortran object FV3/ccpp/physics/CMakeFiles/ccpp_physics.dir/physics/samfshalcnv.f.o
[ 53%] Linking Fortran static library libupp.a
/usr/bin/ar: Relink `/apps/oneapi/compiler/2022.0.2/linux/compiler/lib/intel64_lin/libimf.so' with `/lib64/libm.so.6' for IFUNC symbol `sinf'
Error running link command: Segmentation faultmake[5]: *** [FV3/upp/sorc/ncep_post.fd/CMakeFiles/upp.dir/build.make:2167: FV3/upp/sorc/ncep_post.fd/libupp.a] Error 1
make[5]: *** Deleting file 'FV3/upp/sorc/ncep_post.fd/libupp.a'
...
...
...
[ 60%] Linking Fortran static library libccpp_physics.a
/usr/bin/ar: Relink `/apps/oneapi/compiler/2022.0.2/linux/compiler/lib/intel64_lin/libimf.so' with `/lib64/libm.so.6' for IFUNC symbol `sinf'
Error running link command: Segmentation faultmake[5]: *** [FV3/ccpp/physics/CMakeFiles/ccpp_physics.dir/build.make:2722: FV3/ccpp/physics/libccpp_physics.a] Error 1
make[5]: *** Deleting file 'FV3/ccpp/physics/libccpp_physics.a'

## Machines affected
Hera

## Steps To Reproduce
Note:  This is still following AQM Wiki for [aqm_dev] branch:  https://github.com/ufs-community/ufs-srweather-app/wiki/Air-Quality-Modeling

git clone -b aqm_dev https://github.com/ufs-community/ufs-srweather-app.git
   cd ufs-srweather-app/sorc

Update the ../modulefiles/build_hera_intel.lua for latest CMake to compile.  See PR #1056 
 
./app_build.sh -p=hera -a=ATMAQ --extrn

**Comment by drnimbusrain** [comment]
Update:  This is being tracked to first a new location of the spack-stack on Hera due to Rocky8:

For Hera, the Rocky8 spack-stack can be found here:

/scratch1/NCEPDEV/nems/role.epic/spack-stack/spack-stack-1.3.0/envs/unified-env-rocky8
/scratch1/NCEPDEV/nems/role.epic/spack-stack/spack-stack-1.3.1/envs/unified-env-rocky8
/scratch1/NCEPDEV/nems/role.epic/spack-stack/spack-stack-1.4.0/envs/unified-env-rocky8
/scratch1/NCEPDEV/nems/role.epic/spack-stack/spack-stack-1.4.1/envs/unified-env-rocky8
/scratch1/NCEPDEV/nems/role.epic/spack-stack/spack-stack-1.5.0/envs/unified-env-rocky8
/scratch1/NCEPDEV/nems/role.epic/spack-stack/spack-stack-1.5.1/envs/unified-env-rocky8
/scratch1/NCEPDEV/nems/role.epic/spack-stack/spack-stack-1.6.0/envs/unified-env-rocky8

Updating the ../modulefiles/build_hera_intel.lua for the new location leads to other spack modules for UFS-SRW-App on Hera:

Lmod has detected the following error:  The following module(s) are unknown: "yafyaml/0.5.1"

**Comment by drnimbusrain** [comment]
@BrianCurtis-NOAA @chan-hoo

**Comment by BrianCurtis-NOAA** [comment]
@RatkoVasic-NOAA is yafyaml installed on the hera rocky8 spack-stack ?

**Comment by RatkoVasic-NOAA** [comment]
@BrianCurtis-NOAA I think starting spack-stack-1.5.0 yafyaml is not being installed anymore.

**Comment by BrianCurtis-NOAA** [comment]
@drnimbusrain Is there going to be a way to move on from yafyaml or will we need to find a way to get it back in spack-stack ?

**Comment by drnimbusrain** [comment]
> yafyaml

Actually, yes its weird that we have it here at all in AQM, as that is only used in GOCART2G for global model.  According to @bbakernoaa its only used in  MAPL/GOCART.  I think we could remove it then.

**Comment by BrianCurtis-NOAA** [comment]
I recall something in python not working without yafyaml which might need to be addressed.

**Comment by drnimbusrain** [comment]
OK, please report back if we can/should remove it to proceed.

**Comment by BrianCurtis-NOAA** [comment]
@JianpingHuang-NOAA do you recall something with python not liking yafyaml not being loaded in the environment?

**Comment by drnimbusrain** [comment]
But does yafyaml  even touch python, its fortran based parser, right?

**Comment by MichaelLueken** [comment]
I thought `yafyaml` was only for `mapl` support in the SRW.  The `mapl` version in `spack-stack v1.5.0` no longer requires `yafyaml` to function, so it should be safe to remove `yafyaml` from the modulefile.  For what it's worth, `yafyaml` has been removed in the SRW develop branch since we moved to `spack-stack v1.5.0`.

**Comment by drnimbusrain** [comment]
Just removed it from modulefile on Hera,  and compiled aqm_dev successfully.

**Comment by drnimbusrain** [comment]
However, when trying to generate a test workflow on Hera after build it cannot load the config.yaml file:

File "/scratch1/NCEPDEV/nems/role.epic/miniconda3/4.12.0/envs/regional_workflow/lib/python3.9/site-packages/yaml/scanner.py", line 577, in fetch_value
    raise ScannerError(None, None,
yaml.scanner.ScannerError: mapping values are not allowed here
  in "/scratch2/NAGAPE/arl/Patrick.C.Campbell/run_ufs-srw-app_online-cmaq/run_na_test_ufs-srw-app-arl-aqm_canopy3_20240320/ush/config.yaml", line 11, column 16

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/scratch2/NAGAPE/arl/Patrick.C.Campbell/run_ufs-srw-app_online-cmaq/run_na_test_ufs-srw-app-arl-aqm_canopy3_20240320/ush/./generate_FV3LAM_wflow.py", line 895, in <module>
    expt_dir = generate_FV3LAM_wflow(USHdir, wflow_logfile)
  File "/scratch2/NAGAPE/arl/Patrick.C.Campbell/run_ufs-srw-app_online-cmaq/run_na_test_ufs-srw-app-arl-aqm_canopy3_20240320/ush/./generate_FV3LAM_wflow.py", line 72, in generate_FV3LAM_wflow
    expt_config = setup(ushdir,debug=debug)
  File "/scratch2/NAGAPE/arl/Patrick.C.Campbell/run_ufs-srw-app_online-cmaq/run_na_test_ufs-srw-app-arl-aqm_canopy3_20240320/ush/setup.py", line 313, in setup
    expt_config = load_config_for_setup(USHdir, default_config_fp, user_config_fp)
  File "/scratch2/NAGAPE/arl/Patrick.C.Campbell/run_ufs-srw-app_online-cmaq/run_na_test_ufs-srw-app-arl-aqm_canopy3_20240320/ush/setup.py", line 84, in load_config_for_setup
    raise Exception(errmsg)
Exception:

Could not load YAML config file:  /scratch2/NAGAPE/arl/Patrick.C.Campbell/run_ufs-srw-app_online-cmaq/run_na_test_ufs-srw-app-arl-aqm_canopy3_20240320/ush/config.yaml
Reference the above traceback for more information.

**Comment by drnimbusrain** [comment]
Nevermind my previous comment, I had an error in my config.yaml, so it loads fine now.

**Comment by MichaelLueken** [comment]
Completed with PR #1059.
