### ISSUE TITLE
Upgrade to spack-stack 1.7.0

### ISSUE THREAD

**Issue by RatkoVasic-NOAA** [ufs-community/ufs-srweather-app#1069]
## Description
New spack-stack is available. I'm putting placeholder (draft PR) to prepare SRW in case we decide to go with new version. It mainly depends on WM going with new spack-stack version.

## Solution
Change modulefiles to point to correct modules.

## Requirements**
- Install spack-stack-1.7.0 on WCOSS
- ufs-weather-model upgrade to 1.7.0

## Acceptance Criteria (Definition of Done)
Pass SRW comprehensive tests.

**Comment by gspetro-NOAA** [comment]
@MichaelLueken @RatkoVasic-NOAA Should this issue be closed? I thought we were going directly to 1.8.0, but I may be misremembering. Trying to clean up issues ahead of PI15.
