### ISSUE TITLE
GenEnsProd vx tasks for REFC and RETOP inadvertently check for presence of obs files

### ISSUE THREAD

**Issue by gsketefian** [ufs-community/ufs-srweather-app#1084]
## Expected behavior
The `GenEnsProd` verification tasks for `REFC` and `RETOP` (`run_MET_GenEnsProd_vx_[REFC|RETOP]`) should not check for the presence of obs files since the `GenEnsProd` tool only takes forecast files as input.

## Current behavior

Currently, the `run_MET_GenEnsProd_vx_[REFC|RETOP]` tasks are checking for the presence of obs files.  If the task `get_obs_mrms` has not yet generated these files (because it hasn't launched yet, or has not yet completed), then the `run_MET_GenEnsProd_vx_[REFC|RETOP]` tasks will fail.

The check for obs files is in the ex-script `exregional_run_met_genensprod_or_ensemblestat.sh`, in the call to `set_vx_fhr_list`.  This check is present because this ex-script is used not only for `GenEnsProd` tasks but also the `EnsembleStat` verification tasks, which do take observations as inputs (as well as forecasts).  

## Machines affected
All

## Steps To Reproduce

Run any of the WE2E tests that do **ensemble vx** (deterministic vx will not launch any `GenEnsProd` tasks); for example, `MET_ensemble_verification_only_vx` or `MET_ensemble_verification_only_vx_time_lag`.  The bug only sometimes occurs because often, the `get_obs_mrms` task has in fact completed before the `run_MET_GenEnsProd_vx_[REFC|RETOP]` tasks launch.  So the tests may have to be run multiple times to see this bug. 

## Detailed Description of Fix (optional)

In `exregional_run_met_genensprod_or_ensemblestat.sh`, call the `set_vx_fhr_list` script only if the MET tool being used is `EnsembleStat`.  Otherwise, set `FHR_LIST` to the full list of forecast hours.

## Output (optional)

After implementing a fix, one or more of the ensemble vx tests may have to be run multiple times to ensure that the bug doesn't show up again in any of the runs.

**Comment by MichaelLueken** [comment]
The necessary work to correct this issue was included in PR #1137, which was merged as update [39d1e5d](https://github.com/ufs-community/ufs-srweather-app/commit/39d1e5d857f2065902bbb9f502590fb6e22bc23a).  Closing issue as complete.
