### ISSUE TITLE
[develop] UFS-SRW-AQM: Problems with Conda for Generating Workflow on Hera

### ISSUE THREAD

**Issue by drnimbusrain** [ufs-community/ufs-srweather-app#1113]
## Expected behavior
After building UFS-SRW-AQM with [develop] branch, cannot activate conda srw_app environment for generating workflow following the READTHEDOCS.

## Current behavior
Can not find conda environment: srw_app.  

## Machines affected
Hera

## Steps To Reproduce
https://ufs-srweather-app.readthedocs.io/en/develop/UsersGuide/BuildingRunningTesting/AQM.html#quick-start-guide-srw-aqm
```
module use modulefiles/
module load wflow_hera
Please do the following to activate conda:
       > conda activate srw_app

conda activate srw_app
```

## Output (optional)
**EnvironmentNameNotFound: Could not find conda environment: srw_app
You can list all discoverable environments with `conda info --envs`.**

@chan-hoo

**Comment by chan-hoo** [comment]
@drnimbusrain, can you try it on a new terminal window? I tested it on Hera. It worked well on my end.

**Comment by drnimbusrain** [comment]
@chan-hoo You are correct, closing.  Thank you.
