### ISSUE TITLE
release/public-v1: update of hashes/tags in Externals.cfg following final testing for the release

### ISSUE THREAD

**Issue by climbfuji** [ufs-community/ufs-srweather-app#112]
We need to update `Externals.cfg` to point to the latest hashes of the externals:

- UFS_UTILS has been updated, new hash is 44cc810 --> need to create tag once last documentation updates are in
- ufs-weather-model: tag ufs-v2.0.0 has been created
- EMC_post: tag upp-v9.0.0 has been created

Once confirmed that these hashes work, we can create the tags, update `Externals.cfg` once more and test again.

**Comment by mkavulich** [comment]
@climbfuji upp-v9.0.0 has been tagged in EMC_post

**Comment by climbfuji** [comment]
Closed via https://github.com/ufs-community/ufs-srweather-app/pull/113.
