### ISSUE TITLE
Add a namelist setting to control the date increment when running multiple cycles

### ISSUE THREAD

**Issue by jwolff-ncar** [ufs-community/ufs-srweather-app#131]
Right now, it’s a hard-coded daily counter, but it’s easy to alter.  In set_cycle_dates.sh, you’ll find this code stanza:
all_cdates=()
 date_crnt="${date_start}"
 while [ "${date_crnt}" -le "${date_end}" ]; do
  all_cdates+=( $( printf "%s " ${cycle_hrs[@]/#/${date_crnt}} ) )
  date_crnt=$( date -d "${date_crnt} + 1 days" +%Y%m%d )
 done

In addition, generate_FV3LAM_wflow.sh is also set to be a daily increment
‘cycl_freq’: !!str 24:00:00

We would like the ability to set an increment (in hours) to have more flexibility in this setting. And this should become a user-defined setting that can be passed in through the config.sh.

**Comment by JeffBeck-NOAA** [comment]
@jwolff-ncar, can you move this issue to regional_workflow?  Thanks!

**Comment by jwolff-ncar** [comment]
I think it is already covered by this one: https://github.com/NOAA-EMC/regional_workflow/issues/392
