### ISSUE TITLE
Establish a "getting started" page on the wiki for the develop branch

### ISSUE THREAD

**Issue by jwolff-ncar** [ufs-community/ufs-srweather-app#136]
Particularly important as the develop (stable?) branch deviates from the official release (which is currently documented on the wiki).

Hopefully only updated to include develop will be sufficient and we don't need yet a third version for the stable branch but want to mention it here to keep it on the radar.

**Comment by JulieSchramm** [comment]
Should this be a section under the "Developer Information" section?

**Comment by jwolff-ncar** [comment]
I think that seems like a reasonable place to put something like that.
