### ISSUE TITLE
Add developers information to the wiki documentation

### ISSUE THREAD

**Issue by jwolff-ncar** [ufs-community/ufs-srweather-app#141]
## Description
Should add information to the ufs-srweather-app wiki page related to the code contribution protocol.

## Solution
Create a page that incorporates relevant information (or components) from:
  - https://github.com/ufs-community/ufs/wiki/Creating-a-GitHub-Account-for-Development-Work
  - https://github.com/ufs-community/ufs-weather-model/wiki/Developing-Code
  - https://github.com/NOAA-EMC/regional_workflow/wiki/Code-development-and-review-in-the-regional_workflow-repository
  
Remove current link "Creating a GitHub Account for Development Work" and create a new one for the combo page created above.

**Comment by JulieSchramm** [comment]
@jwolff-ncar I added a Developer Information section to the sidebar of the
Sr Wx App wiki:

https://github.com/ufs-community/ufs-srweather-app/wiki

It has the two links above.  Let me know if a new page is needed with
additional information.

**Comment by jwolff-ncar** [comment]
I am fine with having links but I would prefer they open in a new window so people don't all of the sudden land on a different wiki without realizing it. 

Another option to simply listing all of these links on the right side is to create one page that people can go to that then has a brief description and links to these subpages from there. That would decrease the list of items on the main page if that is a concern.

As the new document @mkavulich is slated to start drafting is put together we may want to add some of that content here as well.
