### ISSUE TITLE
EMC_post was changed to UPP

### ISSUE THREAD

**Issue by chan-hoo** [ufs-community/ufs-srweather-app#170]
# Description

The GitHub repository name of 'EMC_post' was changed to 'UPP' (https://github.com/NOAA-EMC/UPP).

**Comment by JeffBeck-NOAA** [comment]
Thanks for quickly getting this issue opened, @chan-hoo.  The setup.sh script in regional_workflow also needs to be updated for EMC_post -> UPP.  I can create an issue for that.
