### ISSUE TITLE
Workflow end-to-end script should follow standard syntax for arguments, documentation needs updating

### ISSUE THREAD

**Issue by climbfuji** [ufs-community/ufs-srweather-app#179]
## Description

Currently the workflow end-to-end script uses a non-standard format for arguments passed to the script, for example:
```
./run_WE2E_tests.sh \
    tests_file="explist.txt" \
    machine="HERA" \
    account="gsd-hpcs"
```
Standard syntax would be
```
./run_WE2E_tests.sh \
    --tests_file="explist.txt" \
    --machine="HERA" \
    --account="gsd-hpcs"
```
or
```
./run_WE2E_tests.sh \
    -t "explist.txt" \
    -m "HERA" \
    -a "gsd-hpcs"
```
or a mixture of these. This should be changed, because it causes unnecessary confusion.

Also, the documentation in https://ufs-srweather-app.readthedocs.io/en/latest/WE2Etests.html is outdated.

## Solution
Adopt standard syntax and update documentation.

## Alternatives (optional)
Do nothing and make life for users harder than necessary.

**Comment by gsketefian** [comment]
@climbfuji Can you please move this to the regional_workflow repo?  Thanks.

**Comment by climbfuji** [comment]
Couldn't transfer between different github accounts, therefore created a new one. Closing.
