### ISSUE TITLE
ufs-weather-model static build

### ISSUE THREAD

**Issue by llpcarson** [ufs-community/ufs-srweather-app#2]
The ufs-weather-model needs to be compiled in static mode, as the dynamic build option will be removed soon (spring 2020).

This may also have implications for the runtime scripts, as the SDFs are specified at build-time an no LD_LIBRARY_PATH updates are needed.

**Comment by llpcarson** [comment]
Info: the current workflow generation step has a list of valid suite names.  With the static build, this needs to match the compilation of the ufs-weather-model, so does not need to be hard-coded to match a list in the workflow-generation step.
For the MRWeather App release, this was handled by always compiling all provided suites (and removing the others from the release-branch code).

**Comment by llpcarson** [comment]
Related issue in regional_workflow is:
https://github.com/NOAA-EMC/regional_workflow/issues/199

**Comment by jwolff-ncar** [comment]
@llpcarson Close once confirmed complete.

**Comment by llpcarson** [comment]
Compiling part is done (compile all suites in the directory).  List of supported suites is still maintained in the workflow, and maintained by hand - could be cleaned up at some point, but not required for this release (it works)
