### ISSUE TITLE
UFS_UTILS builds incorrectly on Cheyenne with Intel, resulting in runtime failures

### ISSUE THREAD

**Issue by mkavulich** [ufs-community/ufs-srweather-app#201]
# Description

Building the develop branch of the app (either manually or with devbuild.sh) results in a "successful" build of UFS_UTILS and other components. However, the executables produced will not run, due to having incorrectly linked libraries:

```
Starting grid file generation...

Creating namelist file (rgnl_grid_nml_fp) to be read in by the grid
generation executable (exec_fp):
  rgnl_grid_nml_fp = "/glade/scratch/kavulich/UFS_SRW/testing/test_core_hours/expt_dirs/develop/GST_release_public_v1/grid/tmp/regional_grid.nml"
  exec_fp = "/glade/scratch/kavulich/UFS_SRW/testing/test_core_hours/ufs-srweather-app/bin/regional_esg_grid"
/glade/scratch/kavulich/UFS_SRW/testing/test_core_hours/ufs-srweather-app/bin/regional_esg_grid: error while loading shared libraries: libnetcdff.so.7: cannot open shared object file: No such file or directory
```

Using the `ldd` command reveals that the executables have broken links to missing library files:

```
kavulich@cheyenne6:/glade/scratch/kavulich/UFS_SRW/testing/test_core_hours/ufs-srweather-app> ldd bin/regional_esg_grid 
	linux-vdso.so.1 (0x00007ffd9127b000)
	libnetcdff.so.7 => not found
	libnetcdf.so.19 => not found
	libm.so.6 => /glade/u/apps/ch/os/lib64/libm.so.6 (0x00007f15e9493000)
	libpthread.so.0 => /glade/u/apps/ch/os/lib64/libpthread.so.0 (0x00007f15e9276000)
	libdl.so.2 => /glade/u/apps/ch/os/lib64/libdl.so.2 (0x00007f15e9072000)
	libc.so.6 => /glade/u/apps/ch/os/lib64/libc.so.6 (0x00007f15e8ccf000)
	libgcc_s.so.1 => /glade/u/apps/ch/os/lib64/libgcc_s.so.1 (0x00007f15e8ab7000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f15e9790000)
```

The confusing thing about this issue is that the executables are built and run successfully when built manually using cmake outside of the app structure. I did this procedure manually rather than using build_all.sh to ensure that the same environment was (in theory) being used. 

```
kavulich@cheyenne6:/glade/scratch/kavulich/UFS_SRW/testing/test_core_hours/UFS_UTILS> source ../ufs-srweather-app_fix2/env/build_cheyenne_intel.env 

The following have been reloaded with a version change:
  1) hdf5/1.10.6 => hdf5/1.10.8


The following have been reloaded with a version change:
  1) g2/3.4.1 => g2/3.4.2     2) g2tmpl/1.9.1 => g2tmpl/1.10.0


The following have been reloaded with a version change:
  1) netcdf/4.7.4 => netcdf/4.8.1

kavulich@cheyenne6:/glade/scratch/kavulich/UFS_SRW/testing/test_core_hours/UFS_UTILS> CMAKE_FLAGS="-DCMAKE_INSTALL_PREFIX=../ -DEMC_EXEC_DIR=ON"
kavulich@cheyenne6:/glade/scratch/kavulich/UFS_SRW/testing/test_core_hours/UFS_UTILS> mkdir ./build && cd ./build
kavulich@cheyenne6:/glade/scratch/kavulich/UFS_SRW/testing/test_core_hours/UFS_UTILS/build> cmake .. ${CMAKE_FLAGS} 2>&1 | tee cmake.log
kavulich@cheyenne6:/glade/scratch/kavulich/UFS_SRW/testing/test_core_hours/UFS_UTILS/build> make -j 8 VERBOSE=1 2>&1 | tee make.log
kavulich@cheyenne6:/glade/scratch/kavulich/UFS_SRW/testing/test_core_hours/UFS_UTILS/build> ldd ./sorc/grid_tools.fd/regional_esg_grid.fd/regional_esg_grid
	linux-vdso.so.1 (0x00007fffb155c000)
	libnetcdff.so.7 => /glade/u/apps/ch/opt/netcdf/4.8.1/intel/19.1.1/lib/libnetcdff.so.7 (0x00007fc72cbc1000)
	libnetcdf.so.19 => /glade/u/apps/ch/opt/netcdf/4.8.1/intel/19.1.1/lib/libnetcdf.so.19 (0x00007fc72c849000)
	libm.so.6 => /glade/u/apps/ch/os/lib64/libm.so.6 (0x00007fc72c54c000)
	libpthread.so.0 => /glade/u/apps/ch/os/lib64/libpthread.so.0 (0x00007fc72c32f000)
	libdl.so.2 => /glade/u/apps/ch/os/lib64/libdl.so.2 (0x00007fc72c12b000)
	libc.so.6 => /glade/u/apps/ch/os/lib64/libc.so.6 (0x00007fc72bd88000)
	libgcc_s.so.1 => /glade/u/apps/ch/os/lib64/libgcc_s.so.1 (0x00007fc72bb70000)
	libhdf5_hl.so.100 => /glade/u/apps/ch/opt/netcdf/4.8.1/intel/19.1.1/lib/libhdf5_hl.so.100 (0x00007fc72b947000)
	libhdf5.so.103 => /glade/u/apps/ch/opt/netcdf/4.8.1/intel/19.1.1/lib/libhdf5.so.103 (0x00007fc72b276000)
	libsz.so.2 => /glade/u/apps/ch/opt/netcdf/4.8.1/intel/19.1.1/lib/libsz.so.2 (0x00007fc72b05a000)
	libz.so.1 => /glade/u/apps/ch/opt/netcdf/4.8.1/intel/19.1.1/lib/libz.so.1 (0x00007fc72ae3c000)
	libcurl.so.4 => /glade/u/apps/ch/os/usr/lib64/libcurl.so.4 (0x00007fc72abb7000)
	libifport.so.5 => /glade/u/apps/opt/intel/2020u1/compilers_and_libraries/linux/lib/intel64/libifport.so.5 (0x00007fc72a989000)
	libifcoremt.so.5 => /glade/u/apps/opt/intel/2020u1/compilers_and_libraries/linux/lib/intel64/libifcoremt.so.5 (0x00007fc72a5ee000)
	libimf.so => /glade/u/apps/opt/intel/2020u1/compilers_and_libraries/linux/lib/intel64/libimf.so (0x00007fc729f6b000)
	libsvml.so => /glade/u/apps/opt/intel/2020u1/compilers_and_libraries/linux/lib/intel64/libsvml.so (0x00007fc7284b9000)
	libintlc.so.5 => /glade/u/apps/opt/intel/2020u1/compilers_and_libraries/linux/lib/intel64/libintlc.so.5 (0x00007fc728241000)
	libirng.so => /glade/u/apps/opt/intel/2020u1/compilers_and_libraries/linux/lib/intel64/libirng.so (0x00007fc727ed7000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fc72d04d000)
	libnghttp2.so.14 => /glade/u/apps/ch/os/usr/lib64/libnghttp2.so.14 (0x00007fc727cb5000)
	libssh.so.4 => /glade/u/apps/ch/os/usr/lib64/libssh.so.4 (0x00007fc727a6c000)
	libssl.so.1.0.0 => /glade/u/apps/ch/os/lib64/libssl.so.1.0.0 (0x00007fc7277fe000)
	libcrypto.so.1.0.0 => /glade/u/apps/ch/os/lib64/libcrypto.so.1.0.0 (0x00007fc727397000)
	libgssapi_krb5.so.2 => /glade/u/apps/ch/os/usr/lib64/libgssapi_krb5.so.2 (0x00007fc72714f000)
	libldap-2.4.so.2 => /glade/u/apps/ch/os/usr/lib64/libldap-2.4.so.2 (0x00007fc726f03000)
	liblber-2.4.so.2 => /glade/u/apps/ch/os/usr/lib64/liblber-2.4.so.2 (0x00007fc726cf4000)
	librt.so.1 => /glade/u/apps/ch/os/lib64/librt.so.1 (0x00007fc726aec000)
	libkrb5.so.3 => /glade/u/apps/ch/os/usr/lib64/libkrb5.so.3 (0x00007fc72681c000)
	libk5crypto.so.3 => /glade/u/apps/ch/os/usr/lib64/libk5crypto.so.3 (0x00007fc7265ec000)
	libcom_err.so.2 => /glade/u/apps/ch/os/usr/lib64/libcom_err.so.2 (0x00007fc7263e8000)
	libkrb5support.so.0 => /glade/u/apps/ch/os/usr/lib64/libkrb5support.so.0 (0x00007fc7261db000)
	libresolv.so.2 => /glade/u/apps/ch/os/lib64/libresolv.so.2 (0x00007fc725fc4000)
	libsasl2.so.3 => /glade/u/apps/ch/os/usr/lib64/libsasl2.so.3 (0x00007fc725da7000)
	libkeyutils.so.1 => /glade/u/apps/ch/os/lib64/libkeyutils.so.1 (0x00007fc725ba3000)
	libselinux.so.1 => /glade/u/apps/ch/os/lib64/libselinux.so.1 (0x00007fc72597d000)
	libpcre.so.1 => /glade/u/apps/ch/os/usr/lib64/libpcre.so.1 (0x00007fc72570e000)
```

As far as I can tell from the log files, the exact same cmake commands (and eventual compilation commands) are being used for the successful and unsuccessful build. And disabling the weather model and UPP builds does not fix the issue (meaning there is nothing in those builds somehow overwriting the environment. So I do not understand what is going on that is causing the executables to ultimately be created unsuccessfully. 

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Build the App (either manually or with devbuild.sh)
2. Attempt to run the workflow, see the above errors

## Additional Context

This occurs on Cheyenne with Intel compilers. Testing with GNU was not possible due to a separate failure to build the weather model.

**Comment by mkavulich** [comment]
An update based on further investigation: This error also occurs in the stand-alone CMake build for UFS_UTILS...I did not realize it at first because I did not run the "make install" step, which appears to be causing this issue.

Will move this issue to the UFS_UTILS repository.

**Comment by mkavulich** [comment]
Reopening as the fix should be applied at the App level (at least for now)

**Comment by JeffBeck-NOAA** [comment]
@mkavulich, thanks for tracking this down.  It looks like it's specifically a NetCDF problem?  Could it just be related to the version in the build env file?  Should we try a newer/older version?

**Comment by mkavulich** [comment]
So some breaking news, it appears the issue is not related to netCDF at all, but rather, is related to the CMake build rules and how they interact with the build environment. I found a fix that I do not quite understand, but comes straight from [this helpful CMake page](https://gitlab.kitware.com/cmake/community/-/wikis/doc/cmake/RPATH-handling#common-questions): Adding this line to the UFS_UTILS CMakelists.txt fixes the problem:

```
diff --git a/CMakeLists.txt b/CMakeLists.txt
index 3657c8ad..99c8737a 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -82,6 +82,8 @@ if(ENABLE_DOCS)
   add_subdirectory(docs)  
 endif()
 
+set(CMAKE_INSTALL_RPATH_USE_LINK_PATH TRUE)
+
 add_subdirectory(sorc)
```

The documentation is not particularly helpful in indicating *why* this solution is needed, or why this option is not the default, but it does fix the error on Cheyenne. There doesn't appear to be any way to pass this as an argument from the App-level CMake, so the change will likely be needed in UFS_UTILS. I am running tests right now and will open a PR shortly, hopefully this won't take too long to get approved.

**Comment by dmwright526** [comment]
@mkavulich, Thanks for the update on this as I was just struggling with getting things installed on Cheyenne! From my trouble shooting of the problem, it looks like this is a machine issue specifically with the module load of netcdf and the LD_LIBRARY_PATH environment variable. 

If you hard code the netcdf library path to this variable (export LD_LIBRARY_PATH=export LD_LIBRARY_PATH=/path/to/netcdf/lib/:$LD_LIBRARY_PATH)  in the run scripts (e.g. exregional_make_grid.sh) it will then run. This problem might be better addressed at the machine level (which may or may not be possible) as this should be set at module load in my opinion.

**Comment by mkavulich** [comment]
I have gotten to the bottom of this issue and now fully understand what is happening. A combination of Cheyenne environment changes and the specific build rules within hpc-stack are causing this issue; see https://github.com/NOAA-EMC/hpc-stack/issues/376 for more details

Note: I have applied a hard-fix on disk to the Cheyenne intel module, so this issue should no longer occur for Intel. I have not applied a fix for GNU in order to preserve a way to reproduce the error for the hpc-stack issue.

**Comment by mkavulich** [comment]
Since this issue only mentions Intel, it is technically resolved.
