### ISSUE TITLE
Update UPP run script for latest developments

### ISSUE THREAD

**Issue by hertneky** [ufs-community/ufs-srweather-app#207]
As of Oct 2021, UPP uses a formal fortran namelist. In order to update the UPP hash for SRW, some minor changes will need to be made to the ufs-srweather-app/regional_workflow/scripts/exregional_run_post.sh to read the new namelist.

Please let me know, when a good time to do this will be (i.e. when you are ready to start using a newer hash). Note: I tested changes using SRW develop on Hera in early January with success.

Related to UPP [Issue 115](https://github.com/NOAA-EMC/UPP/issues/115)

**Comment by mkavulich** [comment]
Hi @hertneky, thanks for opening this issue! Please go ahead and open these PRs when they are ready for review. Just be sure your PR for ufs-srweather-app references the appropriate PR in regional_workflow so they can be merged in coordination with each other.
