### ISSUE TITLE
Include rst documentation for verification tasks

### ISSUE THREAD

**Issue by jwolff-ncar** [ufs-community/ufs-srweather-app#208]
# Description
Document deterministic and ensemble verification tasks that have been added to the workflow. (How to configure/run.)

## Steps to Reproduce
N/A

## Additional Context
Point users to METplus documentation for additional details.

## Output
N/A

**Comment by gspetro-NOAA** [comment]
@JeffBeck-NOAA Can we close this issue?

**Comment by JeffBeck-NOAA** [comment]
@gspetro-NOAA, yep!
