### ISSUE TITLE
Update rst documentation for using template variables

### ISSUE THREAD

**Issue by jwolff-ncar** [ufs-community/ufs-srweather-app#230]
## Description
This is moved from regional_workflow (issue #651). Update rst documentation for variables introduced in PR https://github.com/ufs-community/regional_workflow/pull/650 for using template variables. Documentation already exists in the WE2E test configuration file config.template_vars.sh (in the directory regional_workflow/tests/WE2E/test_configs/wflow_features).

## Solution
Update the necessary rst file.

**Comment by gspetro-NOAA** [comment]
@JeffBeck-NOAA Was this taken care of with the edits for the Workflow Configuration chapter (with config_defaults.sh info) for the v2 release? Can we close it?

**Comment by JeffBeck-NOAA** [comment]
@gspetro-NOAA, I believe this issue was going to be resolved with [this PR](https://github.com/ufs-community/ufs-srweather-app/pull/198), but it was never merged.  @gsketefian, anything to add here?

**Comment by gsketefian** [comment]
I closed that PR since things changed so much that it got out of date.  I am not up-to-date on how template variables can be used now in the config file.

**Comment by JeffBeck-NOAA** [comment]
Thanks, @gsketefian.  @gspetro-NOAA, I guess we should leave this issue open and tag the code developer who introduced the new template changes.

**Comment by gsketefian** [comment]
Yeah, probably @danielabdi-noaa is the best person after the [yaml configuration PR](https://github.com/ufs-community/regional_workflow/pull/778) is in.

**Comment by danielabdi-noaa** [comment]
@gsketefian I learned about the templates you described just now after reading the description in your PR so not sure if I am the best person for this task. The yaml conversion maintains the template functionality because templates are still either single quoted or not quoted (same thing), thus are not interpreted until they are actually eval'ed. Other than that, I think the your PR describes it well.

**Comment by JeffBeck-NOAA** [comment]
Thanks, @danielabdi-noaa!  @gsketefian, since it sounds like your documentation is fine as is (aside from adding the explanation that Daniel provided), are you willing to reopen it?

**Comment by MichaelLueken** [comment]
Closed by #528.
