### ISSUE TITLE
Add Gaea to supported platforms

### ISSUE THREAD

**Issue by mark-a-potts** [ufs-community/ufs-srweather-app#235]
## Description
Add Gaea to the list of supported platforms in preparation for release v2.

## Solution
Add build and wflow specifics to env as well as machine-specific files to regional_workflow.

**Comment by MichaelLueken** [comment]
This was completed when PR #236 was merged to develop at [3e2b634](https://github.com/ufs-community/ufs-srweather-app/commit/3e2b63407664ecd8362865221a6aeb327de1ed01).  Closing issue now.
