### ISSUE TITLE
Add GSI and RRFS Utilities to enable RRFS DA workflows

### ISSUE THREAD

**Issue by christopherwharrop-noaa** [ufs-community/ufs-srweather-app#239]
## Description
RRFS data assimilation workflows are currently being developed and run via GSL's fork of the SRW App [here](https://github.com/NOAA-GSL/ufs-srweather-app/tree/feature/RRFS_dev1).  This capability needs to transition into the authoritative SRW so that:

1.  Its capabilities can be used by the community
2. The community can contribute to its capabilities
3. Its development is correctly maintained and synchronized with overall authoritative SRW App development and does not diverge

A prerequisite for adding RRFS DA workflow capabilities to authoritative SRW is the addition of two new components:

1. [GSI](https://github.com/NOAA-EMC/GSI)
2. [rrfs_utl](https://github.com/NOAA-GSL/rrfs_utl)

All RRFS DA workflows require building and running code from those two components.

This issue is being opened to discuss various options for adding GSI and rrfs_utl to the authoritative SRW App to lay the foundation for incrementally adding RRFS DA workflow capabilities afterward.

This issue is contingent upon successful approval and merging of a [GSI cmake refactor at EMC](https://github.com/NOAA-EMC/GSI/pull/327).  That work enables GSI's cmake to be fully portable and findable using cmake's `find_package(gsi)`.  It is expected that this will happen around the second week of May.  Once GSI's cmake refactor is merged onto master at EMC, it will have the build system capabilities required here.

## Solution
There are two parts to adding GSI and rrfs_utl to be considered:

1. Checking out the code
2. Building the code

### Checking out the code
There are only two options for adding GSI and rrfs_utl to code checkout: manage_externals and git submodules.

My proposal is to use manage_externals and add the appropriate repositories and hashes for GSI and rrfs_utl to `Externals.cfg`.  This maximizes consistency with how other components are checked out.  The other advantage is that manage_externals is easily configured to ignore GSI's git submodules that live on NOAA's publicly inaccessible VLab.

### Building the code
There are also two options to consider for building the code: (1) Always build both GSI and rrfs_utl whenever SRW is built, or (2) Add an SRW build option, such as `BUILD_RRFS_DA` or something similar, to turn the building of GSI and rrfs_utl on/off.

My proposal is to add a build option (of some appropriate name) to turn building of GSI and rrfs_utl on/off and set the default to OFF.  This will allow faster builds for non-DA use cases and will also make more sense when adding GSI and rrfs_utl components as a first step without adding any accompanying DA workflow capabilities at the outset.

**Please also note that the `srw_common` will need to be updated in order to build GSI and rrfs_utl correctly.  Please see [this example](https://github.com/NOAA-GSL/ufs-srweather-app/blob/feature/RRFS_dev1/env/srw_common) that shows the required updates.**

## Alternatives (optional)
We could use git submodules instead of manage_externals to checkout GSI and rrfs_utl, but that would create an unexpected inconsistency and potentially confuse manage_externals.  It also would cause problems because manage_externals knows how to ignore GSI submodules (which need to be excluded because they are on publicly inaccessible VLab), whereas it is not clear whether git submodules can easily do that.

We could build GSI and rrfs_utl for every use of SRW App, even when a user is not going to run DA workflows.  However, this seems inefficient and wasteful and confusing for the user.

## Related to (optional)
To see an example of a functioning version of SRW with GSI and rrfs_utl integrated into the top-level App cmake, see [GSL's RRFS development branch](https://github.com/NOAA-GSL/ufs-srweather-app/tree/feature/RRFS_dev1).  This branch does not use an option at the app-level to turn GSI and rrfs_utl on/off, but the cmake integration is otherwise complete and functioning (tested successfully on WCOSS Dell, Hera, Jet, Orion, Cheyenne Intel/Gnu).

**Comment by christopherwharrop-noaa** [comment]
@mkavulich , @jwolff-ncar , @JeffBeck-NOAA , @christinaholtNOAA - Perhaps I should not have assigned this to you, but rather just tagged to bring your attention to the existence of this.  Please forgive me and remove yourself as needed.  I will likely be the one who actually submits the PR to address the contents of this issue when the time comes. So maybe I should be the only one assigned to it.  But, I need to make sure appropriate people are pinged and have the chance to see/comment on this fairly impactful development.

**Comment by JeffBeck-NOAA** [comment]
Is there any reason GSI and rrfs_utl couldn't be incorporated into UFS_UTILS?  Their use (DA) applies across UFS Apps, and UFS_UTILS is the one location where utilities currently reside for all Apps.  Could this be another option?

**Comment by christopherwharrop-noaa** [comment]
@JeffBeck-NOAA - The main downside to that is it would make GSI become a dependency for building UFS_UTILS.  Given that rrfs_utls are very small DA-specific utilities, that probably doesn't make sense.

**Comment by christopherwharrop-noaa** [comment]
To expand on that a bit further, if you put the rrfs_utl utilities into UFS_UTILS, you would have to add GSI as a component to ALL UFS apps and always build GSI in order to satisfy the dependency for building UFS_UTILS.  And you'd have to do that even when no DA work was needed.  You could, I suppose, fix that by adding an option for turning DA on/off in the UFS_UTILS build such that it only needed GSI if DA was turned on.  And it might pave the way for more pre-JEDI DA capabilities in the various Apps.  But, my opinion is that it's not worth it.

**Comment by christopherwharrop-noaa** [comment]
FYI - [GSI cmake update PR #327](https://github.com/NOAA-EMC/GSI/pull/327) will be submitted to the review committee today (May 12, 2022) and will be merged by next Wed (May 18, 2022).  At that point the GSI will be suitable for use as a SRW App component.
