### ISSUE TITLE
Update UPP hash for SRW v2 release

### ISSUE THREAD

**Issue by fossell** [ufs-community/ufs-srweather-app#271]
## Description
UPP release/public-v3 branch had some additional updates so the hash in the app Externals.cfg file needs to be updated. Mostly documentation changes, no major code changes, not expected to change results. Current [UPP release/public-v3 branch](https://github.com/NOAA-EMC/UPP/tree/release/public-v3) hash that we expect to tag from is 1dbcb0c4a.

## Solution
Update the UPP hash to most current hash once UPP tags release. 

## Alternatives (optional)
If applicable, add a description of any alternative solutions or features you've considered.

## Related to (optional)
Directly reference any issues or PRs in this or other repositories that this is related to, and describe how they are related.

**Comment by fossell** [comment]
@mark-a-potts - The hash for the [upp_v10.1.0 release](https://github.com/NOAA-EMC/UPP/releases/tag/upp_v10.1.0) which was tagged from branch [release/public-v3](https://github.com/NOAA-EMC/UPP/tree/release/public-v3) is 1dbcb0c4. Please make sure the hash is updated in the appropriate places for the SRW App.

**Comment by mkavulich** [comment]
Completed with #288
