### ISSUE TITLE
devbuild.sh needs testing on NOAA Cloud

### ISSUE THREAD

**Issue by gspetro-NOAA** [ufs-community/ufs-srweather-app#272]
# Description

The devbuild.sh method for building the SRW App only has the following options: cheyenne | gaea | hera | jet | macos | odin | orion | singularity | wcoss_dell_p3

- There is no noaacloud option, and the singularity option for devbuild.sh generates a module not found error (see below). when building directly in AWS/PW. 
- The singularity build should be tested in an actual container prior to the release to be sure it works. 

## Steps to Reproduce

Running: ./devbuild.sh --platform=singularity --compiler=gnu
gives a module not found error: "Lmod has detected the following error:  The following module(s) are
unknown: "hpc-openmpi" "png" "hpc" "hpc-gnu""

**Comment by gspetro-NOAA** [comment]
@MichaelLueken It seems like this has been resolved? Just wanted to confirm.

**Comment by MichaelLueken** [comment]
@gspetro-NOAA Since Platform's nightly builds successfully build the SRW App on NOAA Cloud platforms and PR #1167 will address the final issues with running on Azure, it should be fine to close this issue.
