### ISSUE TITLE
NaturalEarth graphics plotting files need to be moved to standardized/accessible location

### ISSUE THREAD

**Issue by gspetro-NOAA** [ufs-community/ufs-srweather-app#301]
## Description
The locations of the NaturalEarth graphics plotting files were not updated to standardized locations on all Level 1 systems as part of [PR#231](https://github.com/ufs-community/ufs-srweather-app/issues/231). On Orion, the files are inaccessible to a number of EPIC team members. Currently, the NaturalEarth files reside in the following directories: 
On Cheyenne: `/glade/p/ral/jntp/UFS_SRW_app/tools/NaturalEarth`
On Jet: `/lfs4/BMC/wrfruc/FV3-LAM/NaturalEarth`
On Orion: `/work/noaa/gsd-fv3-dev/UFS_SRW_App/v1p0/fix_files/NaturalEarth`
On Gaea: `/lustre/f2/pdata/esrl/gsd/ufs/NaturalEarth`
On Hera: `/scratch2/BMC/det/UFS_SRW_App/develop/fix_files/NaturalEarth`
On NOAACloud: `/contrib/EPIC/NaturalEarth` 

## Solution
On Orion, @EdwardSnyder-NOAA , Sylvia Chin, and I do not have permissions to access the gsd-fv3-dev directory, so we need someone to move the NaturalEarth files from there to `/work/noaa/fv3-cam/UFS_SRW_App/develop/` or another appropriate directory (not v1p0). 
The paths on Gaea, Jet, and Cheyenne, Hera, and NOAACloud should be standardized to match. 

This fix needs to happen before the release so that docs can be updated accordingly. 

@mkavulich

**Comment by mkavulich** [comment]
Thanks for making note of this @gspetro-NOAA. I am not sure who was initially in charge of staging these files so I'll have to check to ensure that they are consistent across platforms, and if they are not, determine which one is "authoritative". I'll let you know what my progress is.

Did you have any preference as to the location? My thought would be to put it under  UFS_SRW_App/develop/fix/NaturalEarth on each platform.

**Comment by gspetro-NOAA** [comment]
@mkavulich No preference on my end. I think your suggestion sounds reasonable. :)

**Comment by mkavulich** [comment]
Okay, I have staged data in "standard" locations on the following machines:

 - Cheyenne ``/glade/p/ral/jntp/UFS_SRW_App/develop/NaturalEarth``
 - Hera ``/scratch2/BMC/det/UFS_SRW_App/develop/NaturalEarth``
 - Jet ``/mnt/lfs4/BMC/wrfruc/UFS_SRW_App/develop/NaturalEarth``
 - Orion ``/work/noaa/fv3-cam/UFS_SRW_App/develop/``

I do not have access to stage the data on Gaea or NOAACloud, so someone else will have to stage that data.

As a side note, this process has made me realize that no data has been staged for the release code. I opened an issue about this here: https://github.com/ufs-community/regional_workflow/issues/793

**Comment by mark-a-potts** [comment]
I have staged the data on Gaea. I also copied the develop directory to create a release-v2.0 directory for the release.

**Comment by gspetro-NOAA** [comment]
I copied NaturalEarth files to the appropriate location on NOAA Cloud.
