### ISSUE TITLE
Include documentation on how to use Jenkins CI/CD testing

### ISSUE THREAD

**Issue by gsketefian** [ufs-community/ufs-srweather-app#307]
## Description
Include documentation on how to run the Jenkins CI/CD tests and look at results.

## Solution
There was some discussion already in PR #297.  Some of that and more should be added to the RST documentation.

## Related to (optional)
PR #297.

**Comment by gspetro-NOAA** [comment]
@JeffBeck-NOAA @jessemcfarland Can we close this now that I added Jenkins info in PR #335 ? Or is there more to be done?

**Comment by JeffBeck-NOAA** [comment]
@gspetro-NOAA, if you're comfortable with the Jenkins documentation that was added in that PR (I think it's good for now), then we can close this issue.

**Comment by gspetro-NOAA** [comment]
Jenkins testing documentation reflects the current state of Jenkins/SRW testing. If a new PR is opened to update Jenkins-related details, we can document the changes at that time and/or create a new issue for documentation.
