### ISSUE TITLE
Change HPC-Stack submodule to sparse-checkout

### ISSUE THREAD

**Issue by gspetro-NOAA** [ufs-community/ufs-srweather-app#319]
## Description
Currently, the HPC-Stack submodule pulls in the entire HPC-Stack repo when only the docs are needed. This led to some confusion about why the hpc-stack submodule appears in the top-level SRW App directory and whether we can avoid having the entire repo in there.

## Solution
It seems like a git sparse-checkout option may solve the problem. 
The process is described [here](https://stackoverflow.com/questions/600079/how-do-i-clone-a-subdirectory-only-of-a-git-repository#:~:text=At%20the%20moment%20it%20is,shallow%20clone%20and%20sparse%20checkout). Instead of `echo "some/dir/" >> .git/info/sparse-checkout`, we can do `echo "docs/source" >> .git/info/sparse-checkout`.

## Alternatives (optional)
It would be worthwhile to explore the intersphinx extension, which allows users to link to docs in other projects. However, it might not permit the addition of an HPC-Stack/submodule chapter within the SRW App docs itself. The sparse checkout seems like the best interim solution and may turn out to be the best solution overall.

**Comment by MichaelLueken** [comment]
@gspetro-NOAA - Since the SRW App has officially transitioned to spack-stack and the HPC-stack submodule has been removed, should this issue be closed?

**Comment by MichaelLueken** [comment]
Closing issue now.  If you feel this issue hasn't been addressed, please feel free to either reopen this issue or open a new issue.
