### ISSUE TITLE
Compilation Error: Symbol 'rmissing' referenced at (1) not found in module 'kinds'

### ISSUE THREAD

**Issue by htan2013** [ufs-community/ufs-srweather-app#324]
# Description

Dear all,
I tried to compile UFS SRW and I met this error when it comes to compilation of ESMF:

-- Found MPI_C: /soft/openmpi/4.1.2/bebop-bdw/bin/mpicc (found version "3.1")
-- Found MPI_Fortran: /gpfs/fs1/home/software/openmpi/4.1.2/bebop-bdw/lib/libmpi_usempif08.so (found version "3.1")
-- Found MPI: TRUE (found version "3.1")
-- Found MPI_CXX: /soft/openmpi/4.1.2/bebop-bdw/bin/mpicxx (found version "3.1")
-- Found NetCDF: /lcrc/project/OW_UFS/HPC-Stack/include (found version "4.7.4") found components: Fortran
-- FindNetCDF defines targets:
--   - NetCDF_VERSION [4.7.4]
--   - NetCDF_PARALLEL [TRUE]
--   - NetCDF_C_CONFIG_EXECUTABLE [/lcrc/project/OW_UFS/HPC-Stack/bin/nc-config]
--   - NetCDF::NetCDF_C [SHARED] [Root: /lcrc/project/OW_UFS/HPC-Stack] Lib: /lcrc/project/OW_UFS/HPC-Stack/lib/libnetcdf.so
--   - NetCDF_Fortran_CONFIG_EXECUTABLE [/lcrc/project/OW_UFS/HPC-Stack/bin/nf-config]
--   - NetCDF::NetCDF_Fortran [SHARED] [Root: /lcrc/project/OW_UFS/HPC-Stack] Lib: /lcrc/project/OW_UFS/HPC-Stack/lib/libnetcdff.so
-- Found MPI_Fortran: /gpfs/fs1/home/software/openmpi/4.1.2/bebop-bdw/lib/libmpi_usempif08.so (found version "3.1")
-- Found MPI: TRUE (found version "3.1")
-- Found OpenMP_Fortran: -fopenmp (found version "4.5")
-- Found OpenMP: TRUE (found version "4.5") found components: Fortran
-- Found bacio: /lcrc/project/OW_UFS/HPC-Stack/lib/libbacio_4.a (found version "2.4.0")
-- Found crtm: /lcrc/project/OW_UFS/HPC-Stack/lib/libcrtm.a (found version "2.3.0")
-- Found NetCDF: /lcrc/project/OW_UFS/HPC-Stack/include (found suitable version "4.7.4", minimum required is "4.3.3") found components: C Fortran
-- FindNetCDF defines targets:
--   - NetCDF_VERSION [4.7.4]
--   - NetCDF_PARALLEL [TRUE]
--   - NetCDF_C_CONFIG_EXECUTABLE [/lcrc/project/OW_UFS/HPC-Stack/bin/nc-config]
--   - NetCDF::NetCDF_C [SHARED] [Root: /lcrc/project/OW_UFS/HPC-Stack] Lib: /lcrc/project/OW_UFS/HPC-Stack/lib/libnetcdf.so
--   - NetCDF_Fortran_CONFIG_EXECUTABLE [/lcrc/project/OW_UFS/HPC-Stack/bin/nf-config]
--   - NetCDF::NetCDF_Fortran [SHARED] [Root: /lcrc/project/OW_UFS/HPC-Stack] Lib: /lcrc/project/OW_UFS/HPC-Stack/lib/libnetcdff.so
-- Found ZLIB: /lcrc/project/OW_UFS/HPC-Stack/lib/libz.a (found version "1.2.11")
-- Found MPI: TRUE (found version "3.1") found components: C Fortran
-- Found ESMF library: /lcrc/project/OW_UFS/HPC-Stack/lib/libesmf.a
CMake Error at /gpfs/fs1/software/centos7/spack-latest/opt/spack/linux-centos7-x86_64/gcc-6.5.0/cmake-3.20.3-vedypwm/share/cmake-3.20/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find ESMF: Found unsuitable version "..", but required is at
  least "8.0.0" (found , )
Call Stack (most recent call first):
  /gpfs/fs1/software/centos7/spack-latest/opt/spack/linux-centos7-x86_64/gcc-6.5.0/cmake-3.20.3-vedypwm/share/cmake-3.20/Modules/FindPackageHandleStandardArgs.cmake:592 (_FPHSA_FAILURE_MESSAGE)
  cmake/FindESMF.cmake:125 (find_package_handle_standard_args)
  CMakeLists.txt:57 (find_package)

-- Configuring incomplete, errors occurred!
See also "/lcrc/project/OW_UFS/UFS_2.0/ufs-srweather-app/build/src/UFS_UTILS/src/UFS_UTILS-build/CMakeFiles/CMakeOutput.log".
-- Found PNG: /lcrc/project/OW_UFS/HPC-Stack/lib64/libpng.a (found version "1.6.35")
-- Found g2: /lcrc/project/OW_UFS/HPC-Stack/lib64/libg2_4.a (found version "3.4.5")
make[2]: *** [src/UFS_UTILS/src/UFS_UTILS-stamp/UFS_UTILS-configure] Error 1
make[1]: *** [src/CMakeFiles/UFS_UTILS.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
-- Found g2tmpl: /lcrc/project/OW_UFS/HPC-Stack/lib/libg2tmpl.a (found version "1.10.0")
-- Found bacio: /lcrc/project/OW_UFS/HPC-Stack/lib/libbacio_4.a (found version "2.4.0")
-- Found bacio: /lcrc/project/OW_UFS/HPC-Stack/lib/libbacio_4.a (found version "2.4.0")
-- Found w3emc: /lcrc/project/OW_UFS/HPC-Stack/lib64/libw3emc_4.a (found version "2.9.2")
-- Found MPI: TRUE (found version "3.1") found components: Fortran
-- Found nemsio: /lcrc/project/OW_UFS/HPC-Stack/lib64/libnemsio.a (found version "2.5.4")
-- Found sfcio: /lcrc/project/OW_UFS/HPC-Stack/lib/libsfcio.a (found version "1.4.0")
-- Found sigio: /lcrc/project/OW_UFS/HPC-Stack/lib/libsigio.a (found version "2.3.0")
-- Found OpenMP_Fortran: -fopenmp (found version "4.5")
-- Found sp: /lcrc/project/OW_UFS/HPC-Stack/lib/libsp_4.a (found version "2.3.3")
-- Found w3nco: /lcrc/project/OW_UFS/HPC-Stack/lib/libw3nco_4.a (found version "2.4.0")

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

I used these modules: 1) cmake/3.20.3-vedypwm   2) openmpi/4.1.2   3) anaconda/4.4.0   4) gcc/9.2.0-pkmzczt
And I put 
export PATH="/lcrc/project/OW_UFS/HPC-Stack/bin:$PATH"
export LD_LIBRARY_PATH="/lcrc/project/OW_UFS/HPC-Stack/lib:$LD_LIBRARY_PATH"
export CMAKE_PREFIX_PATH="/lcrc/project/OW_UFS/HPC-Stack"
in bashrc

## Additional Context

* Machine: Centos-based HPC
* Compiler: GCC/9.2.0

The build log is attached.
[build.out.txt](https://github.com/ufs-community/ufs-srweather-app/files/9047400/build.out.txt)

Thanks in advance,
Haochen

**Comment by htan2013** [comment]
Error resolved by set "export ESMFMKFILE="/path_of_your_esmf.mk/esmf.mk".

New error occured: 

Warning: Type mismatch in argument 'grid' at (1); passed REAL(4) to REAL(8) [-Wargument-mismatch]
[ 41%] Building Fortran object sorc/sfc_climo_gen.fd/CMakeFiles/sfc_climo_gen_lib.dir/source_grid.F90.o
[ 38%] Building Fortran object sorc/ncep_post.fd/CMakeFiles/upp.dir/CALRCH.f.o
[ 39%] Building Fortran object sorc/ncep_post.fd/CMakeFiles/upp.dir/CALSTRM.f.o
[ 40%] Building Fortran object sorc/ncep_post.fd/CMakeFiles/upp.dir/CALTAU.f.o
[ 42%] Building Fortran object sorc/grid_tools.fd/regional_esg_grid.fd/CMakeFiles/regional_esg_grid.dir/pmat4.f90.o
[ 40%] Building Fortran object sorc/ncep_post.fd/CMakeFiles/upp.dir/CALTHTE.f.o
[ 41%] Building Fortran object sorc/ncep_post.fd/CMakeFiles/upp.dir/CALVESSEL.f.o
[ 41%] Building Fortran object sorc/ncep_post.fd/CMakeFiles/upp.dir/CALVIS.f.o
[ 42%] Building Fortran object sorc/ncep_post.fd/CMakeFiles/upp.dir/CALVIS_GSD.f.o
[ 42%] Building Fortran object sorc/sfc_climo_gen.fd/CMakeFiles/sfc_climo_gen_lib.dir/model_grid.F90.o
[ 43%] Building Fortran object sorc/ncep_post.fd/CMakeFiles/upp.dir/CALWXT_DOMINANT.f.o
[ 44%] Building 
Fortran object sorc/ncep_post.fd/CMakeFiles/upp.dir/CALWXT_EXPLICIT.f.o
[ 43%] Building Fortran object sorc/chgres_cube.fd/CMakeFiles/chgres_cube_lib.dir/grib2_util.F90.o
[ 43%] Building Fortran object sorc/chgres_cube.fd/CMakeFiles/chgres_cube_lib.dir/static_data.F90.o
[ 43%] Building Fortran object sorc/fvcom_tools.fd/CMakeFiles/fvcom_tools_lib.dir/module_nwp_base.f90.o
/lcrc/project/OW_UFS/UFS_2.0/ufs-srweather-app/src/UFS_UTILS/sorc/fvcom_tools.fd/module_nwp_base.f90:16:37:

   16 |    use kinds, only: r_kind, r_single, rmissing
      |                                     1
Error: Symbol 'rmissing' referenced at (1) not found in module 'kinds'
make[5]: *** [sorc/fvcom_tools.fd/CMakeFiles/fvcom_tools_lib.dir/module_nwp_base.f90.o] Error 1
make[4]: *** [sorc/fvcom_tools.fd/CMakeFiles/fvcom_tools_lib.dir/all] Error 2
make[4]: *** Waiting for unfinished jobs....
[ 44%] Building Fortran object sorc/ncep_post.fd/CMakeFiles/upp.dir/CALWXT.f.o
/lcrc/project/OW_UFS/UFS_2.0/ufs-srweather-app/src/UPP/sorc/ncep_post.fd/CALWXT.f:101:19:

  101 |       DO 800 I=1,IM


The build log is attached.
[build.pdf](https://github.com/ufs-community/ufs-srweather-app/files/9048703/build.pdf)

**Comment by natalie-perlin** [comment]
Please see the updates on the same error report on UFS community forums:
[https://forums.ufscommunity.org/threads/compilation-error-symbol-rmissing-not-found-module-kinds#comment-539](https://forums.ufscommunity.org/threads/compilation-error-symbol-rmissing-not-found-module-kinds#comment-539)
