### ISSUE TITLE
User specified output grid

### ISSUE THREAD

**Issue by ericaligo-NOAA** [ufs-community/ufs-srweather-app#330]
## Description
Allow the user to specify grid type and dimensions in config.sh that will be used in model_configure

## Solution
In the past, one could specify the following parameters in config.sh, and this information would be used in model_configure. In this example, the model was interpolated to a regional lat lon grid:

WRTCMP_output_grid="regional_latlon"
WRTCMP_lon_lwr_left="-135"
WRTCMP_lat_lwr_left="22.0"
WRTCMP_lon_upr_rght="-60"
WRTCMP_lat_upr_rght="53.5"
WRTCMP_dlon="0.03"
WRTCMP_dlat="0.03"

## Alternatives (optional)
None.
## Related to (optional)
None.

**Comment by gspetro-NOAA** [comment]
@MichaelLueken It seems like this is already in the SRW App. Is there more work to do, or can I close the issue?

**Comment by MichaelLueken** [comment]
@gspetro-NOAA It does appear as though this functionality is already in the SRW App.  We even have several `custom_grid` WE2E tests that do this as well.  This can be closed.
