### ISSUE TITLE
Update container docs with new multi-node Rocoto container option

### ISSUE THREAD

**Issue by gspetro-NOAA** [ufs-community/ufs-srweather-app#338]
## Description
Until recently, use of a container has has been limited to a single node, and users have had to run the workflow using stand-alone scripts instead of Rocoto. This has changed, but the documentation needs updates. 

## Solution
Update the documentation to reflect the fact that the container can now be run across nodes with Rocoto.

**Comment by MichaelLueken** [comment]
Completed by #339
