### ISSUE TITLE
Default case from provided example config.community.sh file fails on most Tier-1 platforms

### ISSUE THREAD

**Issue by mkavulich** [ufs-community/ufs-srweather-app#341]
## Expected behavior
Running the default case from the provided `config.community.sh` file will work "out-of-the-box" on tier 1 platforms.

## Current behavior
The default case will not run unless a location containing the test data is manually specified in the `config.sh` file.

## Machines affected
All machines aside from Jet will fail if the default data location is not manually specified.

## Steps To Reproduce
1. `cd ush`
2. `cp config.community.sh  config.sh`
3. `./generate_FV3LAM_wflow.py`
4. Run the experiment with rocoto

Depending on the platform, this will result in a failure at the get_extrn_ics/get_extrn_lbcs step, or it may succeed (on Jet, where a default data location is present).

## Possible Implementation
An initial fix was proposed in https://github.com/ufs-community/regional_workflow/pull/820, but there was disagreement on the best approach. The regional_workflow --> UFS SRW merger meant that this PR needed to be closed and discussion moved to this repository, so absent a consensus on a fix we will continue here in an issue.

**Comment by MichaelLueken** [comment]
@mkavulich - The `community` WE2E test, which uses `config.community.yaml`, successfully passes on Tier-1 platforms.

Additionally, using:
- `cd ush`
- `cp config.community.yaml config.yaml`
- Manually changing the machine and account in `config.yaml` for each platform
- `./generate_FV3LAM_wflow.py`

the default case successfully passes on all platforms.  Can this issue be closed?

**Comment by MichaelLueken** [comment]
Closing issue now.  If you feel this issue hasn't been addressed, please feel free to either reopen this issue or open a new issue.
