### ISSUE TITLE
Inconsistent ensemble index digits

### ISSUE THREAD

**Issue by mkavulich** [ufs-community/ufs-srweather-app#350]
Original issue opened by @JiliDong-NOAA migrated from regional_workflow repository: [ufs-community/regional_workflow#829](https://github.com/ufs-community/regional_workflow/issues/829)

# Description

Ensemble forecasts failed before starting when creating input.nml due to inconsistent ensemble index digits in ush/set_FV3nml_ens_stoch_seeds.py

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Run regional_workflow using SPP with 10 ensemble members
2. make_ics and make_lbcs successfully finish
3. forecast job failed when creating input.nml for individual members with the following error. See below the run_dir is "mem01" while ush/set_FV3nml_ens_stoch_seeds.py is looking for "mem1"

```
Creating links in the current run directory (run_dir) to fixed (i.e.
static) files in the FIXam directory:
  FIXam = "/scratch1/NCEPDEV/fv3-cam/Jili.Dong/srw_workflow/expt_dirs/test_spp/fix_am"
  run_dir = "/scratch1/NCEPDEV/fv3-cam/Jili.Dong/srw_workflow/expt_dirs/test_spp/2022040500/mem01"


Creating links in the current run directory to cycle-independent model
input files in the main experiment directory...
usage: set_FV3nml_ens_stoch_seeds.py [-h] -o OUTFILE [-c [FILE, SECTION]]
                                     [-i INPUT_NML] [-n NML] [-t {nml,yaml}]
                                     [-u YAML STRING] [-q]
set_FV3nml_ens_stoch_seeds.py: error: argument -o/--outfile: /scratch1/NCEPDEV/fv3-cam/Jili.Dong/srw_workflow/expt_dirs/test_spp/2022040500/mem1/input.nml is not a writable path!
  File "/scratch1/NCEPDEV/fv3-cam/Jili.Dong/srw_workflow/ufs-srweather-app/regional_workflow/ush/set_FV3nml_ens_stoch_seeds.py", line 143, in <module>
    set_FV3nml_ens_stoch_seeds(str_to_type(args.cdate))
  File "/scratch1/NCEPDEV/fv3-cam/Jili.Dong/srw_workflow/ufs-srweather-app/regional_workflow/ush/set_FV3nml_ens_stoch_seeds.py", line 110, in set_FV3nml_ens_stoch_seeds
    print_err_msg_exit(dedent(f'''
  File "/scratch1/NCEPDEV/fv3-cam/Jili.Dong/srw_workflow/ufs-srweather-app/regional_workflow/ush/python_utils/print_msg.py", line 18, in print_err_msg_exit
    traceback.print_stack(file=sys.stderr)

```

## Additional Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Machine
* Compiler
* Reference other issues or PRs in other repositories that this is related to, and how they are related.

## Output

Log file is on Hera:

/scratch1/NCEPDEV/fv3-cam/Jili.Dong/srw_workflow/expt_dirs/test_spp/log/save/run_fcst_mem01_2022040500.log

**Comment by danielabdi-noaa** [comment]
@JiliDong-NOAA @mkavulich I may have fixed this bug inadvertently in PR #348 because the same piece of code in `ush/set_FV3nml_ens_stoch_seeds.py` caused me problems in NCO mode. It was not really necessary to know where to put the `input.nml` file because it is always put in the working directory it is called from, so I removed that piece of code.

I've run a test to make sure it works by modifying `community_ensemble_2mems_stoch` test case to do 10 ensembles instead.
The result is here:
```
/scratch1/BMC/zrtrr/Daniel.Abdi/rrfs/benchmark-test/community_ensemble_2mems_stoch
```
