### ISSUE TITLE
Post-repo merge cleanup

### ISSUE THREAD

**Issue by mkavulich** [ufs-community/ufs-srweather-app#351]
## Description
Several things need to be cleaned up after the regional_workflow merge. This issue will track the progress of those tasks.

## Solution

 - [x] Resolve or migrate remaining issues in regional_workflow
 - [x] Merge duplicate test/ and tests/ directories
 - [x] Resolve redundancies in regional_workflow-based modules
 - [x] Move relevant wiki content from regional_workflow to ufs-srweather-app
 - [ ] Update documentation
 - [ ] Please add other tasks to this issue as they are discovered

**Comment by natalie-perlin** [comment]
A issue for the backward compatibility of the SRW release/public-v2 which uses regional_workflow repo, similarly named branch. Do we need to address the merge, or the merged repository will be used only for the develop branch and releases from now onward?

**Comment by mkavulich** [comment]
@natalie-perlin The regional_workflow repository will remain intact for people using old releases, there are no plans to remove it in the near future. New development and future releases will use the merged repository.

**Comment by gspetro-NOAA** [comment]
@mkavulich Is this issue resolved? (Just trying to do some cleanup.)

**Comment by mkavulich** [comment]
The only thing I don't know about is the wiki migration, if there's any wiki pages in regional_workflow that still need to be migrated to srw (unlikely at this point). Everything else has been completed.

**Comment by gspetro-NOAA** [comment]
It looks like you created a page in the SRW App wiki with instructions for how to move development from forks of the `regional_workflow` repository. The `regional_workflow` wiki itself contains general information, which is now included in updated form in the SRW App wiki. The `regional_workflow` wiki also contains contribution info, which is no longer relevant here but is included in updated form in the SRW repo. I think we can check off the wiki step and close this issue. :)
