### ISSUE TITLE
make GWD orog generation into a function

### ISSUE THREAD

**Issue by mkavulich** [ufs-community/ufs-srweather-app#356]
Original issue opened by @JiliDong-NOAA migrated from regional_workflow repository: https://github.com/ufs-community/regional_workflow/issues/570

## Description
Request to put the GWD orog generation in make_orog (e.g. the contents of "if [ "${CCPP_PHYS_SUITE}" = "FV3_HRRR" ]; then") into a separate function to make the scripts more modular.

## Solution
Convert GWD orog generation to a function

## Requirements**
Convert GWD orog generation to a function

## Acceptance Criteria (Definition of Done)
Convert GWD orog generation to a function

**Comment by gspetro-NOAA** [comment]
@JiliDong-NOAA Is this still a desired SRW App enhancement? If so, could you provide more information on what you're looking for? If not, feel free to close the issue.

**Comment by JiliDong-NOAA** [comment]
I believe the capability has been added and the issue can be closed.
