### ISSUE TITLE
Update CODEOWNERS file to include my name

### ISSUE THREAD

**Issue by MichaelLueken** [ufs-community/ufs-srweather-app#360]
## Description
As the EPIC code manager for the UFS-SRW-App, I need my GitHub username to be included in the ./github/CODEOWNERS file.

## Solution
In the text/update-CODEOWNERS-file branch in my fork of the UFS-SRW-App repo, I have added my name to the ./github/CODEOWNERS file.

**Comment by mkavulich** [comment]
Completed by #361
