### ISSUE TITLE
Minor doc updates to prepare for SRW v2.1.0 release

### ISSUE THREAD

**Issue by gspetro-NOAA** [ufs-community/ufs-srweather-app#379]
## Description
A few quick updates to links, file structure, glossary. 

## Solution
- Add Intersphinx links & remove hpc-stack submodule
- Put tables into “tables” directory instead of directly under "source"
- Update stochastic physics link
- Remove glossary duplicates (sometimes two terms, singular and plural, are connected with one definition)

**Comment by MichaelLueken** [comment]
Completed by #380
