### ISSUE TITLE
Consolidate verification footprint

### ISSUE THREAD

**Issue by mkavulich** [ufs-community/ufs-srweather-app#381]
Original issue opened by @michelleharrold  migrated from regional_workflow repository: https://github.com/ufs-community/regional_workflow/issues/601

## Description
PR https://github.com/ufs-community/regional_workflow/pull/575 added ensemble verification to the workflow. In the review, it was identified that the deterministic and ensemble verification footprint could be compacted. There are currently multiple JREGIONAL_RUN_VX* and exregional* scripts that are fairly redundant; in addition, there are verification tasks in ush/templates/FVLAM_wflow.xml that could be reduced by using jinja.

## Solution
We can likely combine JREGIONAL_RUN_VX* into one since there are minimal differences [potentially by setting arguments or environment variables (in the XML)]. The same can be investigated for the exregional scripts. Jinja can be used to reduce the number of tasks in ush/templates/FVLAM_wflow.xml (e.g., VX_ENSGRID_MEAN_24h_TN) so that instead of having one for each GRID vs. POINT, cycle hour, and MEAN vs. PROB vs. nothing combination, those parameters are looped over in the XML using jinja syntax.

**Comment by gspetro-NOAA** [comment]
@gsketefian @MichaelLueken Have the VX PRs in the past 2 years addressed this issue?

**Comment by gsketefian** [comment]
@gspetro-NOAA Yes, the PRs in the past couple of years have addressed this issue to a great extent by consolidating many of the vx tasks, ex-scripts, and METplus config files.  I think it's ok to close this.  If further consolidation is desired, we can open a new issue.  But maybe also get @mkavulich 's take on it.
