### ISSUE TITLE
Update documentation for config files

### ISSUE THREAD

**Issue by mkavulich** [ufs-community/ufs-srweather-app#392]
## Description:
All documentation still refers to old "shell" style config files rather than the new yaml format introduced in

In addition, the ability to use variables rather than set values (aka "template" variables) in config files was introduced in [regional_workflow PR #650](https://github.com/ufs-community/regional_workflow/pull/650). Documentation exists in the WE2E test configuration file `tests/WE2E/test_configs/wflow_features/config.template_vars.yaml`, but it describes the old (pre-yaml) config format, which is outdated. This file must be updated, and documentation for these template variables added to the users guide.

## Solution:
Update the necessary documentation in the Users Guide and the above-mentioned file.

## Requirements**
 - [ ] Update all references in users guide to config.sh to config.yaml, and related file naming
 - [ ] Update all formatting in users guide to account for yaml formatting of config files
 - [ ] Update above-mentioned template variable documentation, and add to users guide.

## Related to:
Related to issue opened by @gsketefian migrated from regional_workflow repository: https://github.com/ufs-community/regional_workflow/issues/651

**Comment by MichaelLueken** [comment]
@gspetro-NOAA PR #425 mentioned that the update only partially covered this issue.  Is additional work required, or can this issue be closed as well?  Thanks!

**Comment by gspetro-NOAA** [comment]
@mkavulich might be the best one to make that decision. I believe the comments in tests/WE2E/test_configs/wflow_features/config.template_vars.yaml still need to be updated. I'm a little unclear on _how_ they should be updated though. I did add template variables to the ConfigWorkflow chapter if they were listed in config_defaults.yaml. Could be good to have someone check whether additional updates are necessary. It might still be worth adding an explanation of template variable use in the Test chapter or the Running the SRW App chapter. But feel free to offer other suggestions on where you think such an explanation should go! I don't see an obvious place.

**Comment by mkavulich** [comment]
This has been resolved for a while
