### ISSUE TITLE
Experiment directory with `@` character does not run properly

### ISSUE THREAD

**Issue by danielabdi-noaa** [ufs-community/ufs-srweather-app#395]
## Expected behavior

SRW app should run when experiment directory contains @ character.

## Current behavior

SRW app fails to run properly when the experiment directory contains the `@` character. This was revealed during Jenkins testing on Cheyene, where both gnu and intel are tested and the latter is assigned a different experiment directory differentiated by `expt_dir@2`. It looks like rocoto `<cyclestring>&LOGDIR;</cyclesctring>` changes the `@` character to `%` causing all sorts of problems. Now a an underscore is used for Jenkins but the @ issue still exists.

## Machines affected

All

## Steps To Reproduce

Add to your experiment directory path the `@` character.

## Detailed Description of Fix (optional)

Could be a rocoto issue.

## Output (optional)

You will get the log files in a different directory where the `@` is replaced with `%`.  The LOGDIR generated by rocoto changes
`test@2` to `test%2`
```
#! /bin/sh
#SBATCH --account=zrtrr
#SBATCH --qos=batch
#SBATCH --partition=service
#SBATCH --nodes=1-1
#SBATCH --tasks-per-node=1
#SBATCH -t 00:45:00
#SBATCH --job-name=get_extrn_ics
#SBATCH -o /scratch2/BMC/gsd-hpcs/Daniel.Abdi/expt_dirs/test%2/custom_GFDLgrid/log/get_extrn_ics_2019070100.log
#SBATCH --comment=22bb59625914e244ba065a866351335e
export GLOBAL_VAR_DEFNS_FP='/scratch2/BMC/gsd-hpcs/Daniel.Abdi/expt_dirs/test@2/custom_GFDLgrid/var_defns.sh'
export PDY='20190701'
export cyc='00'
export subcyc='00'
export LOGDIR='/scratch2/BMC/gsd-hpcs/Daniel.Abdi/expt_dirs/test%2/custom_GFDLgrid/log'
export ICS_OR_LBCS='ICS'
/scratch2/BMC/gsd-hpcs/Daniel.Abdi/ufs-srweather-app/ush/load_modules_run_task.sh "get_extrn_ics" "/scratch2/BMC/gsd-hpcs/Daniel.Abdi/ufs-srweather-app/jobs/JREGIONAL_GET_EXTRN_MDL_FILES"
```

**Comment by christopherwharrop-noaa** [comment]
The `@` character is used in Rocoto `<cyclestr>` tags to designate various date/time components.  If you want to use text in a `<cyclestr>` that contains an actual `@` character, you will need to escape it by using two consecutive `@@`.  The `@` characters in `<cyclestr>` tags are replaced internally with `%` so that the `strftime` method can be called to expand the string into the values represented by the date/time fields.

**Comment by christopherwharrop-noaa** [comment]
Rocoto doesn't use `%` characters directly because the `%` character has special meaning in XML that interferes with that function, causing the XML parsers to fail.

**Comment by christopherwharrop-noaa** [comment]
Another solution would be to put the portion of the string containing the `@` character outside of the `<cyclstr>` tag so that `<cyclestr>` only contains characters to be interpreted as date/time.  

For example, replace:

```
<cyclestr>my silly @ string for time @Y@m@d@H@M</cyclestr>
```
with
```
my silly @ string for time <cyclestr>@Y@m@d@H@M</cyclestr>

```

**Comment by christopherwharrop-noaa** [comment]
Another solution, specific to this scenario, is to not use `cyclestr>` tags when there is nothing in the string that is dependent on the cycle.  In the example cited here, no part of the `LOGDIR` path contains any date or time information.  So you can just completely eliminate the use of `<cyclstr>` for this particular instance.

**Comment by dshawul** [comment]
@christopherwharrop-noaa Thanks for the explanation! I will try to move the cyclestring out of the LOGDIR path.
