### ISSUE TITLE
Allow users to specify their own vertical coordinate configuration

### ISSUE THREAD

**Issue by mkavulich** [ufs-community/ufs-srweather-app#397]
Original issue opened by @JeffBeck-NOAA migrated from regional_workflow repository: https://github.com/ufs-community/regional_workflow/issues/524

## Description
Currently the vertical coordinate configuration is hard-coded for the UFS SRW App. We should introduce the capability for users to specify their own vertical coordinate configuration.

## Solution
Add an option to set npz_type in the namelist to 'input', which then allows a user to place a text file with the vertical level ak/bks in the run directory to be read in by the model. Also, from @BenjaminBlake-NOAA: "There is a small block of code changes to fv_eta.F90 in the ufs-weather-model code that allows you to use npz_type = 'input'".

Need to confirm whether defining 'npz' or 'levp' values in the namelist are still required when using this method.

**Comment by gspetro-NOAA** [comment]
Was this issue resolved by PR #813 and PR #888 ? Seems like we could close it.

**Comment by mkavulich** [comment]
@gspetro-NOAA Given that you tested the capability and it works with #888, I'd say this is complete!
