### ISSUE TITLE
Discrepancy in NetCDF Version used in Instructions for Jet Install and Runtime Modules

### ISSUE THREAD

**Issue by dmwright526** [ufs-community/ufs-srweather-app#40]
On the installation instructions for Jet (https://github.com/ufs-community/ufs-srweather-app/blob/master/docs/README_jet_intel.txt) it uses netcdf/4.6.1, but in the module files for at least make_grid and make_orog use netcdf/4.7.0. This discrepancy results in runtime failures for at least make_grid and make_orog in the workflow.

Switching the module files for the above two tasks to netcdf/4.6.1 does solve the issue, but it might make more sense to adjust the installation instructions to use 4.7.0. I am not sure if 4.6.1 is specifically needed during the installation process.

**Comment by mkavulich** [comment]
Thanks for this report David; the newest README instructions that build Jet have been updated but not yet pushed to the repository. These updated instructions will be pushed to this repo once this NCEPLIBS update is merged: https://github.com/NOAA-EMC/NCEPLIBS/pull/148

If you need to build on Jet right now, updated instructions can be found on my fork (https://github.com/mkavulich/ufs-srweather-app/tree/build_READMEs/docs). But I'd recommend waiting until the official update if possible.

**Comment by dmwright526** [comment]
Thanks for the information, @mkavulich ! I caught this during a fresh build on Jet, but it sounds like this has already been corrected in the future PR. Thanks!
