### ISSUE TITLE
Remove `ENV_INIT_SCRIPTS_FPS` because it seems redundant.

### ISSUE THREAD

**Issue by danielabdi-noaa** [ufs-community/ufs-srweather-app#401]
## Description

 
`ENV_INIT_SCRIPTS_FPS` seem to be redundant. The idea behind this variable is to setup Lmod for each task, but there are already scripts that do that under the directory `etc/lmod-setup.sh`. Moreover, calling `init_env` and `source etc/lmod-setu.sh` in the same script, such as `ush/load_modules_run_task.sh`, calls lmod initialization twice. On most systems, `ENV_INIT_SCRIPTS_FPS` is set to a default value `/etc/profile` which probably doesn't achieve much.
```
  ENV_INIT_SCRIPTS_FPS:
    - /etc/profile
```
However, on gaea
```
  ENV_INIT_SCRIPTS_FPS:
    - /etc/profile
    - /lustre/f2/dev/role.epic/contrib/Lmod_init.sh
```
and singularity
```
  ENV_INIT_SCRIPTS_FPS:
    - /usr/share/lmod/6.6/init/profile
```
We can't get rid of `etc/lmod-setup.sh` since it is sourced to setup up the environment for workflow generation so `ENV_INIT_SCRIPTS_FPS` has to be the one to go. Moreover, there will only be one place in the code to setup Lmod after this.
There used to be a third place for Lmod setup which came from `regional_workflow`, but that one is removed now.

## Solution

Get rid of `ENV_INIT_SCRIPTS_FPS` and rely on `etc/lmod-setup.sh`. The latter is currently called in `load_modules_run_task.sh` which is probably why `ENV_INIT_SCRIPTS_FPS` is needed for Gaea.

## Requirements**

None

## Acceptance Criteria (Definition of Done)

Get rid of `ENV_INIT_SCRIPTS_FPS` and make sure all fundamental tests pass on all platforms.

## Dependencies (optional)

None

**Comment by MichaelLueken** [comment]
Completed with #404
