### ISSUE TITLE
The option for using user-staged data on local machine is missed in the sample setting file (e.g., config.community.yaml).

### ISSUE THREAD

**Issue by panll** [ufs-community/ufs-srweather-app#408]
## Description

The option for using user-staged data on local machine is missed in the sample setting file (e.g., config.community.yaml).

## Solution
It can be added.

## Requirements**

No other update needed.

## Acceptance Criteria (Definition of Done)
The option for using the staged data on local disk is available to the users.

## Dependencies (optional)

No dependencies.

## Alternative Solutions (optional)
N/A

**Comment by danielabdi-noaa** [comment]
@panll Is this a new feature request or something missed during the transition to python?
Currently there are these options in `config_defaults.yaml` that are used by `run_WE2E` for user staged ics/lbcs i think.
```
  TEST_EXTRN_MDL_SOURCE_BASEDIR: ""
  TEST_PREGEN_BASEDIR: ""
  TEST_ALT_EXTRN_MDL_SYSBASEDIR_ICS: ""
  TEST_ALT_EXTRN_MDL_SYSBASEDIR_LBCS: ""
```

**Comment by panll** [comment]
@danielabdi-noaa It's the option USE_USER_STAGED_EXTRN_FILES in sample config file (e.g., config.community.sh in the old version). Thanks!
