### ISSUE TITLE
Update modulefiles to point to new EPIC maintained HPC-stack locations on Orion, Gaea, and Jet

### ISSUE THREAD

**Issue by MichaelLueken** [ufs-community/ufs-srweather-app#409]
## Description
EPIC maintained HPC-stack locations are available on Orion, Gaea, and Jet at the following locations:

Orion: `/work/noaa/epic-ps/hpc-stack/libs/intel/2022.1.2/modulefiles/stack`

Gaea: `/lustre/f2/pdata/ncep_shared/hpc-stack.epic/libs/intel/2021.3.0/modulefiles/stack`

Jet: `/lfs4/HFIP/hfv3gfs/nwprod/hpc-stack.epic/libs/intel/2022.1.2/modulefiles/stack`

We should update the paths to the modulefiles to these new EPIC maintained stacks.

## Solution
In the modulefiles for the ufs/srweather-app repo, the path to the hpc-stack will need to be updated to the EPIC maintained versions.

For Gaea, replace:

`module use /lustre/f2/dev/role.epic/contrib/hpc-stack/intel-2021.3.0/modulefiles/stack`

with:

`module use /lustre/f2/pdata/ncep_shared/hpc-stack.epic/libs/intel/2021.3.0/modulefiles/stack`

For Jet, replace:

`module use /lfs4/HFIP/hfv3gfs/nwprod/hpc-stack/libs/modulefiles/stack`

with:

`module use /lfs4/HFIP/hfv3gfs/nwprod/hpc-stack.epic/libs/intel/2022.1.2/modulefiles/stack`

For Orion, replace:

`module use /apps/contrib/NCEP/libs/hpc-stack/modulefiles/stack`

with:

`module use /work/noaa/epic-ps/hpc-stack/libs/intel/2022.1.2/modulefiles/stack`

## Acceptance Criteria (Definition of Done)
The SRW app needs to build and the fundamental WE2E need to successfully run through to completion on Jet, Orion, and Gaea.

**Comment by natalie-perlin** [comment]
A [PR-419](https://github.com/ufs-community/ufs-srweather-app/pull/419) is created to address the modulefile updates, yet with different installation paths that are more integrated into the environment needed by SRW.

**Comment by MichaelLueken** [comment]
Issue #427 supersedes this work.  Closing this issue.
