### ISSUE TITLE
Convert TCL format modulefiles to Lua format

### ISSUE THREAD

**Issue by MichaelLueken** [ufs-community/ufs-srweather-app#410]
## Description
The UFS-Weather Model has been updated, converting the old TCL format modulefiles to Lua format.  This needs to be done for the SRW app as well.

## Solution
Convert the current SRW app modulefiles from TCL format to Lua format.

## Acceptance Criteria (Definition of Done)
After converting the TCL format modulefiles to Lua format, the SRW app should successfully build and the fundamental WE2E tests should pass.

**Comment by danielabdi-noaa** [comment]
@MichaelLueken Is someone working on this? If not, i can start looking at it.

**Comment by MichaelLueken** [comment]
Completed by #413
