### ISSUE TITLE
CIs should test NCO mode

### ISSUE THREAD

**Issue by danielabdi-noaa** [ufs-community/ufs-srweather-app#416]
## Description

 
Currently CIs (Jenkins and Github actions) test only in "community" mode because it is easier to figure out the location and name of log files. The older NCO implementation used to store log files in the same place as Community mode so it was not difficult for the CIs to figure the state of workflow runs. However, the new NCO mode stores log files elsewhere and the names of log files also contain unique IDs making things difficult to discern. Since SRW app can now run any test case in either mode, it was easier to run all tests in "community" mode even for those test cases that are supposed to be run in NCO mode.

So currently we are **exposed** to the situation where a PR breaks NCO mode without the CIs noticing it.

## Solution

- Jenkins looks like the easier one to fix so that it can run a test case in NCO mode because it parses only `log.launch_wflow`.
- Github actions parses `FV3LAM_wflow.log` etc and the code for that is not part of SRW app so it needs coordination with the github actions CI developers.

## Requirements**

None

## Acceptance Criteria (Definition of Done)

Modify `setup_WE2E_tests.sh` to run test cases in either "nco" or "community" mode, whatever is specified in the config file, instead of overriding mode to "community". Make sure all fundamental tests, currently there is on NCO test case, pass on all systems.

## Dependencies (optional)

None

## Alternative Solutions (optional)

Create symlinks to the log files under `EXPTDIR/log` with the workflow IDs removed from the names. This should allow both Jenkins and Github actions to test NCO mode properly without any changes needed on the CIs side.

**Comment by MichaelLueken** [comment]
Completed with #418.
