### ISSUE TITLE
Run with gnu and MacOSX

### ISSUE THREAD

**Issue by jwolff-ncar** [ufs-community/ufs-srweather-app#42]
Also serves to put together documentation for running stand-alone (outside of Rocoto) scripts.

**Comment by mkavulich** [comment]
Minor update: GNU testing for the build is now successful...I had to rely on GNU 10.2 which has stricter requirements that do not allow most components of the code to build by default. The final change which will make the full build possible on my Mac with GNU 10 is proposed in this PR for UFS_UTILS: https://github.com/NOAA-EMC/UFS_UTILS/pull/205

**Comment by mkavulich** [comment]
Still working on this...main hangups are in regional_workflow, documented in issue in that repository: https://github.com/NOAA-EMC/regional_workflow/issues/369

**Comment by mkavulich** [comment]
Work is mostly done; changes in this branch: https://github.com/mkavulich/regional_workflow/tree/update_scripts_for_macos

Having issues with my laptop specifically that are preventing finishing up the final touches, will open PR once that is resolved.

**Comment by mkavulich** [comment]
Completed with #97
