### ISSUE TITLE
Integrate BUFR post-processing codes into SRW App

### ISSUE THREAD

**Issue by MatthewPyle-NOAA** [ufs-community/ufs-srweather-app#423]
A working draft for now...

## Description

 

The operational RRFS system (based on the SRW app) will need to generate point forecast data in BUFR format.

## Solution

Integrate the code from https://github.com/NOAA-EMC/regional_bufr into the SRW App as a first step.  The build system will need work, as it is non-cmake and WCOSS-centric.  

## Requirements**

Needs a small number of NCEP libraries that should be available (W3NCO, BUFR) and NetCDF (v4.7.4 was used on WCOSS).  

## Acceptance Criteria (Definition of Done)

For this stage, just getting it included in the Externals.cfg so it gets pulled in with the other software, and also the ability for it to be built with the SRW App would be success.

**Comment by JeffBeck-NOAA** [comment]
@MatthewPyle-NOAA, if you are interested in seeing my final script modifications with your help to get the BUFR soundings working in the App, just let me know!

**Comment by JeffBeck-NOAA** [comment]
Looks like Terra has also migrated those scripts to a repo [here](https://github.com/NOAA-GSL/ufs-BUFR-sounding)!

**Comment by MatthewPyle-NOAA** [comment]
Thanks @JeffBeck-NOAA!     The codes have been updated a bit since then to get rid of some of the hardcoding (on vertical levels, and on the limit of the number of stations), and also eliminates support for non-FV3 models which strips down the software and the number of libraries needed to build it.

**Comment by JeffBeck-NOAA** [comment]
@MatthewPyle-NOAA, great to hear that!  Are they already running within the RRFS-A/B?  If so, the move to the SRW App shouldn't be too bad.

**Comment by MatthewPyle-NOAA** [comment]
Have done some initial work on getting it to build with cmake within the SRW app - only tested on WCOSS2/intel so far.  But progress...

**Comment by gspetro-NOAA** [comment]
@MatthewPyle-NOAA Is this enhancement to the SRW App still needed? It seems like the regional_bufr repo hasn't been touched in a year, and I know that a lot has changed with creation of rrfs-workflow and the SRW/RRFS divergence/convergence question.

**Comment by MatthewPyle-NOAA** [comment]
Had completely forgotten about this issue 2+ years later.  The code got folded into GSL's rrfs_utl repository for our needs.
