### ISSUE TITLE
Update BuildRunSRW chapter for v2.1 release

### ISSUE THREAD

**Issue by gspetro-NOAA** [ufs-community/ufs-srweather-app#426]
## Description
The BuildRunSRW chapter is a monster chapter. Users only need to build the app once but may run many experiments. They currently need to scroll through the entire build section to revisit instructions on running the app. 

## Solution
Separate the BuildRunSRW chapter into 2 chapters: BuildSRW and RunSRW. Additional reorganization and updates may prove useful. TBD.

**Comment by MichaelLueken** [comment]
Completed with #425
