### ISSUE TITLE
Remove my_load_any from modulefiles/srw_common.lua and use load_any

### ISSUE THREAD

**Issue by MichaelLueken** [ufs-community/ufs-srweather-app#429]
## Description
As part of the maintenance on Cheyenne last week, the version of Lmod was updated from `8.1.7` to `8.7.13`.  This version allows the use of `load_any` in `modulefiles/srw_common.lua`, rather than the temporary addition of `my_load_any`.  Now that `load_any` can be used, will remove `my_load_any` from `modulefiles/srw_common.lua` and use `load_any`.

## Solution
Remove `my_load_any` function from `modulefiles/srw_common.lua` and replace use of `my_load_any` with `load_any`.

## Requirements**
No new requirements are necessary (just needed an updated Lmod, which is now available).

## Acceptance Criteria (Definition of Done)
The SRW should be able to build and run on all machines without the use of the `my_load_any` function in `modulefiles/srw_common.lua`

**Comment by MichaelLueken** [comment]
@danielabdi-noaa While you were converting the TCL modulefiles to Lua, what type of errors were you seeing on Cheyenne that required you to create the my_load_any function until the Lmod `8.3.7` was made available?  Now that Cheyenne has Lmod `8.7.13`, I'm encountering errors just for `modulefiles/build_cheyenne_intel.lua`.  I'm seeing the following:

```
mlueken@cheyenne6:/glade/scratch/mlueken/ufs-srweather-app> module load build_cheyenne_intel 
Lmod has detected the following error:  The load_any function failed because it could not find any of the following modules : mapl/2.22.0-esmf-8.3.0b09 mapl/2.11.0-esmf-8.2.0

Please check the spelling or version number. Also try "module spider ..."

Also make sure that all modulefiles written in TCL start with the string #%Module

While processing the following module(s):
    Module fullname  Module Filename
    ---------------  ---------------
    srw_common       /glade/scratch/mlueken/ufs-srweather-app/modulefiles/srw_common.lua
```
If I comment out either:

`load_any("mapl/2.22.0-esmf-8.3.0b09", "mapl/2.11.0-esmf-8.2.0") from modulefiles/srw_common.lua`

or:

`load(pathJoin("mapl", os.getenv("mapl_ver") or "2.11.0-esmf-8.3.0b09")) from modulefiles/build_cheyenne_intel.lua`

then a mapl module is successfully found and loaded.  I can't figure out why this is the case.  Any insights you might have would be greatly appreciated.

@christopherwharrop-noaa I see that you added `module load mapl/2.11.0-esmf-8.3.0b09` to `modulefiles/build_cheyenne_intel` at [648fc79](https://github.com/ufs-community/ufs-srweather-app/commit/648fc79b7be7e94c618141de74ef9332066c4179).  Is there a reason why the Cheyenne Intel build requires this specific version of mapl?  Thanks!

**Comment by christopherwharrop** [comment]
@MichaelLueken - I don't think there was any specific reason to use that version of mapl other than consistency with ESMF.  It was a long time ago and I honestly can't remember why I added it at all.  The GNU modules don't even load mapl.  I will say that back then getting things to work on Cheyenne was pretty difficult, and there were a lot of inconsistencies between the various hpc-stack installations across all the platforms.  It's possible it is just a vestige of some sort of unexpected dependency requirement at the time.

**Comment by dshawul** [comment]
@MichaelLueken It was confused with the "load_any" command and failed with the first library it tried to used it `libpng` i think. If it is only mapl on cheyenne that is the problem, I suspect it is because we are trying to load it twice in `srw_common.lua` and `build_cheyenne`?

**Comment by danielabdi-noaa** [comment]
By the way, if I recall correctly Odin, a non Tier-1, platform also had Lmod version <8.3.7 so that needs to be updated too.

**Comment by MichaelLueken** [comment]
@dshawul Yes, mapl is being loaded in both `srw_common.lua` and `build_cheyenne_intel.lua`.  Attempting to use `unload("mapl")` in `build_cheyenne_intel.lua` didn't correct the issue.  It appears as though one of the loads need to be removed.  I'm leaning towards removing the specific version in `build_cheyenne_intel.lua`.  The fundamental tests were submitted and passed.  My concern would be that it was added when the GSI and RRFS modifications were added so the SRW app.  If this specific version is required for either the GSI or RRFS to work with the SRW app on Cheyenne for Intel, then I'd rather not break that functionality.

**Comment by MichaelLueken** [comment]
> By the way, if I recall correctly Odin, a non Tier-1, platform also had Lmod version <8.3.7 so that needs to be updated too.

Okay, so I shouldn't move forward with this change currently until the Lmod version has been updated on the Tier-2 platforms as well.

**Comment by danielabdi-noaa** [comment]
@MichaelLueken I think replacing with load_any is still a good idea. Odin has other problems besides that. If you look at the conda activation logic in `wflow_odin`, it is a mess. Somebody need to look at the system and make it more inline with other systems. 
I agree removing it in `build_cheyenne` is a safer option now that @christopherwharrop explained it.

**Comment by MichaelLueken** [comment]
Thanks @christopherwharrop-noaa and @danielabdi-noaa!  I will go ahead and move forward with the removal in `build_cheyenne_intel.lua` and bringing in load_any in `srw_common.lua`.
