### ISSUE TITLE
Remove effect of external environment on task specific environment

### ISSUE THREAD

**Issue by danielabdi-noaa** [ufs-community/ufs-srweather-app#435]
## Description

 
SRW app has modulefiles specific for each task, however, it looks like atleast on some systems it does rely on what
module is loaded, whether conda is activated etc before the task is executed. These two are conflicting, so we either make sure each task doesn't rely on external environment settings, OR remove the task modulefiles and rely on the environment being set by the parent shell.

## Solution

Preferred solution here is to make sure the task gets a clean environment unaffected by the parent shell.

## Requirements**

None

## Acceptance Criteria (Definition of Done)

- External environment should not affect what is going inside tasks. 
- Conda activate should work on all systems first time it is activated in `load_modules_run_task.sh`
- Pass all fundamental tests on all systems

## Dependencies (optional)

None

## Alternative Solutions (optional)

Remove the task specific modulefiles, and rely on the environment being set by the parent shell or a mix of both.

**Comment by MichaelLueken** [comment]
Completed with #436.
