### ISSUE TITLE
External model data files need to be removed from COMIN directory in nco mode

### ISSUE THREAD

**Issue by chan-hoo** [ufs-community/ufs-srweather-app#439]
## Description
The external model data files for IC/LBCS (nemsio, netcdf, or grib2) should be removed from the COMIN directory in the NCO mode because they are temporary files and are not used as input files of the run_fcst task.

## Solution
Put the data files into subdirectories like for_ICS and for_LBCS in get_extrn_mdl and remove the subdirectories once IC and LBC files are generated in make_ics and make_lbcs.

**Comment by MichaelLueken** [comment]
Completed with #440.
