### ISSUE TITLE
Rocoto XML generation needs to be more flexible 

### ISSUE THREAD

**Issue by christinaholtNOAA** [ufs-community/ufs-srweather-app#463]
## Description
The Rocoto XML is currently generated by filling in a set Jinja2 template. It is riddled with Jinja2 logic that allows for extensive configuration of existing workflow definitions that supports retrospective experiments running deterministic cold start forecasts and ensemble forecasts, along with data preprocessing, post-processing, and verification tasks. The current template is 1841 lines and becoming very brittle. This is an untenable solution for adding the complexities associated with advanced data assimilation cycling strategies. 

The current template does not support critical functionality needed for the following workflow capabilities:
- Realtime runs, including switching Rocoto to real-time mode, timing out tasks, waiting on data to be available, and setting reservations.
- Full control over defining difference between cycles, including a mechanism to set multiple named cycledefs. This is needed for transitioning between cold start and cycled experiments, defining a partial cycling strategy, and in controlling how long a forecast runs at a given cycle, among others. 
- Extensibility for SRW users to add their own additional tasks at will -- not necessarily included in the SRW authoritative repository. Groups like to perform additional wgrib2 commands, or specific archiving for their real time runs, for example.
- Extensibility for users to define their own task dependencies.

## Solution
A Python tool that transforms YAML configuration files to Rocoto XML files from scratch, without the use of a template. The tool should be able to do the following:
- Generate a Rocoto XML from scratch, without the use of a template.
- Map YAML key/value pairs to Rocoto tags and values.
- Run as a standalone script, much like the existing fill_jinja_template.py script.
- Rely on a pre-defined set of tasks to build up a full workflow.
- Allow a user to override any setting in the YAML configuration of a workflow.

## Requirements**

The tool will need to:
- Fit in with the existing SRW configuration layer.
- Use the Python built-in libraries for XML handling. 
- Be well-documented
- Interact with the SRW scripts through a strict user interface.

## Acceptance Criteria (Definition of Done)

A complete solution will be capable of:
- Duplicating the current behavior of the configuration to generate XML files.
- Allow arbitrary workflows to be created for the components included in the user's defined worklow. For example -- only generate static files, only run verification, only run a cold start forecast. 
- Passes all existing tests.

**Comment by christinaholtNOAA** [comment]
Opened PR #505 to address the use of globals in setup.py, which is useful for using dictionaries to define the XML.

**Comment by christinaholtNOAA** [comment]
Added AQM workflow definitions. Getting closer to an actual PR. Gave a demo to Mike Kavulich, and should probably plan a couple of additional ones -- ask the Thursday group when/who.

**Comment by christinaholtNOAA** [comment]
Schedule a demo for this Thursday. Recording with GoToWebinar. 
Needs to be prioritized for moving forward with other PRs.

**Comment by mkavulich** [comment]
Resolved by #676
