### ISSUE TITLE
Date for external real-time data is not changed when time-offset is not zero on wcoss2

### ISSUE THREAD

**Issue by chan-hoo** [ufs-community/ufs-srweather-app#474]
## Expected behavior
When 'date'='20221111', 'time-offset'='06', and 'cyc'='00' in real-time runs, the date and cyc for the external real-time data should be "20221110" and "18".

## Current behavior
In the log file (`get_extrn_ics`):
+ input_file_path='compath.py para/gfs/v16.2/gfs.20221111/18/atmos'

## Machines affected
- WCOSS2 

## Steps To Reproduce
In the we2e test `nco_grid_RRFS_CONUS_25km_ics_FV3GFS_lbcs_FV3GFS_timeoffset_suite_GFS_v16`,
1. Replace dates with `2022111100`
3. See the log file for `get_extrn_ics`.

**Comment by MichaelLueken** [comment]
Completed by #475.
