### ISSUE TITLE
Start ensemble members from global ensemble members

### ISSUE THREAD

**Issue by christinaholtNOAA** [ufs-community/ufs-srweather-app#485]
## Description
The SRW App supports running a forecast ensemble whose perturbations are stochastically driven through several physical means. There needs to be a mechanism for perturbing initial and boundary conditions, as well. 

RRFS development has achieved this by using GEFS and GDAS ensemble members for initial and lateral boundary conditions. Those external models have been included for use with the retrieve_data.py tool. The workflow needs to be modified to collect the requested global ensemble members, prepare them as initial or boundary conditions using the make_ics and make_lbcs tasks, and have the forecast use those.

## Solution
- Modify the configuration layer to accept GEFS and GDAS as ICS/LBCS.
- Modify get_external_* task to get the requested members
- Modify the XML to run make_ics and make_lbcs on each global ensemble member.
- Modify the forecast tasks to ensure it uses the appropriate ICS/LBCS from the respective ensemble member.

## Requirements**
- Don't break existing capabilities to run with ICS/LBCS of a deterministic external model.
- Map the external global ensemble to the same SRW ensemble member. For example, RRFS member 1 corresponds to GEFS member 1, etc. 
- Grib files from GEFS come with both a & b files. They must be concatenated when they are retrieved. This should not be done as part of retreive_data.py as it's outside the scope of the tool, and should be included in the ex-script for the task.

## Acceptance Criteria (Definition of Done)
- ICS can be any of GDAS (netcdf atm+sfc files), GEFS (grib a & b), or any existing options
- LBCS can be any of GDAS (netcdf atm files), GEFS (merged grib a & b), or any existing options.
- GEFS a & b grib files are merged, if used.

**Comment by christinaholtNOAA** [comment]
GEFS data in data_locations.yml has lists, and it wasn't working appropriately for tests in writing the summary file.

Where should the ICs go?
 - In community mode, it goes in separate sub directory of COMINext for each member. 
 - For NCO mode, all files from all members go directly into COMINext.

Need to modify the file that tracks which model input was downloaded (get_external_ics task makes this file) to ensure it doesn't overwrite any others.

All ensemble members are downloaded in one job. Check how RRFS_dev1 handles sourcing the extrn_mdl_var_defns and gets the right name for the member.

Make subdirectories for mem01, mem02, ... at the make_ics/lbcs stage. Currently does this at the forecast stage since develop uses the same model input for every ensemble member.


Edit: COMext -> COMINext.

**Comment by christinaholtNOAA** [comment]
Data is downloaded for a test case for GDAS. Working on the make_* stage.

Some questions came up:
- Intervals and offsets. We typically use the 6 hour old global run for ICS/LBCS. For SRW mods, just use test cases that start at 0, 6, 12, 18 Z. Use 6 hour offsets. To run SRW at 12 Z, use a 6 hour forecast from 6 Z GEFS/GFS for ICS. LBCS would be 6, 12, 18, 24 forecast files for an 18 hour forecast. 
- No HPSS access. These data will likely have read access, so just asking for HPSS access to your corresponding portfolios will likely suffice for global gridded data. Restricted data will need additional clearance, so could take a longer. 
- GDAS only has surface files on AWS for netcdf. This [document](https://docs.google.com/document/d/1sSKKZm8fJaoMkLiPz6bfHYbr2uO-h-Rycq4H0JP8v60/edit?usp=sharing) on RRFS ensemble data requirements may be useful. Don't worry about NOMADS.

**Comment by christinaholtNOAA** [comment]
- HPSS access gained last week, and accessed data.
- Running make_lbcs and make_ics with each option -- GEFS and GDAS, as appropriate.
- Add additional logic to ex-script to cat the GEFS a and b grib files
- Now focussing on adding additional functionality to grab multiple global members for multiple RRFS members.

**Comment by christinaholtNOAA** [comment]
@MatthewPyle-NOAA Is it okay to store member ics in subdirectories like mem001, mem002 under COMext? GDAS doesn't have different file names for diff members? How should we handle that?

**Comment by MatthewPyle-NOAA** [comment]
@christinaholtNOAA Doing subdirectories matching how the enkfgdas members are treated makes sense to me.  But if you have a strong preference to rename the files (including the member number) and to keep them in a single directory, that also could work (might depend on how many files / member you'll need).

**Comment by christinaholtNOAA** [comment]
@MatthewPyle-NOAA Thanks for your quick response! Keeping them in sub-directories is consistent with how the community has been handling them. If this is acceptable for NCO standards, we can just keep that. 

How are the grib files delivered on WCOSS? Maybe that drives how we want to set this up?

**Comment by MatthewPyle-NOAA** [comment]
Not sure if this answers your final questions, but they exist on WCOSS disk in this fashion after being generated (example from a recent cycle):

/lfs/h1/ops/prod/com/gfs/v16.3/enkfgdas.20221218/12/atmos/mem001/
.
.
.
/lfs/h1/ops/prod/com/gfs/v16.3/enkfgdas.20221218/12/atmos/mem080/

**Comment by christinaholtNOAA** [comment]
@MatthewPyle-NOAA Thank you! I think that's perfect. It maps nicely to the model of keeping the files under separate subdirectories. 

@EdwardSnyder-NOAA I think that means you can continue with the subdirectory approach.

**Comment by EdwardSnyder-NOAA** [comment]
@christinaholtNOAA - I created a [draft PR](https://github.com/ufs-community/ufs-srweather-app/pull/526) for this issue that meets the Acceptance Criteria. While testing the PR, I had trouble downloading the GEFS dataset. This is because the `retrieve_data.py` was looking for the GEFS files on HPSS when they only exist on AWS. If I remove the HPSS option from the `EXTRN_MDL_DATA_STORES` variable, I am able to download the GEFS files. I don't think it is a big issue but wanted to bring it up since some of the machine files have `hpss` listed as an option for the `EXTRN_MDL_DATA_STORES` variable.

**Comment by christinaholtNOAA** [comment]
GEFS test fails immediately when it looks for the HPSS files -- 

Add a decorator to skip the HPSS test on CI in this file: https://github.com/ufs-community/ufs-srweather-app/blob/develop/ush/test_retrieve_data.py


Need to open an Issue about supporting nemsio files for GDAS ics/lbcs.
