### ISSUE TITLE
Correct version numbers on LaTeX-generated PDF documentation

### ISSUE THREAD

**Issue by gspetro-NOAA** [ufs-community/ufs-srweather-app#512]
## Description
Currently, when users generate documentation locally off of their SRW App clone using the make `latexpdf` command, the PDF lists "Release v1.0" regardless of the actual version--v2.0.0, v2.1.0, or develop. The actual documentation is correct for the branch that the user cloned, but the "release" field in the `conf.py` file does not reflect this. 

## Solution
Update the "release" field in the `conf.py` file.

**Comment by MichaelLueken** [comment]
Completed by #513, #514, and #515
