### ISSUE TITLE
[online-cmaq] Biogenic emissions via GFS

### ISSUE THREAD

**Issue by zmoon** [ufs-community/ufs-srweather-app#518]
## Description

 

As Barry brought up in the AQM meeting last Friday, we have been working on a solution for driving the biogenic emissions routines with GFS data (https://github.com/noaa-oar-arl/NEXUS/pull/22). 

cc: @bbakernoaa @chan-hoo 

## Solution

Perhaps:

1) job to retrieve GFS surface data (e.g. like the job to get external LBCs)
2) pre-NEXUS job to use the new script in https://github.com/noaa-oar-arl/NEXUS/pull/22 to process the GFS files for NEXUS input

## Dependencies (optional)

https://github.com/noaa-oar-arl/NEXUS/pull/22

**Comment by bbakernoaa** [comment]
@chan-hoo
