### ISSUE TITLE
Incorporate all RRFS_dev1 variables and workflow configurations

### ISSUE THREAD

**Issue by danielabdi-noaa** [ufs-community/ufs-srweather-app#538]
## Description

 
A lot of variables and workflow tasks are added in RRFS_dev1 that need to be incorporated back into SRW app. One can not test new j-job and ex-scripts of RRFS_dev1 in SRW app because it does not have all of them. The RRFS_dev1 workflow xml file is one big mess. That coupled with new tasks from the Air-Quality modelling work that @chan-hoo is working on, I see will be a problem. I am not offering a solution for this but @christinaholtNOAA may have a solution for that. Until then, we import all variables and workflow tasks to RRFS_dev1 so that new RRFS_dev1 tasks can be developed and tested in SRW.

## Solution

Incorporate all new variables in `config_defaults.yaml` and all the tasks in `FV3LAM_wflow.xml`. Variables should have some structure f.i. new tasks should have own set of variables under a new section `task_{new_task_name}`. The first priority is to make sure current SRW app tasks work after RRFS_dev1 workflow incorporation. Provide flags to turn on/off flags for new spinup/prod cycle tasks etc. of RRFS_dev1.

Second, add capability to run and generate RRFS workflow for retrospective and realtime runs. Provide a `config.rrfs.yaml` file with RRFS_CONUS_3km domain that will be used for incorporating RRFS_dev1 tasks one by one.

## Requirements**

None

## Acceptance Criteria (Definition of Done)

- Current SRW we2e tests must all pass
- All new variables added in `config_defaults.yaml` and machine specific ones
- All new workflow tasks added to `FV3LAM_wflow.xml`
- Provide a `config.rrfs.yaml` file for development
- RRFS_dev1 workflow generation should be possible in SRW app

**Comment by christinaholtNOAA** [comment]
It seems that we might want to address the variables needed for RRFS tasks one task at a time, where we can. As we add a new task to develop, we can assess what that one needs, and as you suggest, we can add a section to the config files.

**Comment by christinaholtNOAA** [comment]
Take a look at this one after develop is merged with XML YAML.

**Comment by christinaholtNOAA** [comment]
Suspending development of RRFS GSI capabilities.
