### ISSUE TITLE
Bug in create workflow config check for invalid key

### ISSUE THREAD

**Issue by zmoon** [ufs-community/ufs-srweather-app#541]
If [the config check](https://github.com/ufs-community/ufs-srweather-app/blob/23b9852b467b4f3f679b767c4c28a791a862cd32/ush/python_utils/config_parser.py#L466) finds an invalid key, we get `UnboundLocalError: local variable 'key' referenced before assignment`, since `key` is not defined. `EXPT_DEFAULT_CONFIG_FN` is also not defined.

https://github.com/ufs-community/ufs-srweather-app/blob/d1aebf4bddd09d6b2e814a8cb27502f36cee6b6b/ush/setup.py#L81-L91

cc: @drnimbusrain

## Expected behavior

It would be better if the info about the invalid key were included in the error message, instead of as a normal print higher up in the log. (And better if the error message worked properly.)

## Current behavior

<details><summary>Example</summary>

```
> ./generate_FV3LAM_wflow.py

  ========================================================================
  Starting experiment generation...
  ========================================================================

  ========================================================================
  Starting function setup() in "setup.py"...
  ========================================================================
INVALID ENTRY: RESTART_WORKFLOW=True

*********************************************************************
FATAL ERROR:
Experiment generation failed. See the error message(s) printed below.
For more detailed information, check the log file from the workflow
generation script: /scratch2/NAGAPE/arl/Zachary.Moon/git/ufs-srweather-app_arl/ush/log.generate_FV3LAM_wflow
*********************************************************************

Traceback (most recent call last):
  File "/scratch2/NAGAPE/arl/Zachary.Moon/git/ufs-srweather-app_arl/ush/./generate_FV3LAM_wflow.py", line 822, in <module>
    generate_FV3LAM_wflow(USHdir, wflow_logfile)
  File "/scratch2/NAGAPE/arl/Zachary.Moon/git/ufs-srweather-app_arl/ush/./generate_FV3LAM_wflow.py", line 70, in generate_FV3LAM_wflow
    expt_config = setup(ushdir)
  File "/scratch2/NAGAPE/arl/Zachary.Moon/git/ufs-srweather-app_arl/ush/setup.py", line 299, in setup
    expt_config = load_config_for_setup(USHdir, default_config_fp, user_config_fp)
  File "/scratch2/NAGAPE/arl/Zachary.Moon/git/ufs-srweather-app_arl/ush/setup.py", line 87, in load_config_for_setup
    User-specified variable "{key}" in {user_config} is not valid
UnboundLocalError: local variable 'key' referenced before assignment
```
</details>

## Machines affected

I assume all, but tested on Hera.

## Steps To Reproduce

Run generate workflow with a `config.yaml` that has a key that isn't in the default config file.

**Comment by mkavulich** [comment]
@zmoon Thank you for taking the time to open this issue. I have opened a PR for a fix here: https://github.com/ufs-community/ufs-srweather-app/pull/559
