### ISSUE TITLE
Add soil temp/moisture adjustment (postanal) --> update_bc

### ISSUE THREAD

**Issue by christinaholtNOAA** [ufs-community/ufs-srweather-app#546]
The rrfs_dev1 script is [here](https://github.com/NOAA-GSL/regional_workflow/blob/feature/RRFS_dev1/scripts/exregional_run_postanal.sh). 

The script identifies the appropriate background files from the model/DA, creates a namelist, and runs adjust_soiltq.exe.

It also updates the boundary condition files by copying them, setting up a namelist, and running update_bc.exe.

Note from comments below: change name to update_bc.

**Comment by BenjaminBlake-NOAA** [comment]
In the operational RAP/HRRR, this task (which runs after the analysis and before the forecast) is referred to as updatebc.  I think we should consider changing the name of this task from postanalysis (which makes me think we are running the UPP in some way) to updatebc.

**Comment by hu5970** [comment]
This task does two functions: soil adjustment and updateBC. It is for running small functions (1 node) after analysis but before the model forecast.  The updatebc is not a good name for this one.

**Comment by christinaholtNOAA** [comment]
Suspending development of RRFS GSI capabilities.
