### ISSUE TITLE
Update GSI hash

### ISSUE THREAD

**Issue by danielabdi-noaa** [ufs-community/ufs-srweather-app#548]
## Description

GSI has been updated to use `ncdiag` from hpc-stack instead of shipping it with the repository.
SRW should load `ncdiag/1.0.0` in `srw_common` and make sure GSI builds correctly with it.
I have encountered some errors while triying to upgrade GSI hash because it is needed for RRFS_dev1 merge work.
If someone familiar with GSI can take a look at this, it would be very helpful!

## Solution

Update GSI hash to latest and make sure SRW builds GSI properly.

## Requirements**

None

## Acceptance Criteria (Definition of Done)

GSI hash is updated and it builds correctly.

**Comment by MichaelLueken** [comment]
@danielabdi-noaa Just a few questions:

1. Are you wanting to update the GSI using NOAA-EMC/GSI or NOAA-GSL/GSI?
2. Are you encountering the failure in the GSI or the EnKF?

Adding ncdiag/1.0.0 to srw_common.lua, I was able to build the GSI, but the EnKF is failing with the following message:

`error #6405: The same named entity from different modules and/or program units cannot be referenced.   [MPI_COMM_WORLD]`

Cloning NOAA-EMC/GSI, I was able to get the GSI and EnKF to build without issue.  However, when updating the compiler from Intel 18 (what the GSI is currently using) to Intel 2022.1.2, the FV3REG build of the EnKF failed with the exact same error.  This will likely require an update to the GSI itself to correct this behavior.

**Comment by MichaelLueken** [comment]
@danielabdi-noaa Using the fix that @hu5970 made in the NOAA-GSL/GSI/rrfs_dev branch at [9b6bf7b](https://github.com/NOAA-GSL/GSI/commit/9b6bf7baa6c94db797089688f4a1524c15c824d5), I was able to get the GSI to build using Intel 2022.1.2.  I should also note that the GSI will likely not run using the Intel 2022.1.2 compiler.  Please see Issue [#447](https://github.com/NOAA-EMC/GSI/issues/447) for more details.

@hu5970 Would it be possible to add this fix to the authoritative NOAA-EMC/GSI repository?

**Comment by dshawul** [comment]
@MichaelLueken Thanks a lot!  I was encountering that same issue but thought I had made a mistake somewhere. I think latest EMC/GSL branch will work with RRFS_dev since they are almost in sync, but just to be safe we can set it to GSL's current hash. The current hash of GSI we have in SRW app has some issues with RRFS_dev workflow.

**Comment by christinaholtNOAA** [comment]
I don't think that we want to use forks of authoritative repos in any case (for authoritative SRW). Changes really must be in the appropriate authoritative repositories/branches for all of this to work smoothly.
