### ISSUE TITLE
generate_FV3LAM_workflow.py no longer deals with relative paths correctly for "EXPT_BASEDIR"

### ISSUE THREAD

**Issue by mkavulich** [ufs-community/ufs-srweather-app#555]
With commit bf075422ed (#505), the default behavior of generate_FV3LAM_wflow.py has changed. This has not been reflected in the documentation, so it either needs to be fixed or the documentation updated to remove references to this functionality.

## Expected behavior
EXPT_BASEDIR is nominally "The base directory in which the experiment directory will be created." Previously, if EXPT_BASEDIR is set to a "relative" path (functionally, this means the first character is not `/`), then the *actual* value would be treated as the default value (`${HOMEdir}/../expt_dirs`) concatenated with the provided path. 

For example, if `EXPT_BASEDIR = /absolute/dir` in the config file, then the experiment will be created with `EXPT_BASEDIR = /absolute/dir`. However, if  `EXPT_BASEDIR = relative/dir` in the config file, then the experiment will be created with `EXPT_BASEDIR = ${HOMEdir}/../expt_dirs/relative/dir`.

## Current behavior
In the current develop branch (after commit bf075422ed), this concatenation no longer occurs, so whatever value is included in EXPT_BASEDIR will be the actual location of the experiments, including relative paths which will simply be treated as-is.

## Machines affected
All

## Steps To Reproduce
See above.

## Detailed Description of Fix (optional)
Unsure. I tried a few different things but none achieved the behavior I was looking for. 

If there is no simple fix we could just consider removing the documentation for this feature and treating EXPT_BASEDIR as literal no matter what. Users could hack in the previous behavior if they really want it.

**Comment by ShawnCebulaNOAA** [comment]
Thank you Michael, I've let the EPIC team know and they'll look into what needs to be done!

Shawn Cebula, EPIC End User Support
