### ISSUE TITLE
Install pygraf libraries in epic modules

### ISSUE THREAD

**Issue by danielabdi-noaa** [ufs-community/ufs-srweather-app#561]
## Description

 
The plotting scripts from `RRFS_dev1` use `pygraf` module. It looks like the current plotting modulefile we have for `plot_allvars` task are not sufficient for pygraf plotting. The first missing library I encountered is `xarrays` but here is the list of libraries 
```
name: pygraf
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7*
  - basemap=1.2*
  - basemap-data-hires=1.2*
  - pynio=1.5.5
  - matplotlib=3.2*
  - metpy=0.12.1
  - pylint=2.4*
  - pytest=6.1*
  - pyyaml=5.3*
  - xarray=0.15*
```

## Solution

Install dependencies required for pygraf plotting on all systems

## Requirements**

The miniconda environment should include libraries required for pygraf plotting

## Acceptance Criteria (Definition of Done)

`pygraf` libraries installed on all level 1 systems

**Comment by gspetro-NOAA** [comment]
In PR [#336](https://github.com/NOAA-EMC/rrfs-workflow/pull/336) in the rrfs-workflow repository, pygraf and all graphics-related tasks were fully removed from the RRFSv1 workflow. Since pygraf is no longer used in RRFSv1, we don't need to worry about porting related functionality to the SRW App.
