### ISSUE TITLE
Pipe crontab entries for e2e tests to /dev/null

### ISSUE THREAD

**Issue by mark-a-potts** [ufs-community/ufs-srweather-app#564]
## Description
 crontab entries for the e2e tests can overwhelm people with email updates. Piping output to /dev/null would eliminate this problem

## Solution
Add ">& /dev/null " to the crontab line

**Comment by mkavulich** [comment]
@mark-a-potts Is this an issue with the workflow or user settings? From my understanding crontab should only send emails if you have set `MAILTO=` in your crontab, so I'm not sure if piping to /dev/null would stop the sending of emails if this setting is active. Currently the crontab entries should be piping all output to a log file (`log.launch_FV3LAM_wflow`), so there should be no terminal output anyway.

**Comment by mkavulich** [comment]
@mark-a-potts Just pinging RE: the above comment, is this still a valid issue or can it be closed?

**Comment by mark-a-potts** [comment]
It can be closed (which I will do). thanks!
