### ISSUE TITLE
Enable running of verification tasks from staged forecast output

### ISSUE THREAD

**Issue by gsketefian** [ufs-community/ufs-srweather-app#565]
## Description
A common anticipated use of the SRW App is to run verification (both deterministic and ensemble) on staged forecast output generated by previous runs of the App.  This capability needs to be added to the App.

## Solution
Add one or more experiment configuration variables that enable this functionality (e.g. a variable that specifies the location of the staged forecast files) and modify scripts as needed to use these variables.

## Requirements
Forecast files must be staged on the various platforms on which the SRW App is tested/run.

## Acceptance Criteria
A WE2E test is added that can run verification (both deterministic and ensemble) on staged forecast output.

## Dependencies
This issue is a prerequisite for resolving Issue #422.

**Comment by mkavulich** [comment]
Resolved via #809
