### ISSUE TITLE
Master inconsistent with regional_workflow/develop

### ISSUE THREAD

**Issue by christinaholtNOAA** [ufs-community/ufs-srweather-app#57]
With the update of regional_workflow with [#PR 357,](https://github.com/NOAA-EMC/regional_workflow/pull/357) the master branch of SRWeather App no longer works. It appears that PR #45 merged to master would fix the problem of sourcing the README txt file. It is not clear to me if there are other inconsistencies between master here and develop in regional_workflow.

**Comment by JeffBeck-NOAA** [comment]
The problem occurs when sourcing the README files, since those in the develop branch still contain system commands related to the build.  @mkavulich, would you be willing to open a PR for your "update_documentation" branch into the develop branch of ufs-srweatherapp?

**Comment by christinaholtNOAA** [comment]
This was closed in error per direct communication with @mkavulich
