### ISSUE TITLE
user.MACHINE var. not properly set when running e2e tests w/ run_WE2E_tests.sh

### ISSUE THREAD

**Issue by ulmononian** [ufs-community/ufs-srweather-app#570]
## Expected behavior
When running end-to-end tests with tests/WE2E/run_WE2E_tests.sh from the command line via

`./run_WE2E_tests.sh tests_file="<file>" machine="<machine>" account="<account>"`

the "machine" arg. entry should populate in the "user" section of ush/config.yaml and experiments should successfully generate.

## Current behavior
Experiment generation fails (on Orion, using srw-dev) because user.MACHINE is not defined, although it is included as an arg. to the un_WE2E_tests.sh. Running `./run_WE2E_tests.sh tests_file="expts_file.txt" machine="orion" account="marine-cpu"` from the command line produces the following error:

`Traceback (most recent call last):
  File "/work2/noaa/epic-ps/cbook/ue/ufs-srweather-app/ush/generate_FV3LAM_wflow.py", line 774, in <module>
    generate_FV3LAM_wflow(USHdir, wflow_logfile)
  File "/work2/noaa/epic-ps/cbook/ue/ufs-srweather-app/ush/generate_FV3LAM_wflow.py", line 70, in generate_FV3LAM_wflow
    expt_config = setup(ushdir)
  File "/work2/noaa/epic-ps/cbook/ue/ufs-srweather-app/ush/setup.py", line 307, in setup
    expt_config = load_config_for_setup(USHdir, default_config_fp, user_config_fp)
  File "/work2/noaa/epic-ps/cbook/ue/ufs-srweather-app/ush/setup.py", line 97, in load_config_for_setup
    raise Exception(
Exception: Mandatory variable "user.MACHINE" not found in
            user config file /work2/noaa/epic-ps/cbook/ue/ufs-srweather-app/ush/config.yaml`

The test "grid_RRFS_CONUS_25km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v16" was used in this example, but the same error is produced despite the test choice.

Hard-coding 'MACHINE: orion' into ush/config.yaml does not bypass the issue, as this field seems to be overwritten & cleared out by `setup.py` when called from `run_WE2E_tests.sh`

## Machines affected
Only tested on Orion, built w/ Intel-2022.0.2 & intel-oneapi-mpi/2021.5.1 from the develop branch (cloned yesterday).

## Steps To Reproduce

1. Clone & build the app
2. Try to run end-to-end test with run_WE2E_test.sh (e.g., grid_RRFS_CONUS_25km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v16)

## Output (optional)

![Screen Shot 2023-02-01 at 9 17 05 AM](https://user-images.githubusercontent.com/43379611/216141420-5b3be6aa-638c-491f-8047-5774e4e91aaf.png)

**Comment by mkavulich** [comment]
@ulmononian I was not able to replicate this error with the latest `develop` branch on Orion. Can you confirm that you have the correct python environment loaded when you run the `run_WE2E_tests.sh` script? 
```
cd path-to-ufs-srweather-app/
module use modulefiles
module load wflow_orion
conda activate regional_workflow
```

If the error persists, can you copy the `run_WE2E_tests.sh` script from this location (`/home/mkavulic/kavulich/UFS/test_develop/ufs-srweather-app/tests/WE2E`) and send the full output from the script? Thanks.

**Comment by mkavulich** [comment]
Also, @ulmononian have you tried on any other platform? I'm curious if it's specific to Orion.

**Comment by ulmononian** [comment]
@mkavulich thanks for taking a look here. i started a fresh session on orion and this time, coincidentally looked at my .bashrc. turns out i had a var exported there, "export MACHINE=orion.intel" from when i was working w/ JCSDA soca-science and got tired of defining that manually. i completely forgot it was in there as i haven't hard orion access in awhile. i cleared that var. definition and re-ran `./run_WE2E_tests.sh tests_file="expts_file.txt" machine="orion" account="marine-cpu"`, this time with success. 

i assume clearing that variable did the trick, though i am surprised it was not overwritten by ./run_WE2E_tests.sh / setup.py to begin with. 

either way, once i start another orion session w/ MACHINE left defined from my .bashrc, i will confirm if that was the cause and close this issue out, chalking it up to classical user error.

**Comment by ulmononian** [comment]
@mkavulich this issue can be closed as it was an anomalous user-error on my side. thanks again for checking on this. not sure if i am to close it or if @MichaelLueken needs to?

**Comment by MichaelLueken** [comment]
@ulmononian I will go ahead and close this issue.
