### ISSUE TITLE
Testing the SRW w/ spack-stack Unified Environment

### ISSUE THREAD

**Issue by ulmononian** [ufs-community/ufs-srweather-app#572]
## Description
While the transition from hpc-stack to spack-stack on the weather model side is ongoing (e.g.:  [UFS-WM #1448](https://github.com/ufs-community/ufs-weather-model/issues/1448), [Acorn spack testing](https://github.com/NOAA-EMC/hpc-stack/wiki/Spack-stack-installations-to-replace-hpc-stack-functionsl), a new spack-based Unified Environment (UE) has been installed by @climbfuji on Orion to help facilitate the switch. This environment contains a "unified" set of compiler+MPI, libraries/packages, and modules to support the UFS-WM and various related apps (e.g., global-workflow, SRW, JCSDA Skylab, and GSI). The UE installation is here on Orion: /work2/noaa/da/dheinzel/spack-stack/spack-stack-unified-env/envs/unified-dev/install and can be loaded via:

`module use /work2/noaa/da/dheinzel/spack-stack/spack-stack-unified-env/envs/unified-dev/install/modulefiles/Core`

`module av`

Testing of the UE is underway on Orion with the UFS-WM, SRW, and Skylab, and pending further successful results, the environment will be installed on other R&D machines (Hera, Cheyenne, Jet, etc.) for further testing and validation.

The SRW has been built using the UE on Orion (w/ Intel compiler/MPI) and can be found here: /work2/noaa/epic-ps/cbook/ue/ufs-srweather-app (temporary). The test set from ufs-srweather-app/tests/WE2E/machine_suites/fundamental is currently in progress here: /work2/noaa/epic-ps/cbook/ue/ufs-srweather-app/expt_dir/ue_tests.  Regression testing and cross-comparison between the UFS-WM built/run with the hpc-stack and spack-stack UE is ongoing.

If any SRW developers/users would like to test the SRW using the UE, a feature branch that has updated build_orion_intel/srw_common_spack module files has been created here: [feature/test_spack_ue](https://github.com/ulmononian/ufs-srweather-app/tree/feature/test_spack_ue).

This issue is ultimately just to open discussion surrounding the move to spack-stack and to identify issues that may arise in the transition.

**Comment by climbfuji** [comment]
Thanks @ulmononian . One thing I would like to note, we should check if moving to spack-stack solves the long-standing problem of using different environments for building and running. I am positive that this is the case, but someone who understands the problem a lot better should check.

**Comment by ulmononian** [comment]
Update:  with #570 resolved, the test set from ufs-srweather-app/tests/WE2E/machine_suites/fundamental is currently in progress here: /work2/noaa/epic-ps/cbook/ue/ufs-srweather-app/expt_dir/ue_tests.

**Comment by ulmononian** [comment]
fundamental tests completed successfully on orion w/ @climbfuji's UE (see screenshot):

<img width="857" alt="screen_shot_2023-02-02_at_8 57 21_pm" src="https://user-images.githubusercontent.com/43379611/216672298-55eb9d0a-880c-4aee-87a4-f7d396263ca2.png">

**Comment by gspetro-NOAA** [comment]
@ulmononian @climbfuji Is this issue still relevant, or can it be closed?

**Comment by climbfuji** [comment]
I defer to @ulmononian

**Comment by mkavulich** [comment]
From my understanding this issue was to track the transition to using spack-stack instead of hpc-stack. Since that was achieved successfully more than a year ago, I assume this issue is resolved.

**Comment by ulmononian** [comment]
@gspetro-NOAA this can definitely be closed. sorry about that!
