### ISSUE TITLE
Error in opening the compiled module file.  Check INCLUDE paths.   [CONSTANTSR4_MOD]

### ISSUE THREAD

**Issue by Schuch666** [ufs-community/ufs-srweather-app#575]
Hi

I have instaled the Online-CMAQ in Cheyenne, however a modeule of the constants (constantsR4_mod) was missing durring the installation process. In order to install I change in multiple parts of the code to aways use constants_mod instead of choose between constantsR4_mod/constants_mod.

My question is, there is a problem in this approach? and there is a way to install whichout modify multiple source files?

Thank you,
Daniel

**Comment by ShawnCebulaNOAA** [comment]
Good morning Daniel, hope all is well!

Just posting here to let you know we're taking a look into this for you and we'll get back to you soon with an answer!

Shawn Cebula, EPIC End User Support

**Comment by Schuch666** [comment]
This steps are not needed to build the current version of the code
Thank you
