### ISSUE TITLE
RRFS make ics/lbcs

### ISSUE THREAD

**Issue by christinaholtNOAA** [ufs-community/ufs-srweather-app#576]
Add make ics/lbcs jobs and tasks in the workflow. One gotcha related to current implementation:

- How to handle the vertical level file. Should be configurable. Put that file in /parm

Acceptance Criteria:
-- All RRFS config options have been implemented.
-- No SRW behavior has changed.
-- Ensure that we are not writing to COMIN when we should not be.

**Comment by christinaholtNOAA** [comment]
Need to sort out issues of running 64 levels (default), and 65 levels. Eddie to add this capability to the FIXgsi ticket [here](https://github.com/ufs-community/ufs-srweather-app/issues/672).

**Comment by MichaelLueken** [comment]
Completed with PR #813.  Closing issue.
