### ISSUE TITLE
Which physics suite need be supported?

### ISSUE THREAD

**Issue by christinaholtNOAA** [ufs-community/ufs-srweather-app#577]
It currently looks like FV3_HRRR and FV3_RAP are in RRFS. Do we need both?

Group instinct says maybe only FV3_HRRR is needed.

**Comment by christinaholtNOAA** [comment]
A multi-physics ensemble option will require the support of additional suites. But it probably won't be FV3_RAP.

There may be a need to support suites not defined as "official" suites.

**Comment by MatthewPyle-NOAA** [comment]
It sounds like the multi-physics ensemble will have very RRFS-centric names like RRFSmem?? (where ?? is the two digit member number).  Not yet in UFS weather, but should be soonish.  

And not 100% sure, but I'm thinking FV3_RAP may be used in the 13 km testing that sometimes is done to test RRFS workflow items in a computationally cheaper way.

**Comment by christinaholtNOAA** [comment]
FV3_HRRR and FV3_RAP at NOAA GSL.
Jili is testing many combinations for each multiphysics ensemble member. 
Other suites will be added with new experimental configurations.

**Comment by christinaholtNOAA** [comment]
Focusing on FV3_HRRR and FV3_RAP for now.
