### ISSUE TITLE
Start a guide for consistent terminology.

### ISSUE THREAD

**Issue by christinaholtNOAA** [ufs-community/ufs-srweather-app#578]
Make sure that when we refer to specific fields/tasks, the variable naming conventions are consistent. This will help with understanding. 

For example, analyses fields are either spelled out as analysis or the abbreviation ANL is used. Partial cycle is pcyc? Does something else make sense.

Reach out to Gillian for where it should live.

**Comment by BenjaminBlake-NOAA** [comment]
I believe the consistency of naming conventions can be partially addressed through a future PR for issue #633 where we plan to update the task names.
@chan-hoo has already proposed names for the existing SRW app tasks.  I will review those, and look over the existing RRFS tasks and propose names for those.

**Comment by christinaholtNOAA** [comment]
Ben has a Google Doc, and can update Issue #633 with additional suggestions to gather additional feedback.

**Comment by christinaholtNOAA** [comment]
Everything is transferred from the Google Doc. Ben to follow up with the Issue to try to get additional feedback. Perhaps bring it up in the Friday meeting.
