### ISSUE TITLE
How should we handle optional real-time tasks?

### ISSUE THREAD

**Issue by christinaholtNOAA** [ufs-community/ufs-srweather-app#579]
Post processing and archiving tasks are often optional and only relevant for real-time runs. How will those get introduced in the real time run? Will the scripts need to live in SRW develop?

Examples:
- pygraf
- bufr sounding profiles
- archiving to HPSS
- cleaning disk

**Comment by christinaholtNOAA** [comment]
Convert to discussion.

**Comment by MatthewPyle-NOAA** [comment]
We discussed this issue a bit at the 20230427 RRFS ops workflow meeting.  I'd say the overall consensus was for the SRW app to contain everything needed for all use cases.  Users could then have a script to clean out unwanted items if desired.  For example, we'll need to do something like this for ops to eliminate the various verification jobs within the ARW app that won't be used in operational instances like the AQM or RRFS.

**Comment by christinaholtNOAA** [comment]
Suspending development of RRFS GSI capabilities.
