### ISSUE TITLE
Add product generation job.

### ISSUE THREAD

**Issue by BenjaminBlake-NOAA** [ufs-community/ufs-srweather-app#580]
The script for this one is [here](https://github.com/NOAA-GSL/regional_workflow/blob/feature/RRFS_dev1/scripts/exregional_run_prdgen.sh) in RRFS_dev1.

This task uses wgrib2 to generate various subdomain RRFS grib2 files from the raw-UPP generated grib2 output from the run_post task.  It will be needed for the real-time operational RRFS runs.  

The rrfs_prdgen_subpiece.sh script is called using CFP to parallelize the job and speed up the overall runtime.  The current version of the script resides in $PRDGENdir (ush/prdgen) but we may want to consider re-locating it.

**Comment by BenjaminBlake-NOAA** [comment]
@danielabdi-noaa  I am going to create a feature branch for this issue later today and will attempt to incorporate all of the changes you've already made in your feature/process_bufr branch.  I'll let you know if I have any questions or issues - thanks for all the work you've done so far!

**Comment by MatthewPyle-NOAA** [comment]
Ben reported that he hopes to open a PR for this change this week.

**Comment by christinaholtNOAA** [comment]
Tests on WCOSS last week. Some unrelated issues with the workflow tests are causing hangups. Hopefully PR by Wednesday.

**Comment by BenjaminBlake-NOAA** [comment]
A PR for this issue has just been submitted [here](https://github.com/ufs-community/ufs-srweather-app/pull/631), will wait on feedback from others.

**Comment by christinaholtNOAA** [comment]
Iterating through PR. 

Does this job need to run sub-hourly? It will be sub-hourly eventually. Initial PR will be for just hourly.
Jillian has provided feedback around documentation. Can include in this PR.
Should wrap up changes tomorrow.
