### ISSUE TITLE
Documentation for setting up an AMI

### ISSUE THREAD

**Issue by jwolff-ncar** [ufs-community/ufs-srweather-app#59]
Current AMI documentation
 - https://github.com/NOAA-EMC/NCEPLIBS-external/blob/release/public-v2/doc/README_redhat_gnu.txt
 - https://github.com/NOAA-EMC/NCEPLIBS-external/blob/release/public-v2/doc/README_ubuntu_gnu.txt

These include instructions on building the weather model stand-alone and not the SRW app. Is that the final intention @climbfuji or is there more work to be done here? There is a note in there that says "for the latter, the model is built by the workflow" but that is not true for the SRW app so that should probably be removed.

**Comment by climbfuji** [comment]
> Current AMI documentation
> 
> * https://github.com/NOAA-EMC/NCEPLIBS-external/blob/release/public-v2/doc/README_redhat_gnu.txt
> * https://github.com/NOAA-EMC/NCEPLIBS-external/blob/release/public-v2/doc/README_ubuntu_gnu.txt
> 
> These include instructions on building the weather model stand-alone and not the SRW app. Is that the final intention @climbfuji or is there more work to be done here? There is a note in there that says "for the latter, the model is built by the workflow" but that is not true for the SRW app so that should probably be removed.

These instructions are final (well, more or less). It is not the intention to describe how to build the model when running the App, just how to build the model standalone. This was the case for MRW 1.0 and 1.1, too.

The sentence "for the latter, the model is built by the workflow" is in all `README_*.txt` files. If that is not true, we need to change that in all of these.
