### ISSUE TITLE
Add save restart job

### ISSUE THREAD

**Issue by BenjaminBlake-NOAA** [ufs-community/ufs-srweather-app#591]
The script for this one is [here](https://github.com/NOAA-GSL/regional_workflow/blob/feature/RRFS_dev1/scripts/exregional_save_restart.sh) in RRFS_dev1.

This task saves the model restart files to nwges.  Upstream dependencies of this task are the forecast jobs which produce restart files.

**Comment by christinaholtNOAA** [comment]
Suspending development of RRFS GSI capabilities.
