### ISSUE TITLE
Can the output names of the forecast job be consolidated to match NCO-expected?

### ISSUE THREAD

**Issue by christinaholtNOAA** [ufs-community/ufs-srweather-app#594]
Currently there are two different naming conventions for the grib output files:

-- PRSLEV and NATLEV in develop vs bgdawp and bgrd3d in RRFS.

**Comment by christinaholtNOAA** [comment]
Moving to the PRSLEV and NATLEV could be one direction since bgdawp and bgrd3d are conventions that are a bit outdated....let's get rid of them!!

It's not clear that PRSLEV and NATLEV  will be the chosen names in the end, but could be a nice place to settle currently.

**Comment by MatthewPyle-NOAA** [comment]
This was discussed at the 20230427 RRFS ops workflow meeting.  Is an eagerness to eliminate the bgdawp and bgrd3d names (a NAM relic!)  Everybody seemed good with the prslev and natlev naming convention.
