### ISSUE TITLE
Stage forecast data from the SRW App on Hera for running vx WE2E tests without running a forecast

### ISSUE THREAD

**Issue by gsketefian** [ufs-community/ufs-srweather-app#597]
## Description

 
On Hera, post-processed output files from the SRW App need to be staged in order to run the WE2E test `MET_verification_only_vx`.  This test uses staged forecast files (in grib2 format) along with staged obs to run deterministic verification.

The necessary observation files are already in the "authoritative" (is that the right adjective?) directory that stages data for testing the `develop` branch, which is at:
```
/scratch2/BMC/det/UFS_SRW_App/develop
```
The observations are in the subdirectory `obs_data`, but there are no staged **forecast** data from the SRW App.  (Note that there is staged external model data in the subdirectory `input_model_data`, but that data is from **external** models (FV3GFS, GSMGFS, RAP, HRRR, and NAM), not from the SRW App itself.)

## Solution

Currently, the staged files are in the personal directory
```
/scratch2/BMC/det/Gerard.Ketefian/UFS_CAM/DTC_ensemble_task/staged/fcst_det/2019061500/postprd
```
(Note that for now, the only date that's needed is `2019061500`.)  I propose to create a subdirectory under `/scratch2/BMC/det/UFS_SRW_App/develop` named `SRW_App_data` in which to place any output needed from the SRW App.  Under there, create the subdirectory `fcst_det` to contain deterministic forecast output from the SRW App (later, another subdirectory at this level named `fcst_ens` will be needed to hold staged ensemble output from the SRW).  To match the same naming convention as from an actual forecast with the SRW, the grib2 files will be placed in the subdirectory `2019061500/postprd` under `fcst_det`. 
 So the full path to the staged files will be:
```
/scratch2/BMC/det/UFS_SRW_App/develop/SRW_App_data/fcst_det/2019061500/postprd
```
Once this or a similar directory structure is agreed on in this issue, the test configuration file `config.MET_verification_only_vx.yaml` will have to be modified to point to the new staging location and a new PR opened to make this change.

In addition, it might be helpful to rename the subdirectory `input_model_data` that contains external model data to something like `extrn_model_data` so that it is clear that it contains only external model data, not data from the SRW itself.

## Requirements**

The WE2E test `MET_verification_only_vx` needs to succeed using the new staging locations.

## Acceptance Criteria (Definition of Done)

The WE2E test `MET_verification_only_vx` needs to succeed using the new staging locations.

## Alternative Solutions (optional)

Other layouts for the SRW staging directory are possible.  Please propose alternatives below.

**Comment by gsketefian** [comment]
@MichaelLueken @mkavulich Please let me know if you have thoughts on this issue that's related to PR #565.  Thanks.

**Comment by MichaelLueken** [comment]
@gsketefian -
Your reasoning on the naming nomenclature makes sense to me.  So long as @mkavulich is on-board with this location as well, please go ahead and move forward with creating `/scratch2/BMC/det/UFS_SRW_App/develop/SRW_App_data/fcst_det/2019061500/postprd`
and moving the staged data currently in 
`/scratch2/BMC/det/Gerard.Ketefian/UFS_CAM/DTC_ensemble_task/staged/fcst_det/2019061500/postprd`
into the newly created authoritative directory.

**Comment by mkavulich** [comment]
The idea looks good to me, but I'm not a huge fan of the proposed naming scheme. Right now we have `input_model_data` and `obs_data` directories, so I would prefer something like `output_data` or `static_output_data` in the `/scratch2/BMC/det/UFS_SRW_App/develop/` directory to keep the same theme going. Under that we could have `fcst_det` and `fcst_ens`. We should also have directories for grids: If we had test data for the same date but different grids that would be a conflict. So for that initial case, it would be under `/scratch2/BMC/det/UFS_SRW_App/develop/SRW_App_data/output_data/fcst_det/[PREDEFINED_GRID_NAME]/2019061500/postprd`

I'd also suggest including the `var_defns.sh` file in that directory so we can always know which settings were used to create that data.

**Comment by gsketefian** [comment]
@mkavulich Good point about the grid name and including `var_defns.sh`.  The rest of it sounds good too.  I think I have permission to make the directories, so I'll go ahead.  Thanks.

**Comment by gsketefian** [comment]
@mkavulich @MichaelLueken I'm wondering if it's worth also including `config.yaml`.  I will for now, we can remove it if we think it's unnecessary.

**Comment by mkavulich** [comment]
Theoretically all that information should be contained in var_defns.sh, but it couldn't hurt to include config.yaml as well
