### ISSUE TITLE
Containers for the SRW application release

### ISSUE THREAD

**Issue by jwolff-ncar** [ufs-community/ufs-srweather-app#60]
@climbfuji  @SamuelTrahanNOAA What is the status of this work? Is it still targeted for the SRW application release? Is the intent to set up a container to run the stand-alone weather model only (not the app)?

Also, will this be for Docker only or was there further working being done to get this running with Singularity?

I see this information so far:
https://github.com/NOAA-EMC/NCEPLIBS-external/blob/release/public-v2/doc/README_docker_gnu.md

**Comment by climbfuji** [comment]
The container README is the only one that is not yet updated, thanks for reminding me. @SamuelTrahanNOAA was asking for new instructions, but I believe these are simply to install the latest versions of release/public-v2 of NCEPLIBS-external and NCEPLIBS and build the model standalone as a test, but to not include the model source code or build in the container image.
