### ISSUE TITLE
Errors in generate workflow and launch script in Cheyenne

### ISSUE THREAD

**Issue by Schuch666** [ufs-community/ufs-srweather-app#604]
After build the most updated version I received these errors

## Expected behavior
for
 ./config_utils.py -c config.yaml -v config_defaults.yaml
SUCCESS

and for
python3 generate_FV3LAM_wflow.py
Experiment generation completed.  The experiment directory is:
EXPTDIR='/glade/scratch/schuch/RRFS-CMAQ_inline/test2/expt_dirs/test_community'

## Current behavior
 ./config_utils.py -c config.yaml -v config_defaults.yaml
Traceback (most recent call last):
  File "/glade/scratch/schuch/RRFS-CMAQ_inline/test/ufs-srweather-app/ush/./config_utils.py", line 11, in <module>
    from python_utils import cfg_main
  File "/glade/scratch/schuch/RRFS-CMAQ_inline/test/ufs-srweather-app/ush/python_utils/__init__.py", line 31, in <module>
    from .config_parser import (
  File "/glade/scratch/schuch/RRFS-CMAQ_inline/test/ufs-srweather-app/ush/python_utils/config_parser.py", line 38, in <module>
    import jinja2
ModuleNotFoundError: No module named 'jinja2'

python3 generate_FV3LAM_wflow.py
Traceback (most recent call last):
  File "/glade/scratch/schuch/RRFS-CMAQ_inline/test/ufs-srweather-app/ush/generate_FV3LAM_wflow.py", line 12, in <module>
    from python_utils import (
  File "/glade/scratch/schuch/RRFS-CMAQ_inline/test/ufs-srweather-app/ush/python_utils/__init__.py", line 31, in <module>
    from .config_parser import (
  File "/glade/scratch/schuch/RRFS-CMAQ_inline/test/ufs-srweather-app/ush/python_utils/config_parser.py", line 38, in <module>
    import jinja2
ModuleNotFoundError: No module named 'jinja2'`

## Machines affected
Cheyenne

## Steps To Reproduce
In Cheyenne:
git clone -b online-cmaq https://github.com/ufs-community/ufs-srweather-app
cd ufs-srweather-app
cp modulefiles/build_cheyenne_intel.lua modulefiles/build.cheyenne.intel.lua
cp modulefiles/build_cheyenne_intel.lua sorc/UFS_UTILS/modulefiles/build.cheyenne.intel.lua
cp modulefiles/build_cheyenne_intel.lua sorc/AQM-utils/parm/nexus_modulefiles/cheyenne.intel.lua
cp modulefiles/build_cheyenne_intel.lua sorc/AQM-utils/modulefiles/build_cheyenne.intel.lua
remove the version from load pio/2.5.7 and parallelio/2.5.2 from line 7 of modulefiles/srw_common.lua
remove the version of fms in line 9 from modulefiles/srw_common.lua
./devbuild.sh -p=cheyenne -a=ATMAQ
cd ush/
module use ../modulefiles
module load wflow_cheyenne
conda activate regional_workflow
./config_utils.py -c config.yaml -v config_defaults.yaml
python3 generate_FV3LAM_wflow.py

## Detailed Description of Fix and a NEW error on next step
My solution was to create a new conda environment in my $HOME cloning the original regional_workflow environment

module use ../modulefiles
module load wflow_cheyenne
conda activate regional_workflow
conda env export > regional_workflow.yml

nano regional_workflow.yml                        # changing the prefix to my $HOME
conda env create -f regional_workflow.yml  # creating the same env in my $HOME

Using my regional_workflow environment (skiping 'module use ../modulefiles' and 'module load wflow_cheyenne' in a different login) I was able to ran the python script generate_FV3LAM_wflow.py and the experiment directory is generated.

However, running the submission script "./launch_FV3LAM_wflow.sh" I'm geting a new error:

./launch_FV3LAM_wflow.sh
Modules based on Lua: Version 8.7.13  2022-09-14 12:56 -05:00
    by --

Currently Loaded Modules:
  1) ncarenv/1.3   2) rocoto/1.3.3   3) miniconda3/4.12.0   4) wflow_cheyenne

/glade/scratch/schuch/RRFS-CMAQ_inline/test/ufs-srweather-app/ush/bash_utils/filesys_cmds_vrfy.sh: line 68: BASH_SOURCE[2]: unbound variable

The end-to-end run of the workflow for the forecast experiment specified
by expt_name has completed with the following workflow status (wflow_status):
  expt_name = "test_community"
  wflow_status = "FAILURE"

I'm not sure if this error is related to the conda environment or another part of the code

**Comment by mkavulich** [comment]
@Schuch666 I was unable to build the code using the procedures you mentioned. The CMake step failed with the following message:

```CMake Error at CMakeLists.txt:124 (find_package):
  Could not find a configuration file for package "FMS" that is compatible
  with requested version "2022.04".

  The following configuration files were considered but not accepted:

    /glade/work/epicufsrt/GMTB/tools/intel/2022.1/hpc-stack-v1.2.0_6eb6/intel-2022.1/mpt-2.25/fms/2022.01/lib/cmake/fms/fms-config.cmake, version: 2022.1.0
```

Setting the fms version explicitly to `fms/2022.01` did not help either, it gave me the same CMake error. So I believe there is some sort of dependency issue.

All that said, it shouldn't be necessary to build the code to reproduce your problem; so I continued with the procedure you outlined above. I did not observe the errors that you describe, instead the environment was loaded successfully:

```
$ cd ush/
$ module use ../modulefiles
$ module load wflow_cheyenne
Please do the following to activate conda:
       > conda activate regional_workflow
$ conda activate regional_workflow
$ cp config.community.yaml config.yaml
$ ./config_utils.py -c config.yaml -v config_defaults.yaml
SUCCESS
```

Can you be specific about what happens when you attempt to load the conda environment as usual? Do you receive any error messages?

Check that there are no module loads in your `~/.bashrc` or `~/.profile` files, as this can cause unexpected module behavior.

**Comment by Schuch666** [comment]
Hi @mkavulich 

I did a few new tests using the copy the the conda environment and the usual environment and the error related to jinja2 is not present:

```
# conda environments:
#
base                     /glade/u/home/schuch/miniconda3
regional_workflow     *  /glade/u/home/schuch/miniconda3/envs/regional_workflow
rspatial                 /glade/u/home/schuch/miniconda3/envs/rspatial
```

and 

```
# conda environments:
#
                         /glade/u/home/schuch/miniconda3
                         /glade/u/home/schuch/miniconda3/envs/regional_workflow
                         /glade/u/home/schuch/miniconda3/envs/rspatial
base                     /glade/work/epicufsrt/contrib/miniconda3/4.12.0
regional_workflow     *  /glade/work/epicufsrt/contrib/miniconda3/4.12.0/envs/regional_workflow

```

But the last error related to the script "./launch_FV3LAM_wflow.sh" remains the same (they should be not related to the jinja2 error in previous steps).

for:
$ ./launch_FV3LAM_wflow.sh
my output remains the same

```
Modules based on Lua: Version 8.7.13  2022-09-14 12:56 -05:00
    by --

Currently Loaded Modules:
  1) ncarenv/1.3   2) rocoto/1.3.3   3) miniconda3/4.12.0   4) wflow_cheyenne

/glade/scratch/schuch/RRFS-CMAQ_inline/test2/ufs-srweather-app/ush/bash_utils/filesys_cmds_vrfy.sh: line 68: BASH_SOURCE[2]: unbound variable

The end-to-end run of the workflow for the forecast experiment specified
by expt_name has completed with the following workflow status (wflow_status):
  expt_name = "test_community"
  wflow_status = "FAILURE"
```
The result is the same incluing a `module purge` command, and this error is happening independent of the loaded modules.

**Comment by Schuch666** [comment]
@mkavulich 
PS: to build using in cheyenne there is a additional step: to remove the version of pio and fms in lines 28-29 of modulefiles/build_cheyenne_intel.lua

**Comment by mkavulich** [comment]
@Schuch666 I'm glad you were able to solve the conda environment problem.

The AQM workflow is unfortunately outside of my area of expertise, so I hope someone else can help you with that problem.

**Comment by Schuch666** [comment]
@mkavulich no problem

all suggestion are welcome

**Comment by natalie-perlin** [comment]
@Schuch666 - 
  I've completed the steps to reproduce the errors you were getting on Cheyenne, but all seemed to work with no issues. There was no need to modify `modulefiles/ufs.common` or `build_cheyennne_intel.lua` The workflow was successfully generated.
  
The exact steps I followed:
 
```
git clone -b online-cmaq https://github.com/ufs-community/ufs-srweather-app
cd ufs-srweather-app
cp modulefiles/build_cheyenne_intel.lua modulefiles/build.cheyenne.intel.lua
cp modulefiles/build_cheyenne_intel.lua sorc/UFS_UTILS/modulefiles/build.cheyenne.intel.lua
cp modulefiles/build_cheyenne_intel.lua sorc/AQM-utils/parm/nexus_modulefiles/cheyenne.intel.lua
cp modulefiles/build_cheyenne_intel.lua sorc/AQM-utils/modulefiles/build_cheyenne.intel.lua
./devbuild.sh -p=cheyenne -a=ATMAQ
cd ush/
module use /glade/scratch/nperlin/ufs-srweather-app/modulefiles
module load wflow_cheyenne
conda activate regional_workflow
cp config.community.yaml config.yaml
vim config.yaml ## Set MACHINE=cheyenne, set an ACCOUNT variable
./config_utils.py -c config.yaml -v config_defaults.yaml
## verify that you use the python3 from the regional_workflow environment, it needs to be:
## /glade/work/epicufsrt/contrib/miniconda3/4.12.0/envs/regional_workflow/bin/python3
which python3
python3 generate_FV3LAM_wflow.py
```

The result of the workflow generation:


  ```
Experiment generation completed.  The experiment directory is:
    EXPTDIR='/glade/scratch/nperlin/expt_dirs/test_community'
```

**Comment by Schuch666** [comment]
Hi @natalie-perlin , thank you!

It is working until this point, with this message:
```
Experiment generation completed.  The experiment directory is:
EXPTDIR='/glade/scratch/schuch/RRFS-CMAQ_inline/test4/expt_dirs/test_community'

```
however for the next steps:
```
cd /glade/scratch/schuch/RRFS-CMAQ_inline/test4/expt_dirs/test_community
./launch_FV3LAM_wflow.sh
```
are produzing this error:
 ```
$ cat log/make_grid.log
+ /glade/scratch/schuch/RRFS-CMAQ_inline/test4/ufs-srweather-app/ush/load_modules_run_task.sh make_grid /glade/scratch/schuch/RRFS-CMAQ_inline/test4/ufs-srweather-app/jobs/JREGIONAL_MAKE_GRID

Loading modules for task "make_grid" ...

Currently Loaded Modules:
  1) cmake/3.22.0         21) mapl/2.22.0-esmf-8.3.0b09
  2) ncarenv/1.3          22) nemsio/2.5.4
  3) intel/2022.1         23) sfcio/1.4.1
  4) mpt/2.25             24) sigio/2.3.2
  5) mkl/2022.1           25) w3nco/2.4.1
  6) ncarcompilers/0.5.0  26) wrf_io/1.2.0
  7) hpc/1.2.0            27) ncio/1.1.2
  8) hpc-intel/2022.1     28) wgrib2/2.0.8
  9) hpc-mpt/2.25         29) srw_common
 10) jasper/2.0.25        30) g2/3.4.5
 11) zlib/1.2.11          31) esmf/8.3.0b09
 12) bufr/11.7.0          32) hdf5/1.10.8
 13) bacio/2.4.1          33) netcdf/4.7.4
 14) crtm/2.4.0           34) libpng/1.6.37
 15) g2tmpl/1.10.2        35) pio/2.5.7
 16) ip/3.3.3             36) fms/2022.04
 17) sp/2.3.3             37) build_cheyenne_intel
 18) w3emc/2.9.2          38) miniconda3/4.12.0
 19) gftl-shared/v1.5.0   39) miniconda_regional_workflow
 20) yafyaml/v0.5.1       40) make_grid.local

Launching J-job (jjob_fp) for task "make_grid" ...
  jjob_fp = "/glade/scratch/schuch/RRFS-CMAQ_inline/test4/ufs-srweather-app/jobs/JREGIONAL_MAKE_GRID"

Traceback (most recent call last):
  File "/glade/scratch/schuch/RRFS-CMAQ_inline/test4/ufs-srweather-app/ush/config_utils.py", line 11, in <module>

    from python_utils import cfg_main
  File "/glade/scratch/schuch/RRFS-CMAQ_inline/test4/ufs-srweather-app/ush/python_utils/__init__.py", line 31, in <module>
    from .config_parser import (
  File "/glade/scratch/schuch/RRFS-CMAQ_inline/test4/ufs-srweather-app/ush/python_utils/config_parser.py", line 38, in <module>
    import jinja2
ModuleNotFoundError: No module named 'jinja2'

========================================================================
Entering script:  "JREGIONAL_MAKE_GRID"
In directory:     "/glade/scratch/schuch/RRFS-CMAQ_inline/test4/ufs-srweather-app/jobs"

This is the J-job script for the task that generates grid files.
========================================================================
/glade/scratch/schuch/RRFS-CMAQ_inline/test4/ufs-srweather-app/jobs/JREGIONAL_MAKE_GRID: line 155: GRID_DIR: unbound variable
```

and I have found similar errors in log/get_extrn_lbcs_2019061518.log and log/get_extrn_ics_2019061518.log.

Locks like the conda environment used to this job/task are missing the `jinja2 python module`

There is a way to fix this? or to use a different conda environment inside the job/task?

**Comment by Schuch666** [comment]
update: the problem is related to configuration caused by `conda init`, commenting the lines related to `conda init` from my `~/.bashrc` fix the issue

I'm able to run the launch_FV3LAM_wflow.sh

**Comment by natalie-perlin** [comment]
@Schuch666  - That's excellent! Thanks for letting us know.
