### ISSUE TITLE
Suite option not recognized in Cheyenne

### ISSUE THREAD

**Issue by Schuch666** [ufs-community/ufs-srweather-app#621]
I'm trying to reproduce the second simulation of the [UFS dev tutorial](https://ufs-srweather-app.readthedocs.io/en/develop/Tutorial.html#experiment-2-test) in Cheyenne. The initial steps are returning SUCCEEDED state until the TASK make_lbcs. In the beginning of the run_fcst TASK the jobs stops and the error from the `log/run_fcst_2019061518.log` file:

```
An error occurred in ccpp_physics_init
Invalid suite FV3_RRFS_v1beta

FATAL from PE    20: Call to CCPP physics_init step failed
```
it seems that the model is not recognizing this option. I did some tests switching to other suites, and a test with  FV3_RRFS_v1beta and the input data from the [first case](https://ufs-srweather-app.readthedocs.io/en/develop/Tutorial.html#experiment-1-control) (that presented the same error). This return similar errors:

```
An error occurred in ccpp_physics_init
Invalid suite FV3_HRRR
```
and
```
An error occurred in ccpp_physics_init
Invalid suite FV3_WoFS_v0
```
Do you have any suggestions on how to debug this error?

**Comment by MichaelLueken** [comment]
Hi @Schuch666!

Just to check, while building the SRW App, are you using `-a=ATMAQ`?  If you are, then `CPL_AQM` is being set to true, which is causing `sorc/CMakeLists.txt`, line 35, to set the `CCPP_SUITES` as:

`"FV3_GFS_v15p2,FV3_GFS_v16,FV3_GFS_v17_p8"`

If you add `FV3_HRRR`, `FV3_RRFS_v1beta`, and `FV3_WoFS_v0` (or any of the other missing suite options) to line 35 in sorc/CMakeLists.txt, these additional options should be available.

**Comment by Schuch666** [comment]
Hi @MichaelLueken 

Yes, this is my case, the suggestion works!

Thank you for the help
