### ISSUE TITLE
Weather model will not build on Orion with devbuild.sh

### ISSUE THREAD

**Issue by mkavulich** [ufs-community/ufs-srweather-app#623]
## Expected behavior
All UFS SRW App components should build successfully on Orion with the devbuild.sh script

## Current behavior
When building the app with the command `./devbuild.sh -p=orion`, I received the following error from the CMake step of the weather model build:

```
[  6%] Building Fortran object sorc/emcsfc_snow2mdl.fd/CMakeFiles/snow2mdl_lib.dir/model_grid.F90.o
CMake Error at CMakeLists.txt:124 (find_package):
  By not providing "FindFMS.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "FMS", but
  CMake did not find one.

  Could not find a package configuration file provided by "FMS" (requested
  version 2022.04) with any of the following names:

    FMSConfig.cmake
    fms-config.cmake

  Add the installation prefix of "FMS" to CMAKE_PREFIX_PATH or set "FMS_DIR"
  to a directory containing one of the above files.  If "FMS" provides a
  separate development package or SDK, be sure it has been installed.


-- Configuring incomplete, errors occurred!
See also "/work/noaa/gsd-fv3-test/kavulich/UFS/test_develop/ufs-srweather-app/build/sorc/ufs-weather-model/src/ufs-weather-model-build/CMakeFiles/CMakeOutput.log".
make[2]: *** [sorc/ufs-weather-model/src/ufs-weather-model-stamp/ufs-weather-model-configure] Error 1
make[1]: *** [sorc/CMakeFiles/ufs-weather-model.dir/all] Error 2
```

I have not tried any additional debugging due to lack of time, but I am curious if/how the Jenkins tests are successful when I am unable to build the code.

## Machines affected
Orion

## Steps To Reproduce
1. Check out the top of develop on Orion
2. Run `./devbuild.sh -p=orion`, observe above-noted failure

**Comment by MichaelLueken** [comment]
Hi @mkavulich -

Looking through the Jenkins output for Orion on last Friday's (02/17/2022) test of @gsketefian's PR #609, I see the following:

```
-- Found FMS: "/work/noaa/epic-ps/role-epic-ps/hpc-stack/libs/intel-2022.1.2/intel-2022.1.2/impi-2022.1.2/fms/2022.04" (Version: "2022.4.0")
-- FMS targets:
--   - FMS::fms_r4 [Lib: /work/noaa/epic-ps/role-epic-ps/hpc-stack/libs/intel-2022.1.2/intel-2022.1.2/impi-2022.1.2/fms/2022.04/lib/libfms_r4.a]
--   - FMS::fms_r8 [Lib: /work/noaa/epic-ps/role-epic-ps/hpc-stack/libs/intel-2022.1.2/intel-2022.1.2/impi-2022.1.2/fms/2022.04/lib/libfms_r8.a]
```

While I didn't test develop, yesterday, I was able to build @gsketefian's `feature/rename_vx_tasks` branch on Orion without any issues using `devbuild.sh`.  Once Orion comes out of maintenance, I will attempt to test the develop branch to see if I can replicate this error.

**Comment by mkavulich** [comment]
@MichaelLueken Thanks for the response. I didn't include this in my original write-up, but this happened with both an older version of develop (307713fd3) as well as the most up-to-date version, so I doubt this is related to a recent code change. I also noticed this line in my CMake output:

```-- Found ESMF: /work/noaa/epic-ps/role-epic-ps/hpc-stack/libs/intel-2022.1.2/intel-2022.1.2/impi-2022.1.2/esmf/8.3.0b09/lib/libesmf.a (found suitable version "8.3.0", minimum required is "8.3.0") 
[  5%] Linking Fortran static library libnoah_lsm_routines.a
[  6%] Building Fortran object sorc/emcsfc_snow2mdl.fd/CMakeFiles/snow2mdl_lib.dir/model_grid.F90.o
CMake Error at CMakeLists.txt:124 (find_package):
```

Which confuses me even more because that's the same location where my build "couldn't find" FMS.

If you wanted to look at my failing build, it can be found here: `/home/mkavulic/kavulich/UFS/test_develop/ufs-srweather-app`

**Comment by MichaelLueken** [comment]
@mkavulich I tried going to the directory you noted above, but I don't have permission:

```
Orion-login-1[1] mlueken$ cd /home/mkavulic/kavulich/UFS/test_develop/ufs-srweather-app
-bash: cd: /home/mkavulic/kavulich/UFS/test_develop/ufs-srweather-app: Permission denied
```

Having said that, I believe I know what is happening on Orion.  Looking at the `fms` directory, I see the following:

```
drwxr-sr-x+ 5 role-epic-ps epic-ps 4096 Oct  6 23:05 2022.01
drwxr-sr-x+ 5 role-epic-ps epic-ps 4096 Oct  6 17:10 2022.03
drwxr-s---  5 role-epic-ps epic-ps 4096 Feb  2 18:42 2022.04
```

There are no permissions for users outside of the epic-ps group to access the contents of `fms/2022.04`.  Unfortunately, this issue wasn't identified until a user without access to the epic-ps group attempted to build the weather model.  This is also the reason why the weather model builds without issue for me and Jenkins (Jenkins testing uses epic-ps on Orion).

@natalie-perlin Please update the the permissions for:
```
/work/noaa/epic-ps/role-epic-ps/hpc-stack/libs/intel-2022.1.2/intel-2022.1.2/impi-2022.1.2/fms/2022.04
/work/noaa/epic-ps/role-epic-ps/hpc-stack/libs/intel-2022.1.2/intel-2022.1.2/impi-2022.1.2/fms/2022.04/lib
/work/noaa/epic-ps/role-epic-ps/hpc-stack/libs/intel-2022.1.2/intel-2022.1.2/impi-2022.1.2/fms/2022.04/lib/cmake
/work/noaa/epic-ps/role-epic-ps/hpc-stack/libs/intel-2022.1.2/intel-2022.1.2/impi-2022.1.2/fms/2022.04/lib/cmake/fms
```
so that they use `drwxr-sr-x+` rather than `drwxr-s---`.

Thank you very much!

**Comment by natalie-perlin** [comment]
@mkavulich @MichaelLueken - 
Thanks for drawing my attention to this issue! All fixed now:
```
drwxr-sr-x+  5 role-epic-ps epic-ps 4096 Feb  2 18:42 2022.04
drwxr-sr-x+  5 role-epic-ps epic-ps 4096 Oct  6 23:05 2022.01
drwxr-sr-x+  5 role-epic-ps epic-ps 4096 Oct  6 17:10 2022.03
```
The umask is set to 0022, and default access control list is set to have identical permissions for possible next installations:
```
[role-epic-ps@Orion:/work/noaa/epic-ps/role-epic-ps/hpc-stack/libs/intel-2022.1.2/intel-2022.1.2/impi-2022.1.2/fms]# getfacl .
# file: .
# owner: role-epic-ps
# group: epic-ps
# flags: -s-
user::rwx
group::r-x
mask::r-x
other::r-x
default:user::rwx
default:group::r-x
default:other::r-x

```
... and the hpc-stack base directory as well:

```
[role-epic-ps@Orion:/work/noaa/epic-ps/role-epic-ps/hpc-stack]# getfacl .
# file: .
# owner: role-epic-ps
# group: epic-ps
# flags: -s-
user::rwx
group::r-x
mask::r-x
other::r-x
default:user::rwx
default:group::r-x
default:other::r-x

[role-epic-ps@Orion:/work/noaa/epic-ps/role-epic-ps/hpc-stack]# ls -lat
total 16
drwxrwsr-x+ 15 role-epic-ps epic-ps 4096 Feb 10 09:10 ..
drwxr-sr-x+  3 role-epic-ps epic-ps 4096 Nov  9 15:07 libs
drwxr-sr-x+  3 role-epic-ps epic-ps 4096 Oct  6 14:30 src
```

**Comment by MichaelLueken** [comment]
@natalie-perlin Thank you very much for taking care of this so quickly!

@mkavulich Thank you for bringing this to our attention!  Please try building the SRW App using `devbuild.sh` on Orion to make sure that the issue has been corrected.

**Comment by mkavulich** [comment]
@natalie-perlin @MichaelLueken Thanks for getting to the bottom of this. It looks like there might still be some permissions problems; my build now finds FMS, but can't find g2tmpl:

```
CMake Error at FV3/upp/CMakeLists.txt:50 (find_package):
  By not providing "Findg2tmpl.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "g2tmpl", but
  CMake did not find one.

  Could not find a package configuration file provided by "g2tmpl" with any
  of the following names:

    g2tmplConfig.cmake
    g2tmpl-config.cmake

  Add the installation prefix of "g2tmpl" to CMAKE_PREFIX_PATH or set
  "g2tmpl_DIR" to a directory containing one of the above files.  If "g2tmpl"
  provides a separate development package or SDK, be sure it has been
  installed.


-- Configuring incomplete, errors occurred!
```

**Comment by MichaelLueken** [comment]
@mkavulich Yep, `g2tmpl/1.10.2` appears to only have permissions for `epic-ps` as well:

```
drwxr-sr-x+ 5 role-epic-ps epic-ps 4096 Oct  6 16:31 1.10.0
drwxr-s---+ 5 role-epic-ps epic-ps 4096 Feb  2 18:53 1.10.2
```

@natalie-perlin Please update the permissions for:

```
/work/noaa/epic-ps/role-epic-ps/hpc-stack/libs/intel-2022.1.2/intel-2022.1.2/g2tmpl/1.10.2
/work/noaa/epic-ps/role-epic-ps/hpc-stack/libs/intel-2022.1.2/intel-2022.1.2/g2tmpl/1.10.2/lib
/work/noaa/epic-ps/role-epic-ps/hpc-stack/libs/intel-2022.1.2/intel-2022.1.2/g2tmpl/1.10.2/lib/cmake
/work/noaa/epic-ps/role-epic-ps/hpc-stack/libs/intel-2022.1.2/intel-2022.1.2/g2tmpl/1.10.2/lib/cmake/g2tmpl
/work/noaa/epic-ps/role-epic-ps/hpc-stack/libs/intel-2022.1.2/intel-2022.1.2/g2tmpl/1.10.2/share
```

I went ahead and looked at `pio/2.5.7` and `crtm/2.4.0`, which were the other two libraries that have been updated recently, and it looks like their permissions are set as `drwxr-sr-x+`, so once `g2tmpl/1.10.2` has been updated, Orion's HPC-stack should be good to go.

Thanks!

**Comment by natalie-perlin** [comment]
@MichaelLueken - thank you, 
All masks are recalculated, default _and_ current permissions updated recursively from the upstream `/work/noaa/epic-ps/role-epic-ps/hpc-stack/` directory, and now it shows the g2tmpl/ permissions correctly:
```
drwxr-sr-x+  4 role-epic-ps epic-ps 4096 Feb  2 18:53 .
drwxr-sr-x+  5 role-epic-ps epic-ps 4096 Feb  2 18:53 1.10.2
drwxr-sr-x+ 36 role-epic-ps epic-ps 4096 Oct 17 12:49 ..
drwxr-sr-x+  5 role-epic-ps epic-ps 4096 Oct  6 16:31 1.10.0
```

**Comment by MichaelLueken** [comment]
@natalie-perlin Thank you very much for recursively updating permissions from the upstream `/work/noaa/epic-ps/role-epic-ps/hpc-stack` directory!

**Comment by mkavulich** [comment]
Thanks @MichaelLueken and @natalie-perlin, looks like it's working now. I'll close this issue as fixed.
