### ISSUE TITLE
Compare fix/input files for GST on all platforms (cheyenne, hera, jet, orion, gaea)

### ISSUE THREAD

**Issue by fentoad72** [ufs-community/ufs-srweather-app#64]
Check that files are identical and report to group if they are not (or if they are)

**Comment by jwolff-ncar** [comment]
Once these are firmed up, we will need to put a copy on AWS S3 bucket (along with all tier 1 (2?) platforms)

**Comment by jwolff-ncar** [comment]
@fentoad72 You might also take a look at @llpcarson's latest updates for the WM UG documentation (Section 4.1.1) to confirm that we are consistent there as well.
Thank you!

**Comment by fentoad72** [comment]
Here are some initial results.  I used the fix_am directories on cheyenne, hera, jet, and orion, and pulled the fix_nco_gfsv16_20201208.tar from HPSS.  I create a list of files by doing 'ls -1' in each fix_am directory, and wrote a simple Python file that reads in all 5 files, calculates the intersection (550 files) which is files found in all 5 directories and the difference which is the union of all files (563) minus the intersection. There are 13 files that appear in one or more but not all 5.  
1 rrtmgp-data-sw-g224-2018-12-04.nc

2 geo_em.d01.nc_HRRRX

3 syndat_stmnames_q2fy19

4 Thompson_MP_MONTHLY_CLIMO.nc

5 geo_em.d01.nc_HRRR_AK

6 geo_em.d01.nc_RAPX

7 rrtmgp-cloud-optics-coeffs-sw.nc

8 global_hyblev.l150.txt

9 syndat_stmnames_new

10 rrtmgp-cloud-optics-coeffs-lw.nc

11 syndat_stmnames_previous

12 syndat_stmnames_old2

13 rrtmgp-data-lw-g256-2018-12-04.nc


550 files may not be the minimum as there are still copies of certain files (just looking by eye), for example
CFSR.OISST.1982.2010.monthly.clim

CFSR.OISST.1999.2012.monthly.clim.grb

CFSR.SEAICE.1982.2010.monthly.clim

CFSR.SEAICE.1982.2012.monthly.clim.grb

(2 data formats)

fix_co2_proj

fix_co2_update

(2 datasets)

global_kplist.1d.txt

global_kplist.hd.txt

global_kplist.master.txt

(3 datasets)

These may or may not be justified.  At this point, I'm just the messenger.  Also, I didn't do a bitwise comparison, just checked on the filenames.

The file counts:
cheyenne 550
hera 560
HPSS 553
jet 563
orion 553

**Comment by fentoad72** [comment]
Once again, here's the output, and I labeled the fix_20121202.tar as "hpss-dev":
fix_amarbetter@vpn65-177:~/fix_files>python fix_files.py 
hera 560
cheyenne 550
orion 560
jet 563
hpss-dev 560
.fix_am
Intersecting files 550
Union of all files 563
Differing files 13
13
1 Thompson_MP_MONTHLY_CLIMO.nc ['hera', 'orion', 'jet', 'hpss-dev']
2 rrtmgp-data-lw-g256-2018-12-04.nc ['hera', 'orion', 'jet', 'hpss-dev']
3 geo_em.d01.nc_HRRRX ['hera', 'orion', 'jet', 'hpss-dev']
4 rrtmgp-cloud-optics-coeffs-sw.nc ['hera', 'orion', 'jet', 'hpss-dev']
5 geo_em.d01.nc_HRRR_AK ['hera', 'orion', 'jet', 'hpss-dev']
6 rrtmgp-cloud-optics-coeffs-lw.nc ['hera', 'orion', 'jet', 'hpss-dev']
7 geo_em.d01.nc_RAPX ['hera', 'orion', 'jet', 'hpss-dev']
8 syndat_stmnames_q2fy19 ['jet']
9 rrtmgp-data-sw-g224-2018-12-04.nc ['hera', 'orion', 'jet', 'hpss-dev']
10 global_hyblev.l150.txt ['hera', 'orion', 'jet', 'hpss-dev']
11 syndat_stmnames_old2 ['hera', 'orion', 'jet', 'hpss-dev']
12 syndat_stmnames_previous ['jet']
13 syndat_stmnames_new ['jet'] 

HPSS-dev has 560 files, as does orion and hera.  Cheyenne has 550 files and jet has 563 files.  There are 10 files that are on every platform except cheyenne and 3 extra files on jet (syndat_stnames)

fix_orog
hera 20
cheyenne 16
orion 20
jet 20
hpss-dev 20
.fix_orog
Intersecting files 16
Union of all files 20
Differing files 4
4
1 GlobalLakeDepth.txt ['hera', 'orion', 'jet', 'hpss-dev']
2 GlobalLakeStatus.dat ['hera', 'orion', 'jet', 'hpss-dev']
3 GlobalLakeStatus.txt ['hera', 'orion', 'jet', 'hpss-dev']
4 GlobalLakeDepth.dat ['hera', 'orion', 'jet', 'hpss-dev']
All platforms have 20 files except for cheyenne, which is missing the GlobalLake data.

fix_sfc_climo
hera 14
cheyenne 16
orion 14
jet 14
hpss-dev 14
.fix_sfc_climo
Intersecting files 14
Union of all files 16
Differing files 2
2
1 README ['cheyenne']
2 sorc ['cheyenne']

All hosts have 14 files except cheyenne, which has 16, but just a README file and a sorc directory.
The results so far show that orion and hera file listings match HPSS-dev, while jet has a few extra.  Cheyenne's missing files seem very fixable.  Jamie (I think) mentioned a plan going forward to rsync those directories to ensure they're all the same.  There's always going to be someone who wants to tweak the input files.  Status quo seems to be putting them in the fix_ directories.  Another option might be to create a space in the user's ufs-srweather-app filespace where extra files could go.  I'm not sure if the latter is doable or preferable, just throwing it out there.
