### ISSUE TITLE
Add pygraf plotting support

### ISSUE THREAD

**Issue by danielabdi-noaa** [ufs-community/ufs-srweather-app#653]
## Description

 
`RRFS_dev1` branch uses [pygraf](https://github.com/NOAA-GSL/pygraf) for plotting. I think this should be incorporated back into SRW even though it may not be run operationally for two reasons. First, visual verification of results  of SRW against the RRFS_dev1 branch. Second, the plots look more high quality to me than the current SRW `plot_allvars.py` scripts. It also seems to have option to make diff plots so it may replace the `plot_allvars/diff.py` scripts in the future.

## Solution

Add pygraf plotting library support 

## Requirements**

Would need update of required plotting libraries in the EPIC stack. See issue #561 

## Acceptance Criteria (Definition of Done)

Should be able to produce graphics using pygraf library

## Dependencies (optional)

None

## Alternative Solutions (optional)

Keep using `plot_allvars`

**Comment by gspetro-NOAA** [comment]
@christinaholtNOAA @danielabdi-noaa It looks like the PR related to this was closed a while ago. Can the issue be closed?

**Comment by christinaholtNOAA** [comment]
This is no longer a desired feature.
