### ISSUE TITLE
Define shared variables and predefined grids for all tasks

### ISSUE THREAD

**Issue by danielabdi-noaa** [ufs-community/ufs-srweather-app#654]
## Description

 
`RRFS_dev1` tasks share a number of variables and predefined grids, so I believe these should go in before any task specific PR. I don't think it is appropriate to add these common things with a PR meant specifically for a given task. Examples:
  - new NCO directory names `NWGES`, `RRFSE_NWGES`, `ENSCTRL_COMIN`
  - `TAG` variable that is prepended to all task names so that one can identify tasks in multiple workflows
  - Workflow control flags such as `DO_SPINUP`, `DO_DACYCLE` etc 
  - `RRFS_dev1` defines a bunch of new cycles besides `forecast`, `initial` etc,
    
    ```
    AT_START_CYCLEDEF: "00 01 01 01 2100 *"
    INITIAL_CYCLEDEF: "00 01 01 01 2100 *"
    BOUNDARY_CYCLEDEF: "00 01 01 01 2100 *"
    BOUNDARY_LONG_CYCLEDEF: "00 01 01 01 2100 *"
    SPINUP_CYCLEDEF: "00 01 01 01 2100 *"
    PROD_CYCLEDEF: "00 01 01 01 2100 *"
    PRODLONG_CYCLEDEF: "00 01 01 01 2100 *"
    RECENTER_CYCLEDEF: "00 01 01 01 2100 *"
    ARCHIVE_CYCLEDEF: "00 01 01 01 2100 *"
    SAVEINPUT_CYCLEDEF: "00 01 01 01 2100 *"
    ```
 - Add namelists for DA cycle 
 - Maybe also add the workflow and test case? That will make sure the PRs are tested as they are added sequentially.
 
I think this PR is high priority because of this since all other tasks will depend on it. It can also serve as a base to develop the new yaml workflow since the cycles, workflow controls, new directories etc are all required

## Solution

Modify `config_defaults.yaml` and `predef_grid_params.yaml` to include the above variables and new predefined grids respectively.

## Requirements**

None

## Acceptance Criteria (Definition of Done)

Has the common variables for all tasks and new predefined grids.

## Dependencies (optional)

None

**Comment by JeffBeck-NOAA** [comment]
@danielabdi-noaa, can we change the NWGES name so it's more descriptive?  What is the purpose of this directory?

**Comment by MatthewPyle-NOAA** [comment]
@JeffBeck-NOAA The use of NWGES is a bit of a legacy variable name in production.  It is often used to define a directory holding DA-relevant files (such as first guess and analysis files) outside of the main COM output directory.   It could be changed, but not sure if that would negatively impact those in GSL/EMC that deal with the DA aspects of RRFS.

**Comment by JeffBeck-NOAA** [comment]
Thanks @MatthewPyle-NOAA!  Got it.  I suppose if we have sufficient documentation regarding these NCO-based variable/directory names in the SRW App, that would work too.

**Comment by MichaelLueken** [comment]
Since RRFSv1 will not be released using the ufs-srweather-app repository, and the RRFS-related features have been removed from the SRW App repository following the merging of PR #893, I will now close this issue.
