### ISSUE TITLE
parm/input.nml.FV3 need to be updated for the recent GFS physic update

### ISSUE THREAD

**Issue by ytangnoaa** [ufs-community/ufs-srweather-app#661]
Recently updated https://github.com/NOAA-EMC/fv3atm/blob/develop/ccpp/data/GFS_typedefs.F90
changed the namelist variables for "&gfs_physics_nml". Some variables, such as "nsradar_reset",
are not longer accepted. However, in the current workflow,  "parm/input.nml.FV3" still has that item in
the namelist, which caused the run failure. 

@chan-hoo  Could you take a look?

**Comment by chan-hoo** [comment]
@ytangnoaa, sure. do you know which hash of the ufs weather model made this change? or can you let me know how I can reproduce the failure? Should I use a specific CCPP suite?

**Comment by chan-hoo** [comment]
I found it on https://github.com/ufs-community/ufs-weather-model/commit/74ec1da74ee8a4fdf2989f7d43e6c775559ce284.

**Comment by ytangnoaa** [comment]
> I found it on [ufs-community/ufs-weather-model@74ec1da](https://github.com/ufs-community/ufs-weather-model/commit/74ec1da74ee8a4fdf2989f7d43e6c775559ce284).

In fv3atm, this change appeared in https://github.com/NOAA-EMC/fv3atm/commit/8b84603c592150110da68fcdb598ddc1debee181
