### ISSUE TITLE
Determine FIXgsi and predefined grid file locations for RRFS

### ISSUE THREAD

**Issue by EdwardSnyder-NOAA** [ufs-community/ufs-srweather-app#672]
## Description

 
The RRFS configuration of the SRW App uses a `FIXgsi` directory found within the `ufs-srweather-app` folder with some predefined grid files. The current SRW App doesn't have this `FIXgsi` directory and these predefined grid files. To help support the RRFS configuration, we will need to create a `FIXgsi` directory and copy the predefined grid files to each RDHPCs. 

The current SRW App does have a `DOMAIN_PREGEN_BASEDIR` variable that points to `FV3LAM_pregen` folder, which is stagged on each RDHPCs, so perhaps the predefined grid files can go here.

## Solution

Create a common `FIXgsi` directory on each RDHPCs. 
Determine where the predefined grids go (`DOMAIN_PREGEN_BASEDIR` or `FIXgsi`) and copy the files there for each RDHPCs.
Copy any other files we need to run the RRFS configuration to the `FIXgsi` directory.

## Requirements**

None.

## Acceptance Criteria (Definition of Done)

Each platform has a `FIXgsi` directory with the correct files and has the predefined grid files stagged.
The RRFS tasks that uses the `FIXgsi` directory and files can be completed in the develop branch of the SRW App.

**Comment by EdwardSnyder-NOAA** [comment]
Fix files (like FIXgsm, FIXorg, FIXshp, etc.) are now stagged on each platform under `path/to/UFS_SRW_App/develop/fix`. I suggest we place the FIXgsi directory here with the other fix files.

**Comment by EdwardSnyder-NOAA** [comment]
`fix_gsi` directory with the contents of gsi-fix.22.07.27.tar.gz is now on the following RDHPCS platforms: cheyenne, gaea, hera, jet, orion, and NOAA cloud (aws, gcp, azure). This PR #674 adds the FIXgsi to the machine files.

**Comment by EdwardSnyder-NOAA** [comment]
To run the process lightning task on Jet, I had to add the predefined grid RRFS_CONUS_3km folder and the prepobs_prep_RAP.bufrtable file to the fix_gsi directory.

**Comment by christinaholtNOAA** [comment]
There are some fix files in RRFS_dev1 branch. It's going to be a larger scope for understanding what differences exist between what RRFS_dev1 needs and what is staged on platforms.

Predefined grid files are organized differently on prem vs in RRFS_dev1. We need to find out which grids we need to support for RRFS.

**Comment by EdwardSnyder-NOAA** [comment]
Added `prepobs_prep_RAP.bufrtable` file to `fix_gsi` and added `global_hyblev_fcst_rrfsL65.txt` file to the `fix_am` directory on each RDHPCs platform. 

Still need to add these files to odin, stampede, and wcoss2, since I don't have access to those machines. Are we going to support these machines?

**Comment by EdwardSnyder-NOAA** [comment]
We will be supporting these grids for RRFS:
RRFS_NA_3km
RRFS_NA_13km
RRFS_CONUS_3km
RRFS_BayArea_3km

Things to do:
- [ ] RRFS_NA_3km and RRFS_CONUS_3km needs to be copied to all RDHPCs PREGEN locations 
   - [x] Jet
   - [x] Hera
   - [ ] wcoss2
   - [x] Orion
- [ ] Need to figure out how to generate the `fv3_grid_spec` files for RRFS_NA_13km and RRFS_BayArea_3km and copy them to all RDHPCs
- [ ] Make a PR that adds the RRFS_BayArea_3km domain. Use this [PR](https://github.com/ufs-community/regional_workflow/pull/725) as reference

**Comment by EdwardSnyder-NOAA** [comment]
`fv3_grid_spec` files are created in the expt dir under expt_date when the expt completes. Don't worry about the `fv3_grid_spec.####` files. Will address those later.

**Comment by EdwardSnyder-NOAA** [comment]
The `fv3_grid_spec` file for RRFS_NA_13km was created and placed on Jet, Hera, and Orion. A new issue will be created to track the RRFS_BayArea_3km domain PR. 

An additional issue will be created to document the RRFS fix, grid, and obs files needed in the develop branch. A [document](https://docs.google.com/spreadsheets/d/1v-FbZmK91OSSyHFgl1UnwrqlSRjq8qfyh8SbxNbp0aQ/edit?usp=sharing) was generated to track which files have been uploaded and to which platform.

Closing this issue since it has been resolved. Will add additional issues when they come up as needed.
