### ISSUE TITLE
MET_ensemble_verification with `run_envir=nco` stopped working

### ISSUE THREAD

**Issue by danielabdi-noaa** [ufs-community/ufs-srweather-app#677]
## Expected behavior

The test should run correctly with `run_envir=nco` mode. It stopped working with the latest commit #659 
It runs fine in community mode though

## Current behavior

It doesn't run properly
```
$ rocotorun -v 10 -w FV3LAM_wflow.xml -d FV3LAM_wflow.db                                                                                    03/15/23 21:09:10 UTC :: FV3LAM_wflow.xml :: Error: Extra element join in interleave.
03/15/23 21:09:10 UTC :: FV3LAM_wflow.xml :: Error: Element join has extra content: cyclestr at FV3LAM_wflow.xml:837.
03/15/23 21:09:10 UTC :: FV3LAM_wflow.xml :: Error: Element task failed to validate content at FV3LAM_wflow.xml:828.
03/15/23 21:09:10 UTC :: FV3LAM_wflow.xml :: Error: Extra element task in interleave.
03/15/23 21:09:10 UTC :: FV3LAM_wflow.xml :: Error: Element metatask failed to validate content at FV3LAM_wflow.xml:649.
03/15/23 21:09:10 UTC :: FV3LAM_wflow.xml :: Error: Element workflow failed to validate content at FV3LAM_wflow.xml:220.
03/15/23 21:09:10 UTC :: FV3LAM_wflow.xml :: Error: Element workflow failed to validate content at FV3LAM_wflow.xml:220.
```

## Machines affected

All

## Steps To Reproduce

Run the hera intel fundamental test with `MET_ensemble_verification` or directly run the test case with `run_envir=nco`.

**Comment by gsketefian** [comment]
@danielabdi-noaa Do you mind sending me the path (preferably on Hera) to the experiment directory of the `MET_ensemble_verification` WE2E test in nco mode?  I'd like to know what it's supposed to look like so I'll make sure that it still works in my future vx PRs.  Thanks.

**Comment by danielabdi-noaa** [comment]
@gsketefian The directory is here
```
/scratch2/BMC/gsd-hpcs/Daniel.Abdi/expt_dirs/MET_ensemble_verification_old_20230315_212242
```
Enclosing LOGDIR in `<cyclestr></cyclestr>` often gives problems in NCO mode since that also contains date in NCO mode.
Unfortunately my fix, although it did make it start to run the test, did not completely solve the problem as it seems the `MET_ensemble_verification` test failed in `run_MET_PcpCombine_fcst_APCP03h_mem002`

**Edit** There was one more issue, use of hardcoded `.log` extension instead of `LOGEXT` that will work in NCO mode. The latter appends the WORKFLOW_ID to distinguish log file from one another.

**Comment by gsketefian** [comment]
@danielabdi-noaa Ah ok, thanks for the explanation and the path.
