### ISSUE TITLE
Add lightning data paths from disk to machine files.

### ISSUE THREAD

**Issue by EdwardSnyder-NOAA** [ufs-community/ufs-srweather-app#678]
The purpose of this issue is to determine which RDHPCS platforms have stagged lightning obs data and update the corresponding machine files.

**Comment by EdwardSnyder-NOAA** [comment]
Lightning obs data is found on Hera, Jet, and Orion. Hera has two directory one with current data and one archive. Jet and Orion both have archive datasets.
Hera (current): /scratch2/BMC/public/data/lightning
Hera (archive): /scratch2/BMC/zrtrr/rli/data/lightning
Jet: /mnt/lfs4/BMC/wrfruc/Ruifang.Li/data/lightning
Orion: /work/noaa/wrfruc/mhu/rrfs/data/lightning

**Comment by EdwardSnyder-NOAA** [comment]
Added lightning paths to Hera, Jet, and Orion via PR #644. Didn't add the current Hera lightning path. We will need to address how we will switch between retro and non-retro runs as these paths and other variables will change. The dev1 branch has [this script](https://github.com/NOAA-GSL/regional_workflow/blob/feature/RRFS_dev1/ush/set_rrfs_config.sh) that switched between paths.

**Comment by EdwardSnyder-NOAA** [comment]
Daniel's [PR 647](https://github.com/ufs-community/ufs-srweather-app/pull/647/files#diff-07c7b729a743994e24af097288775d509b246ee691b31820b1fd982e002488ff) addresses how to switch between a retro and non-retro run.

**Comment by EdwardSnyder-NOAA** [comment]
Archive paths need to point to files under /path/to/UFS_SRW_data folder on our RDHPCS platforms. Copy only the case data we want. Look to our RRFS.config.yaml for which data we should copy over.

**Comment by christinaholtNOAA** [comment]
@EdwardSnyder-NOAA I'm finding these supported paths on those platforms:

Hera: /scratch2/BMC/public/data/lightning/vaisala/netcdf
Jet: /public/data/lightning/vaisala/netcdf/

I'm not seeing any paths set for WCOSS in RRFS_dev1.

@mkavulich Might also find this helpful with his work on retrieving data.

**Comment by EdwardSnyder-NOAA** [comment]
Awesome, you found the current lightning data on Jet! I was missing that. I'll tag @danielabdi-noaa so he can add that path to the `LIGHTNING_ROOT` in Jet's real time section of his [PR 647](https://github.com/ufs-community/ufs-srweather-app/pull/647/files#diff-07c7b729a743994e24af097288775d509b246ee691b31820b1fd982e002488ff).

**Comment by danielabdi-noaa** [comment]
@EdwardSnyder-NOAA I have Updated the realtime path on Jet. It was not specified in `set_rrfs_config.sh` file for some reason.

**Comment by EdwardSnyder-NOAA** [comment]
Decided to put the lightning data under a new directory called `rrfs_retro_data` since we have more rrfs data to stage. The full path to the lightning data on Jet and Hera are as followed: 
Jet: `/mnt/lfs4/HFIP/hfv3gfs/role.epic/UFS_SRW_data/develop/rrfs_retro_data/lightning/vaisala/netcdf`
Hera: `/scratch1/NCEPDEV/nems/role.epic/UFS_SRW_data/develop/rrfs_retro_data/lightning/vaisala/netcdf`

I put the first 12 hours of lightning data for the July 20th, 2022, case in these directories. This is the case that is listed in the [config.rrfs.yaml](https://github.com/ufs-community/ufs-srweather-app/pull/647/files#diff-b2bb98fb25c20e15f0e06d96f9c5927dc92657db2a655b8e2cdb9fd03690d02f). Down the road we should talk about which cases we would like to include in the config files and for the release.

**Comment by EdwardSnyder-NOAA** [comment]
@danielabdi-noaa - I created these lightning paths on Hera and Jet and staged 12 hours of the config.rrfs.yaml case lightning data there. Could you update the LIGHTNING_ROOT paths for the retro section of the Hera and Jet machine files? Thanks!

**Comment by danielabdi-noaa** [comment]
@EdwardSnyder-NOAA Ok I will updated it. Thanks!

**Comment by EdwardSnyder-NOAA** [comment]
Closing since we have paths on Jet and Hera with enough lightning data to run a short cycle.
