### ISSUE TITLE
New forecast failures for GFS_v16

### ISSUE THREAD

**Issue by christinaholtNOAA** [ufs-community/ufs-srweather-app#693]
## Expected behavior

@mkavulich ran a comprehensive test suite from the develop branch on Hera with a version of SRW from Mar 10, 2023 (af3855ff) experiencing only the expected failures. 

I ran a comprehensive test suite on Hera with my branch updated to the develop valid as of Mar 20 (4018b0053) and saw 3 new forecast failures on several 3km domains using GFS_v16. @mkavulich was able to replicate the failure for the CONUS 3km with a clean develop branch.

His test on Hera: /scratch2/BMC/fv3lam/kavulich/UFS/workdir/test_develop/expt_dirs/e83194ed/grid_RRFS_CONUScompact_3km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v16/

## Current behavior

The following tests fail on the forecast step with the outlined failures

**grid_RRFS_CONUScompact_3km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v16**
 
After 182 iterations:
`compute_qs: saturation vapor pressure table overflow, nbad=      1`

**grid_CONUS_3km_GFDLgrid_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v16**

After 89 iterations
`compute_qs: saturation vapor pressure table overflow, nbad=      1`

**grid_RRFS_CONUS_3km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v16**

After 182 iterations, a seg fault occurred.

## Machines affected

Hera is the only one tested currently.

## Steps To Reproduce

Build SRW and run the comprehensive test suite, or the individual ones listed above.

## Detailed Description of Fix (optional)

For now, reverting changes to k_split and n_split for the GFS_v16 suite seems like the likely culprit.

**Comment by mkavulich** [comment]
The hash that introduced this failure is e83194ed (PR #664). An example of this failure can be found on disk on Hera here: `/scratch2/BMC/fv3lam/kavulich/UFS/workdir/test_develop/expt_dirs/e83194ed/grid_RRFS_CONUScompact_3km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v16/`

For reference, here is the same test on Hera for the previous hash (6ce0363c) succeeding: `/scratch2/BMC/fv3lam/kavulich/UFS/workdir/test_develop/expt_dirs/6ce0363c/grid_RRFS_CONUScompact_3km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v16/`
