### ISSUE TITLE
Use cmake build for EMC_post

### ISSUE THREAD

**Issue by mkavulich** [ufs-community/ufs-srweather-app#7]
- [x] Point to EMC_post hash that builds with cmake
 - [x] Test building and running
 - [x] Merge EMC_post cmake build to develop
 - [ ] Change srweather-app to point to hash in EMC_post on develop with final merged changes

**Comment by jwolff-ncar** [comment]
@mkavulich Should this be handled in issue #5 or should this remain separate?
