### ISSUE TITLE
Jinja templating for config file formats

### ISSUE THREAD

**Issue by danielabdi-noaa** [ufs-community/ufs-srweather-app#700]
## Description

 
Currently config files support jinja templating using `extend_yaml` function that fills values of templated jinja2 entries refering to variables in the same config file. However, support for jinja templating of a block of yaml entries is not supported. This may come in handy, for example, when you want to define a set of variables only if a certain condition is met. With the existing approach, one has to define the variables and set to null/empty even when they are not needed.

## Solution

Add jinja templating to all config file formats: yaml, json, xml, ini, and shell

## Requirements**

None

## Acceptance Criteria (Definition of Done)

Fundamental tests pass

**Comment by gspetro-NOAA** [comment]
@danielabdi-noaa @christinaholtNOAA Since the related PR was closed, can this issue be closed?

**Comment by christinaholtNOAA** [comment]
This will not be included.
