### ISSUE TITLE
Plotting tasks do not run the correct script; plots are not created.

### ISSUE THREAD

**Issue by mkavulich** [ufs-community/ufs-srweather-app#742]
## Expected behavior
Adding a plotting task (from `parm/wflow/plot.yaml`) should run the plotting task.

## Current behavior
`parm/wflow/plot.yaml` has a bug: the incorrect J-job script is called (`JREGIONAL_MAKE_GRID` instead of `JREGIONAL_PLOT_ALLVARS`). This causes the plotting task to simply re-run the make_grid task, rather than creating plots.

## Machines affected
All.

## Steps To Reproduce
Running the WE2E test `grid_RRFS_CONUS_25km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_2017_gfdlmp_regional_plot` is the easiest way to observe this issue. 

## Detailed Description of Fix (optional)
Modify `parm/wflow/plot.yaml` to run the correct task.

Thanks to @BruceKropp-Raytheon for pointing out this problem.

**Comment by BruceKropp-Raytheon** [comment]
I confirm that applying this fix before starting WE2E tests (on Orion, so far) does generate plots as expected:

sed "s|JREGIONAL_MAKE_GRID|JREGIONAL_PLOT_ALLVARS|1" -i parm/wflow/plot.yaml
