### ISSUE TITLE
[production/AQM.v7] Standard Environmental Variables for coming-in models for the UFS-AQM  

### ISSUE THREAD

**Issue by JianpingHuang-NOAA** [ufs-community/ufs-srweather-app#748]
To support AQMv7 implementation, it is required to meet NCO implementation. One of the requirements is to specify coming-in models correctly. 

1) To define environmental variables COMINgfs in ~/ush/job_preamble.sh or J-jobs scripts associated with using operational gfs output files. They include JREGIONAL_NEXUS_GFS_SFC or JREGIONAL_MAKE_ICS or JREGIONAL_MAKE_LBCS, and JREGIONAL_GET_EXTRN_MDL_FILES

2) To define COMINgefs in  J-jobs like JREGIONAL_AQM_LBCS or jobs_preamble.sh.

**Comment by chan-hoo** [comment]
@JianpingHuang-NOAA, you can find the new COMINgfs defined in `job_preamble.sh': https://github.com/ufs-community/ufs-srweather-app/blob/332bd109f6e96a47295c8c4b54f4c1338016f160/ush/job_preamble.sh#L124
