### ISSUE TITLE
[production/AQM.v7] To define DCOMfire by using fire emission RAVE data files to support AQMv7 implementation

### ISSUE THREAD

**Issue by JianpingHuang-NOAA** [ufs-community/ufs-srweather-app#750]
To meet NCO implementation standards, please define DCOMINfire  in the J-job scripts , JREGIONAL_FIRE_EMISSION or job-preamble.sh file.

Meanwhile, please replace "{AQM_FIRE_DIR}" with "DCOMINfire" in the ex-script, exregional_fire_emission.sh

**Comment by chan-hoo** [comment]
@JianpingHuang-NOAA, you can find the new DCOMIN variables in `machine/wcoss2.yaml`: https://github.com/ufs-community/ufs-srweather-app/blob/332bd109f6e96a47295c8c4b54f4c1338016f160/ush/machine/wcoss2.yaml#L45
