### ISSUE TITLE
Introduce test cases from ufs-case-studies platform

### ISSUE THREAD

**Issue by clouden90** [ufs-community/ufs-srweather-app#753]
## Description
Per discussion (#736), The "retrieve_data.py" unit tests now take a very long time to run (more than an hour for a single file on Hera!) due to having to retrieve very large nemsio files over the internet for the [ufs-case-studies cases](https://ufs-case-studies.readthedocs.io/en/develop/2020CAPE.html#). 
EPIC-DTO team has a [deliverable](https://jira.epic.oarcloud.noaa.gov/browse/ECC-317) to include 4 scientifically-validated UFS test cases (must be from ufs-case-studies platform based on the description) into SRW apps.

## Solution
The solution will be thru #776 as @christinaholtNOAA recommended. EPIC-DTO plans to add the following cases to SRW apps:

- [2020 Cold Air Damming](https://ufs-case-studies.readthedocs.io/en/develop/2020CAD.html#model-configuration-and-datasets)
- [2020 July CAPE case](https://ufs-case-studies.readthedocs.io/en/develop/2020CAPE.html#model-configuration-and-datasets)
- [2019 Halloween Storm](https://ufs-case-studies.readthedocs.io/en/develop/2019HaloweenStorm.html#model-configuration-and-datasets)
- [2019 Hurricane Barry](https://ufs-case-studies.readthedocs.io/en/develop/2019Barry.html#model-configuration-and-datasets)

Short summary for IBCS/LBCS/configurations can be found in this [confluence page](https://confluence.epic.oarcloud.noaa.gov/display/DTO/Release+four+scientifically-validated+UFS+test+cases+from+the+UFS+Case+Studies+Platform+thru+SRW+apps).

FYI @EdwardSnyder-NOAA. I noticed RRFS also have plans to add test cases for RRFS release. Please feel free to let me know if there is an overlap. We can coordinate accordingly.

**Comment by christinaholtNOAA** [comment]
The point of these tests is to make sure that we know where these files are and that they work for this type of file. It's not about a specific test case or data. If it runs fast enough on other platforms, we can skip it on Hera.

Alternatively, retrieve_data.py could be modified to just confirm that a file exists and skip pulling it. In that case, we assume that wget would work for a file that exists, but we still check that.

**Comment by clouden90** [comment]
> The point of these tests is to make sure that we know where these files are and that they work for this type of file. It's not about a specific test case or data. If it runs fast enough on other platforms, we can skip it on Hera.
> 
> Alternatively, retrieve_data.py could be modified to just confirm that a file exists and skip pulling it. In that case, we assume that wget would work for a file that exists, but we still check that.

Thanks for the comments, @christinaholtNOAA , and I totally agreed (as I pointed out we could skip these tests on some platforms in the [original PR](https://github.com/ufs-community/ufs-srweather-app/pull/736#issuecomment-1523488857)). If no one else has other opinions, #776 would be a good hotfix for this issue. We then can move forward to add test cases thru WE2E framework. Thanks.

**Comment by MichaelLueken** [comment]
Closed with PR #776.
