### ISSUE TITLE
[production/AQM.v7] AQM forecast build with module that may not be correct

### ISSUE THREAD

**Issue by lgannoaa** [ufs-community/ufs-srweather-app#755]
Currently, the forecast executable load module esmf/8.3.0b09 and mapl/2.23.1-esmf-8.3.0b09
We need to exam if AQM forecast need mapl/2.23.1-esmf-8.3.0b09 to build or it can be avoid.

**Comment by chan-hoo** [comment]
@lgannoaa, it was updated to "8.4.1": https://github.com/ufs-community/ufs-srweather-app/blob/332bd109f6e96a47295c8c4b54f4c1338016f160/versions/run.ver.wcoss2#L22

With v8.4.1, "mapl" is not necessary any more.

**Comment by lgannoaa** [comment]
Good. I will close this issue as it is now resolved.
