### ISSUE TITLE
[production/AQM.v7] Job source code using RUN_ENVIR=nco for incorrect action

### ISSUE THREAD

**Issue by lgannoaa** [ufs-community/ufs-srweather-app#756]
There are many places within the job scripts referenced RUN_ENVIR=nco in if statement for application logic. The RUN_ENVIR=nco should ONLY be used in NCEP NCO implementation environment. It is currently on WCOSS using ECFLOW workflow. Therefore, there should a review and clean up all RUN_ENVIR=nco part where it:
**(1) Implement rocoto workflow specific operations.**
For example, job_preamble.sh has the following assignment that is not working to work with NCO ecflow workflow.
_if [ "${RUN_ENVIR}" = "nco" ] && [ "${DEBUG}" = "TRUE" ]; then
    __EXPTLOG=${EXPTDIR}/log
    mkdir -p ${__EXPTLOG}
    for i in ${LOGDIR}/*.${WORKFLOW_ID}.log; do
        __LOGB=$(basename $i .${WORKFLOW_ID}.log)
        ln -sf $i ${__EXPTLOG}/${__LOGB}.log
    done
fi_ 
**(2) Wired in path/location that does not take workflow level default value.** 
For example job_preamble.sh
_if [ "${RUN_ENVIR}" = "nco" ]; then
    export COMIN="${COMIN_BASEDIR}/${RUN}.${PDY}/${cyc}"
    export COMOUT="${COMOUT_BASEDIR}/${RUN}.${PDY}/${cyc}"_
Should be modified as:
    export COMIN=${COMIN:-"${COMIN_BASEDIR}/${RUN}.${PDY}/${cyc}"}
For example J-Job JREGIONAL_GET_EXTRN_MDL_FILES, 
_if [ "${RUN_ENVIR}" = "nco" ]; then
...
    export EXTRN_MDL_STAGING_DIR="${DATAROOT}/${t_text}.${share_pid}"_
Should be modified as:
    export EXTRN_MDL_STAGING_DIR=${EXTRN_MDL_STAGING_DIR:-"${DATAROOT}/${t_text}.${share_pid}"}
**(3) Direct access to NCO DATAROOT location.** 
For example, exregional_make_ics.sh script assigned extrn_mdl_staging_dir directory directly in NCO DATAROOT location. How can it be sure that none of the NCO production jobs used the same directory name?
**(4) Unauthorized remove ${COMIN}/RESTART.**
In exregional_run_fcst.sh has:
  _if [ "${RUN_ENVIR}" = "nco" ]; then
    if [ -d "${COMIN}/RESTART" ] && [ "$(ls -A ${DATA}/RESTART)" ]; then
      rm -rf "${COMIN}/RESTART"
    fi_
     The ${COMIN}/RESTART from a previous failed fcst job can not be unauthorized remove. The forecast job should write RESTART in COM as soon as it created. For example, GFS used ln -sf so the file created in $DATA/RESTART is available in COM as soon as it gets created. When fcst job failed, the restart job will access and update the RESTART from COM location.

**Comment by chan-hoo** [comment]
@lgannoaa, for 1), the if-statement condition has been changed: https://github.com/ufs-community/ufs-srweather-app/blob/33366db40b53195676b4aeeb9a4a55979837a4fe/ush/job_preamble.sh#L142

**Comment by chan-hoo** [comment]
For 2), you are using the old version. Those parts have been already changed. Please see the latest branch: https://github.com/ufs-community/ufs-srweather-app/blob/611d3a6471533988eb73e2eba101842c460d66da/ush/job_preamble.sh#L120

**Comment by chan-hoo** [comment]
For 4) What does it mean "unauthorized"? I think you don't understand how the current workflow uses the shared ID for the forecast task. Same as GFS, the current workflow creates a soft-link to DATA/RESTART in COM: https://github.com/ufs-community/ufs-srweather-app/blob/611d3a6471533988eb73e2eba101842c460d66da/scripts/exregional_run_fcst.sh#L610
The part you pointed out is the last command of the forecast task. If the first try fails, the part will not run at all: https://github.com/ufs-community/ufs-srweather-app/blob/611d3a6471533988eb73e2eba101842c460d66da/scripts/exregional_run_fcst.sh#L639
Please check their locations in the script carefully:
https://github.com/ufs-community/ufs-srweather-app/blob/611d3a6471533988eb73e2eba101842c460d66da/scripts/exregional_run_fcst.sh#L716
Once the forecast task is completed successfully, the script removes the existing soft-link from COM and copies the original DATA/RESTART directory to COM. As I keep mentioning, the current workflow uses the shared ID for the forecast task. Even if the first try of run_fcst fails, the second try will run in the same shared DATA directory and search for the restart files in DATA/RESTART.

**Comment by chan-hoo** [comment]
For 3) This is incorrect. I guess you are using the old version of the ufs srw app.
