### ISSUE TITLE
[production/AQM.v7] Remove application logic in ex-scripts that required parallel running date to be wired into the configuration file

### ISSUE THREAD

**Issue by lgannoaa** [ufs-community/ufs-srweather-app#758]
Many ex-scripts using application logic that require parallel running date to be wired in the configuration file. This part of application logic is used to get the forecast FHR output (FCST_LEN_HRS) for a cycle. However, there is no need to wired in every running date for the purpose. 
This solution is not going to work with NCO production environment. In the production, AQM should take the PDY and CYC from NCO ECFLOW workflow level. The application logic can be fixed to:
(1) Not require every running date to be wired in the control file -  var_defns
(2) Use environment variable $cyc and FHR output control array $FCST_LEN_CYCL_ALL to figure out the FCST_LEN_HRS.

## Current behavior ##

In parallel configuration file var_defns.sh has two arrays:
FCST_LEN_CYCL_ALL=( "6" "72" "72" "6" ) - Configure number of FCST_LEN_HRS with each cycle 
ALL_CDATES=( "2023042500" "2023042506" "2023042512" "2023042518" ) - Wired in parallel running date from beginning PDY to ending PDY.

In ex-scripts have the following application logic to find out the FCST_LEN_HRS for current running cycle.
if [ "${FCST_LEN_HRS}" = "-1" ]; then
  for i_cdate in "${!ALL_CDATES[@]}"; do
    if [ "${ALL_CDATES[$i_cdate]}" = "${PDY}${cyc}" ]; then
      FCST_LEN_HRS="${FCST_LEN_CYCL_ALL[$i_cdate]}"
      break
    fi
  done
fi

## Issue analysis ##
The current solution outlined above does not work with realtime production run. Realtime production NCO system should not be required to list every CDATE in the ALL_CDATES array. NCO should have freedom to assign any PDY from ECFLOW workflow level in case of production emergency.
The application logic outlined above is not needed. The only purpose is the get FCST_LEN_HRS from consistent array FCST_LEN_CYCL_ALL. That does not need to have CDATE wired in.  

## Machines affected ##
All.

**Purposed solution**
(1) Remove the use of wired ALL_CDATES in control file, use the PDY assigned from workflow level.
(2) Replace the ex-scripts application logic as the following diff output:
 if [ "${FCST_LEN_HRS}" = "-1" ]; then
   for i_cdate in "${!ALL_CDATES[@]}"; do
     if [ "${ALL_CDATES[$i_cdate]}" = "${PDY}${cyc}" ]; then
       FCST_LEN_HRS="${FCST_LEN_CYCL_ALL[$i_cdate]}"
       break
     fi
   done
 fi
---
 case $cyc in
   00 )
     FCST_LEN_idx=0
   ;;
   06 )
     FCST_LEN_idx=1
   ;;
   12 )
     FCST_LEN_idx=2
   ;;
   18 )
     FCST_LEN_idx=3
   ;;
 esac
 FCST_LEN_HRS=${FCST_LEN_CYCL_ALL[$FCST_LEN_idx]}

A tested version of the exregional_nexus_gfs_sfc.sh file that has the application logic fix can be found in:
/lfs/h2/emc/global/noscrub/lin.gan/para/packages/aqm.v7.0.46/scripts> diff exregional_nexus_gfs_sfc.sh-0501-1 exregional_nexus_gfs_sfc.sh
Note: exregional_nexus_gfs_sfc.sh-0501-1 is the original script
          exregional_nexus_gfs_sfc.sh is the new script has the purposed fix in place.

**Comment by chan-hoo** [comment]
@lgannoaa, the `all_cdates` parts you mentioned above have been updated with the recent change in the UFS SRW App: https://github.com/ufs-community/ufs-srweather-app/blob/611d3a6471533988eb73e2eba101842c460d66da/scripts/exregional_aqm_lbcs.sh#L87

- commit: https://github.com/ufs-community/ufs-srweather-app/commit/611d3a6471533988eb73e2eba101842c460d66da
