### ISSUE TITLE
[production/AQM.v7] AQM package merge for both rocoto workflow and ecflow workflow targeted for implementation code delivery

### ISSUE THREAD

**Issue by lgannoaa** [ufs-community/ufs-srweather-app#759]
## Description
A documentation to outline group decision and progress on AQM package merge activity.
There was a meeting on May 2nd; a group decision was made to do a local package merge between:
/lfs/h2/emc/global/noscrub/lin.gan/git/aqm.v7.0.46 - This is the version that ecflow tested with cycled run.
/lfs/h2/emc/physics/noscrub/jianping.huang/nwdev/packages/aqm.v7.0.71 - This is the latest realtime package for rocoto workflow parallel.

The merged package will be used to run AQM realtime parallel (rocoto workflow) and implementation ecflow parallel to ensure reproducibility going forward. Jianping will host the merged package and Lin will link to this same package for parallel run.

**Comment by chan-hoo** [comment]
next step: Issue #797
