### ISSUE TITLE
[production/AQM.v7] concatenate_nexus_post_split.py - unstable output file size

### ISSUE THREAD

**Issue by lgannoaa** [ufs-community/ufs-srweather-app#775]
There is a finding that $HOMEaqm/sorc/arl_nexus/utils/python/concatenate_nexus_post_split.py utility generated corrupted NEXUS_Expt_combined.nc file. This file has normal size around 858MB. However, some tests have shown corrupted size 572MB. 

Job nexus_post_split used concatenate_nexus_post_split.py to create NEXUS_Expt_combined.nc and used by $HOMEaqm/sorc/arl_nexus/utils/python/make_nexus_output_pretty.py within the same job. The make_nexus_output_pretty.py failed with AssertionError without generate output file NEXUS_Expt_pretty.nc. However, nexus_post_split completed without necessary exception handling.

Since the corrupted output and AssertionError was not handled by exception handling. The nexus_post_split completed. The forecast job failed not finding NEXUS_Expt_pretty.nc file. Error:
+ create_symlink_to_file.sh[124]: print_err_msg_exit 'Cannot create symlink to specified target file because the latter does
not exist or is not a file:

Recommend for developer to do stability test on concatenate_nexus_post_split.py utility.
Recommend for developer to patch exception handling in the ex-script of the job nexus_post_split - exregional_nexus_post_split.sh.

## Machines affected
wcoss

## Debug Output Saved in /lfs/h2/emc/global/noscrub/lin.gan/canned/concatenate_nexus_post_split_debug
aqm_nexus_post_split_00.o56988419-BAD (nexus_post_split job log that does should have failed due to bad output file with AssertionError)
NEXUS_Expt_combined.nc-BAD (The corrupted file)
aqm_nexus_post_split_00.o57049044-GOOD (a rerun of the nexus_post_split job log that created the same file with correct file size)
NEXUS_Expt_combined.nc-GOOD (The good output generated from rerun)

**Comment by JianpingHuang-NOAA** [comment]
@chan-hoo  Do you remember when did we merge the updated concatenate_nexus_post_split.py into the workflow?

**Comment by bbakernoaa** [comment]
@JianpingHuang-NOAA I think it had to be around December of last year

**Comment by bbakernoaa** [comment]
I just did a test using the community code with 72 hour forecasts every 6 hourly cycles and didn't see an issue 

path on wcoss here: `/lfs/h2/emc/stmp/barry.baker/aqm_community_aqmna13`

```ls -lh 20230*/INPUT/aqm*NEXUS*
-rw-r--r-- 1 barry.baker emc 4.0G May  4 15:03 2023040100/INPUT/aqm.t00z.NEXUS_Expt.nc
-rw-r--r-- 1 barry.baker emc 4.0G May  4 15:03 2023040106/INPUT/aqm.t06z.NEXUS_Expt.nc
-rw-r--r-- 1 barry.baker emc 4.0G May  4 15:03 2023040112/INPUT/aqm.t12z.NEXUS_Expt.nc
-rw-r--r-- 1 barry.baker emc 4.0G May  4 15:03 2023040118/INPUT/aqm.t18z.NEXUS_Expt.nc
-rw-r--r-- 1 barry.baker emc 4.0G May  4 15:02 2023040200/INPUT/aqm.t00z.NEXUS_Expt.nc
-rw-r--r-- 1 barry.baker emc 4.0G May  4 15:02 2023040206/INPUT/aqm.t06z.NEXUS_Expt.nc
-rw-r--r-- 1 barry.baker emc 4.0G May  4 15:02 2023040212/INPUT/aqm.t12z.NEXUS_Expt.nc
-rw-r--r-- 1 barry.baker emc 4.0G May  4 15:03 2023040218/INPUT/aqm.t18z.NEXUS_Expt.nc
-rw-r--r-- 1 barry.baker emc 4.0G May  4 15:03 2023040300/INPUT/aqm.t00z.NEXUS_Expt.nc
-rw-r--r-- 1 barry.baker emc 4.0G May  4 15:03 2023040306/INPUT/aqm.t06z.NEXUS_Expt.nc
-rw-r--r-- 1 barry.baker emc 4.0G May  4 15:02 2023040312/INPUT/aqm.t12z.NEXUS_Expt.nc
-rw-r--r-- 1 barry.baker emc 4.0G May  4 15:03 2023040318/INPUT/aqm.t18z.NEXUS_Expt.nc
-rw-r--r-- 1 barry.baker emc 4.0G May  4 15:03 2023040400/INPUT/aqm.t00z.NEXUS_Expt.nc
-rw-r--r-- 1 barry.baker emc 4.0G May  4 15:03 2023040406/INPUT/aqm.t06z.NEXUS_Expt.nc
-rw-r--r-- 1 barry.baker emc 4.0G May  4 15:03 2023040412/INPUT/aqm.t12z.NEXUS_Expt.nc
-rw-r--r-- 1 barry.baker emc 4.0G May  4 15:03 2023040418/INPUT/aqm.t18z.NEXUS_Expt.nc
-rw-r--r-- 1 barry.baker emc 4.0G May  4 15:03 2023040500/INPUT/aqm.t00z.NEXUS_Expt.nc
-rw-r--r-- 1 barry.baker emc 4.0G May  4 15:03 2023040506/INPUT/aqm.t06z.NEXUS_Expt.nc
-rw-r--r-- 1 barry.baker emc 4.0G May  4 15:02 2023040512/INPUT/aqm.t12z.NEXUS_Expt.nc
-rw-r--r-- 1 barry.baker emc 4.0G May  4 15:03 2023040518/INPUT/aqm.t18z.NEXUS_Expt.nc
-rw-r--r-- 1 barry.baker emc 4.0G May  4 15:03 2023040600/INPUT/aqm.t00z.NEXUS_Expt.nc
-rw-r--r-- 1 barry.baker emc 4.0G May  4 15:03 2023040606/INPUT/aqm.t06z.NEXUS_Expt.nc
-rw-r--r-- 1 barry.baker emc 4.0G May  4 15:03 2023040612/INPUT/aqm.t12z.NEXUS_Expt.nc
-rw-r--r-- 1 barry.baker emc 4.0G May  4 15:03 2023040618/INPUT/aqm.t18z.NEXUS_Expt.nc
-rw-r--r-- 1 barry.baker emc 4.0G May  4 15:03 2023040700/INPUT/aqm.t00z.NEXUS_Expt.nc
-rw-r--r-- 1 barry.baker emc 4.0G May  4 15:03 2023040706/INPUT/aqm.t06z.NEXUS_Expt.nc
-rw-r--r-- 1 barry.baker emc 4.0G May  4 15:02 2023040712/INPUT/aqm.t12z.NEXUS_Expt.nc
-rw-r--r-- 1 barry.baker emc 4.0G May  4 15:03 2023040718/INPUT/aqm.t18z.NEXUS_Expt.nc
-rw-r--r-- 1 barry.baker emc 4.0G May  4 15:02 2023040800/INPUT/aqm.t00z.NEXUS_Expt.nc
-rw-r--r-- 1 barry.baker emc 4.0G May  4 15:03 2023040806/INPUT/aqm.t06z.NEXUS_Expt.nc
-rw-r--r-- 1 barry.baker emc 4.0G May  4 15:03 2023040812/INPUT/aqm.t12z.NEXUS_Expt.nc
-rw-r--r-- 1 barry.baker emc 4.0G May  4 15:02 2023040818/INPUT/aqm.t18z.NEXUS_Expt.nc
-rw-r--r-- 1 barry.baker emc 4.0G May  4 15:03 2023040900/INPUT/aqm.t00z.NEXUS_Expt.nc
-rw-r--r-- 1 barry.baker emc 4.0G May  4 15:03 2023040906/INPUT/aqm.t06z.NEXUS_Expt.nc
-rw-r--r-- 1 barry.baker emc 4.0G May  4 15:03 2023040912/INPUT/aqm.t12z.NEXUS_Expt.nc
-rw-r--r-- 1 barry.baker emc 4.0G May  4 15:03 2023040918/INPUT/aqm.t18z.NEXUS_Expt.nc
-rw-r--r-- 1 barry.baker emc 4.0G May  4 15:03 2023041000/INPUT/aqm.t00z.NEXUS_Expt.nc
-rw-r--r-- 1 barry.baker emc 4.0G May  4 15:03 2023041006/INPUT/aqm.t06z.NEXUS_Expt.nc
```

**Comment by chan-hoo** [comment]
The error check has already been added to the command line: https://github.com/ufs-community/ufs-srweather-app/blob/cf184119b3791a6bcf94e7415a560aebb741a6cc/scripts/exregional_nexus_post_split.sh#L91

**Comment by JianpingHuang-NOAA** [comment]
Is there any relationship between this issue and the issue #[86 ](https://github.com/NOAA-EMC/AQM/issues/86)with EMC/AQM ?

@lgannoaa  Is this issue resolved? Did you see this happened again recently?

**Comment by lgannoaa** [comment]
This issue has not been tested yet. We need to merge the latest package and test it with both AQM realtime parallel and ecflow.
Please keep it open.

**Comment by JianpingHuang-NOAA** [comment]
Yes, I agree.
