### ISSUE TITLE
Need a workflow for data preproc tasks

### ISSUE THREAD

**Issue by christinaholtNOAA** [ufs-community/ufs-srweather-app#781]
Adds the parm/wflow files to create an XML for running the first three data preprocessinging tasks.

These tasks will follow the naming conventions outlined in PR [#633](https://github.com/ufs-community/ufs-srweather-app/issues/633), and will be blocked by the three PRs for bufr, radar refl, and lightning task getting merged.

**Comment by mkavulich** [comment]
Resoved per RRFS Merge to SRW project board
