### ISSUE TITLE
[production/AQM.v7] Missing two GFS surface input files for the job, JREGIONAL_NEXUS_GFS_SFC at 06z and 12z cycles

### ISSUE THREAD

**Issue by JianpingHuang-NOAA** [ufs-community/ufs-srweather-app#791]
Another issue has arisen for the NEXUS jobs related to biogenic emission calculations when we use the previous GFS surface inputs in the real-time runs. Specifically, we have identified that two files are missing: gfs.t${cyc}z.sfcf075.nc and gfs.t${cyc}z.sfcf078.nc for 06z and 1z cycles.

These files are necessary for the job 'EGIONAL_NEXUS_GFS_SFC' which prepares GFS surface input files for biogenic emission calculations. For example, as of today's 12z cycle, this issue can be observed at the following location:

/lfs/h2/emc/pt"mp/jianping.huang/emc.para/tmp/nexus_emission_02.57654133.cbqs01/GFS_SFC.

After that, we need to modify the JREGIONAL_NEXUS_EMISSION related ex-script, exregional_nexus_emission.sh to include 78 hour gfs surface input data in the GFS_SFC_MEGAN_INPUT.nc

Please see an example at
/lfs/h2/emc/ptmp/jianping.huang/emc.para/tmp/nexus_emission_02.57654133.cbqs01/GFS_SFC_MEGAN_INPUT.nc

@chan-hoo @bbakernoaa @lgannoaa

**Comment by chan-hoo** [comment]
@JianpingHuang-NOAA, Fixed: https://github.com/ufs-community/ufs-srweather-app/commit/cf184119b3791a6bcf94e7415a560aebb741a6cc

**Comment by bbakernoaa** [comment]
@chan-hoo Thanks!

**Comment by JianpingHuang-NOAA** [comment]
@bbakernoaa 

I checked out the updated production/AQM.v7 branch today and tested it for 00z cycle on 20230516. I saw the following time information for the file of /lfs/h2/emc/ptmp/jianping.huang/emc.para/tmp/nexus_emission_04.58117321.cbqs01/GFS_SFC_MEGAN_INPUT.nc  (Cactus)

time: units = "minutes since 2023-05-15 00:00:00.0" ;
data:
 time = 1110, 1170, 1230, 1290, 1350, 1410, **1470, 1530, 1590, 1650, 1710, 1770** ;

This met input file is used to calculate the biogenic emissions for the time period of 00z to 06z on 20230516.

The time information shows "24.5,  25,5,  26.5, 27.5, 28.5,  29.5" hours since 20230515 at 00z.

My question for you, does the NEXUS recognize time information presented above for biogenic emission calculations?

**Comment by bbakernoaa** [comment]
Again yes.  The netCDF attribute for time is in units of `"minutes since 2023-05-15 00:00:00.0"` . This is a requirement for HEMCO which interprets the correct time stamps based on the combination of time values + the units. 

Its actually part of the netCDF COARDS/CF requirements

**Comment by JianpingHuang-NOAA** [comment]
@bbakernoaa  Just want to confirm. Thanks for the further clarification.

**Comment by bbakernoaa** [comment]
please see https://github.com/noaa-oar-arl/NEXUS/pull/33

Ongoing work to address these various issues on the nexus side. It is quite puzzling
