### ISSUE TITLE
Three obsolete  J-job scripts with AQMv7 Production branch

### ISSUE THREAD

**Issue by JianpingHuang-NOAA** [ufs-community/ufs-srweather-app#792]
For operational implementation, the following three J-jobs are not used.  We need to delete them

https://github.com/ufs-community/ufs-srweather-app/blob/production/AQM.v7/jobs/JREGIONAL_MAKE_GRID
https://github.com/ufs-community/ufs-srweather-app/blob/production/AQM.v7/jobs/JREGIONAL_MAKE_OROG
https://github.com/ufs-community/ufs-srweather-app/blob/production/AQM.v7/jobs/JREGIONAL_MAKE_SFC_CLIMO

**Comment by chan-hoo** [comment]
@JianpingHuang-NOAA, those tasks have already been removed from the production branch.
