### ISSUE TITLE
can we remove manage_externals and use git submodules instead?

### ISSUE THREAD

**Issue by edwardhartnett** [ufs-community/ufs-srweather-app#8]
manage_externals is a home-rolled build tool from CESM that reproduces the functionality of git submodules. It does not seem to offer any feature that we need, which git submodules do not already have.

Git is a well-known, well-tested, and well understood tool. It is already well-integrated with all continuous integration tools and systems. (For example, git submodules are just an extra checkbox on the configuration form when setting up Jenkins CI.)

manage_externals is something that no one else in the world has any interest in or use for. It is untested, unknown, and is not nor never will be well integrated with CI or other development tools.

I suggest we remove it from the project and use git submodiles, as is done in ufs-weather-model.

Part of the motivation for manage_externals probably comes from the way our current build systems to a poor job of checking external software, to ensure that all necessary components are present. Furthermore, the sub-components are themselves often badly-managed, without good, versioned releases. We need to address these issues in each project (and we are doing that).

A big hint that manage_externals is not really a good idea comes from the fact that no one else does this, yet many software packages have to manage external dependencies, in many cases more complex ones than we are dealing with here. 

Instead of attempting to invent our own custom solutions, I suggest we use industry-standard practice and the third-party tools, like git and CMake, which we do not have to originate, test, document, or explain, and which are already well-integrated with the modern software engineering toolset.

To support CI, we will almost certainly need to add git submodules anyway. manage_externals is going to become an additional tool, one that we will struggle to maintain in sync with the submodiles, not a replacement for submodules.

**Comment by jedwards4b** [comment]
If the issue is that you need to use git submodules for some portion of the code then you should know that manage_externals supports git submodules within it's subrepositories.  manage_externals was developed specifically to address some of the shortcomings of git submodules and its use is established and accepted within the cime community.  If you have found a specific shortcoming of manage_externals please open an issue in that [repository.](https://github.com/ESMCI/manage_externals)
