### ISSUE TITLE
Staged verification data needs to be copied to platforms beyond Hera

### ISSUE THREAD

**Issue by mkavulich** [ufs-community/ufs-srweather-app#808]
## Description
There are two stand-alone verification tests that use staged data to run verification tasks (`MET_verification_only_vx` and `MET_ensemble_verification_only_vx`)

This data is staged on Hera here: /scratch1/NCEPDEV/nems/role.epic/UFS_SRW_data/develop/output_data/

## Solution
Copy the Hera staged verification data to other stage-one platforms in the appropriate "UFS_SRW_data" locations. Then update the machine files to point to the proper locations, similar to the Hera machine file.

## Requirements**
Stage the verification data on Jet, Orion, Cheyenne, and Gaea, and update the machine files for the new paths.

## Acceptance Criteria (Definition of Done)
Run the `MET_verification_only_vx` and `MET_ensemble_verification_only_vx` tests on each platform to ensure these tests pass on all tier 1 platforms.

**Comment by natalie-perlin** [comment]
Data has been stages in EPIC-controlled space on Hera, Cheyenne, Orion/Hercules, Jet, Gaea.
Still needs porting to WCOSS2 by somebody with the access to the platform. (Does it need to be placed on acorn?)

`Hera:`
/scratch1/NCEPDEV/nems/role.epic/UFS_SRW_data/develop/output_data/fcst_ens/RRFS_CONUS_3km
`Cheyenne:`
/glade/work/epicufsrt/contrib/UFS_SRW_data/develop/output_data/fcst_ens/RRFS_CONUS_3km
`Orion/Hercules:`
/work/noaa/epic-ps/role-epic-ps/UFS_SRW_data/develop/output_data/fcst_ens/RRFS_CONUS_3km
`Jet:`
/mnt/lfs4/HFIP/hfv3gfs/role.epic/UFS_SRW_data/develop/output_data/fcst_ens/RRFS_CONUS_3km
`Gaea:`
/lustre/f2/dev/role.epic/contrib/UFS_SRW_data/develop/output_data/fcst_ens/RRFS_CONUS_3km

**Comment by natalie-perlin** [comment]
Staged observation data added to ./UFS_SRW_data/:

`Hera:`
/scratch1/NCEPDEV/nems/role.epic/UFS_SRW_data/develop/obs_data/ndas/proc/prepbufr.ndas.2021050[4-5]*
/scratch1/NCEPDEV/nems/role.epic/UFS_SRW_data/develop/obs_data/ccpa/proc/2021050[4-5]*
/scratch1/NCEPDEV/nems/role.epic/UFS_SRW_data/develop/obs_data/mrms/proc/2021050[4-5]*
`Cheyenne:`
/glade/work/epicufsrt/contrib/UFS_SRW_data/develop/obs_data/ndas/proc/prepbufr.ndas.2021050[4-5]*
/glade/work/epicufsrt/contrib/UFS_SRW_data/develop/obs_data/ccpa/proc/2021050[4-5]*
/glade/work/epicufsrt/contrib/UFS_SRW_data/develop/obs_data/mrms/proc/2021050[4-5]*
`Orion/Hercules:`
/work/noaa/epic-ps/role-epic-ps/UFS_SRW_data/develop/obs_data/ndas/proc/prepbufr.ndas.2021050[4-5]*
/work/noaa/epic-ps/role-epic-ps/UFS_SRW_data/develop/obs_data/ccpa/proc/2021050[4-5]*
/work/noaa/epic-ps/role-epic-ps/UFS_SRW_data/develop/obs_data/mrms/proc/2021050[4-5]*
`Jet:`
/mnt/lfs4/HFIP/hfv3gfs/role.epic/UFS_SRW_data/develop/obs_data/ndas/proc/prepbufr.ndas.2021050[4-5]*
/mnt/lfs4/HFIP/hfv3gfs/role.epic/UFS_SRW_data/develop/obs_data/ccpa/proc/2021050[4-5]*
/mnt/lfs4/HFIP/hfv3gfs/role.epic/UFS_SRW_data/develop/obs_data/mrms/proc/2021050[4-5]*
`Gaea:`
/lustre/f2/dev/role.epic/contrib/UFS_SRW_data/develop/obs_data/ndas/proc/repbufr.ndas.2021050[4-5]*
/lustre/f2/dev/role.epic/contrib/UFS_SRW_data/develop/obs_data/ccpa/proc/2021050[4-5]*
/lustre/f2/dev/role.epic/contrib/UFS_SRW_data/develop/obs_data/mrms/proc/2021050[4-5]*

**Comment by mkavulich** [comment]
Thanks @natalie-perlin! I just ran a number of tests on Cheyenne and Jet and confirmed the data is staged correctly on those platforms, though the path for staged output data is not yet in the machine files. I'll open a PR to add these locations to the machine files, and that should close out this Issue.
