### ISSUE TITLE
Upgrade MET and METplus to the coordinated METplus version 5.0

### ISSUE THREAD

**Issue by gsketefian** [ufs-community/ufs-srweather-app#834]
## Description

 
To enable inclusion of time-lagged forecast hour in the `.stat` output files that MET/METplus generates, an upgrade to MET/METplus is needed.

## Solution

Upgrade to the [Coordinated METplus Version 5.0](https://dtcenter.org/community-code/metplus/coordinated-metplus-version-5-0).

## Requirements**

Requires upgrades to the software stack on all platforms.

## Acceptance Criteria (Definition of Done)

All the WE2E verification tests pass.  These are:
```
MET_ensemble_verification
MET_ensemble_verification_only_vx
MET_ensemble_verification_only_vx_time_lag
MET_verification
MET_verification_only_vx
```

**Comment by gsketefian** [comment]
@michelleharrold @JeffBeck-NOAA @willmayfield Tagging you to see what you think.

**Comment by JeffBeck-NOAA** [comment]
I will defer to @michelleharrold, but as long as the versions of MET/METplus that are used support our current research-related features (e.g., NMEP/NEP, gen_ens_prod, etc.), then I think this will be OK.

**Comment by michelleharrold** [comment]
I am good with the update to METplus coordinated release v5.0. I know there were some ensemble-stat and gen-ens-prod changes (mostly to METplus config file options) in that release, but since all of the WE2E tests passed without error, we should be good to go. Just a quick question: was there any comparison of the output from v5.0 to the previous version to make sure the output itself was okay (I know the WE2E tests passed, so that's a good first check)?

**Comment by gsketefian** [comment]
@michelleharrold This came up as part of PR #826.  As far as I understand the METplus 5.0 coordinated release is not part of the software stack on any platform, so no tests have been run yet (but I could be wring about that; I'll let @natalie-perlin clarify).  

@natalie-perlin Is it possible to install the METplus 5.0 coordinated release on Hera while also keeping the current MET/METplus versions (i.e. can they be in the software stack simultaneously)?  That way we can test with both versions and make changes to the app as necessary to make sure we get the same results.

**Comment by natalie-perlin** [comment]
@gsketefian @michelleharrold 
MET-11.0.2 and METplus-5.0.2 are successfully installed on Hera with Intel compiler for currently used EPIC-managed stacks:

`/scratch1/NCEPDEV/nems/role.epic/hpc-stack/libs/intel-2022.1.2`
`/scratch1/NCEPDEV/nems/role.epic/hpc-stack/libs/intel-2022.1.2_ncdf492`

 If this is OK to use these versions, I'd go ahead and adapt the SRW PR https://github.com/ufs-community/ufs-srweather-app/pull/826 
 to run the MET verification tests with these updated module versions.

**Comment by MichaelLueken** [comment]
@gsketefian - Since the SRW App is currently using MET-11.1.0 and METplus-5.1.0, has the SRW App been updated to use the coordinated METplus version 5.0?  If so, can this issue be closed?  Thanks!

**Comment by MichaelLueken** [comment]
Closing issue now.  If you feel this issue hasn't been addressed, please feel free to either reopen this issue or open a new issue.
