### ISSUE TITLE
Add support for RRFS pre-operational runs as ICS/LBCS.

### ISSUE THREAD

**Issue by christinaholtNOAA** [ufs-community/ufs-srweather-app#837]
## Description

 

It might be useful to be able to start forecasts from RRFS pre-operational initial and boundary conditions.

**Comment by christinaholtNOAA** [comment]
It seems like this was handled by @natalie-perlin already, no?

**Comment by MichaelLueken** [comment]
Support was added to the SRW App for RRFS_a data via PR #1089, which was merged on 09/12/2024, at hash [26cdad8](https://github.com/ufs-community/ufs-srweather-app/commit/26cdad8e2045612d4c67d201d6870016e8582afd).  Closing issue now.
