### ISSUE TITLE
[production/AQM.v7] AQMv7 real-time run failed with the latest version of  production/AQMv7 branch

### ISSUE THREAD

**Issue by JianpingHuang-NOAA** [ufs-community/ufs-srweather-app#845]
The AQMv7 near real-time (NRT) runs failed with the latest workflow production/AQMv7. The issue was caused by the run_post jobs, which were looking for the dyn files aqm.t${cyc}.dyn.f000.nc  at $COMOUT/aqm.$PDY/$cyc/ during the forecast model is running.  The run_post jobs were supposed to be triggered by the forecast model run is completed and all the dyn and phy files were moved to $COMOUT/aqm.$PDY/$cyc.   However, the current workflow triggers the run_post jobs during the process while the forecast model job is running and those dyn and phy files have not been moved to the $COMOUT.

Please see the workflow local copy and related log files on Cactus
1) workflow: /lfs/h2/emc/physics/noscrub/jianping.huang/nwdev/packages/aqm.v7.0.81/ush

2) workflow log file, 
/lfs/h2/emc/physics/noscrub/jianping.huang/para/c81/2023062606/log.launch_FV3LAM_wflow

3) run_post log file
/lfs/h2/emc/ptmp/jianping.huang/emc.para/output/20230626/run_post_f002_2023062606.id_1687780516.log.0

4) the post run OUTPUT log file
/lfs/h2/emc/ptmp/jianping.huang/emc.para/tmp/run_post_f002.66374195.cbqs01/OUTPUT.131355

Thanks !

**Comment by chan-hoo** [comment]
- In your workflow XML file:
```
        <dependency>
          <or>
            <taskdep task="&TN_RUN_FCST;"/>
            <and>
              <datadep age="05:00">&DYN_DIR;f#fhr#.nc</datadep>
              <datadep age="05:00">&PHY_DIR;f#fhr#.nc</datadep>
            </and>
          </or>
        </dependency>
```

- In the `latest` workflow XML file:
```
        <dependency>
          <or>
            <taskdep task="&TN_RUN_FCST;"/>
          </or>
        </dependency>

```

As shown above, your workflow XML file has another dependency that was removed long time ago. That is the reason why your workflow doesn't work correctly.

As can be seen below, in the workflow XML template file (parm/FV3LAM_wflow.xml), the second dependency should not be included in AQM:
```
        <dependency>          <or>
            <taskdep task="&TN_RUN_FCST;{{ uscore_ensmem_name }}"/>
      {%- if not cpl_aqm %}            <and>
              <datadep age="05:00">&DYN_DIR;f#fhr#.nc</datadep>
              <datadep age="05:00">&PHY_DIR;f#fhr#.nc</datadep>
            </and>
      {%- endif %}
          </or>
        </dependency>
```

This was caused by that you didn't set FCST_LEN_HRS: -1 in `config.yaml`. Is this a real-time run? Why did you set FCST_LEN_HRS: 6? Isn't 72 hr forecast run a requirement for bias-correction?

**Comment by chan-hoo** [comment]
@JianpingHuang-NOAA, I've removed the dependency from other `run_post` cases for AQM in the workflow XML file as: 

https://github.com/ufs-community/ufs-srweather-app/commit/65871809b9ad881aa09b2e177db5ae535d80a487

Please run `git pull` and let me know if you have any problems.
