### ISSUE TITLE
Upgrade ip to 4.1.0

### ISSUE THREAD

**Issue by AlexanderRichert-NOAA** [ufs-community/ufs-srweather-app#858]
## Description / Requirements
With ip 3.3.3 getting dated, the NCEPLIBS team would like ip users to upgrade to the latest version (4.1.0).

## Solution / Acceptance Criteria (Definition of Done)
Set ip version to 4.1.0 in modulefiles/{srw_common.lua,srw_common_spack.lua}

**Comment by laurenfrederick** [comment]
@AlexanderRichert-NOAA Are you planning to put in a PR for this or would you like EPIC help?

**Comment by MichaelLueken** [comment]
@laurenfrederick @AlexanderRichert-NOAA This change will need to be made to the ufs-weather-model before it can be made to the SRW App.  The SRW App's WE2E aren't thorough enough tests to ensure that all components will work with IP/4.1.0.  The ufs-weather-model's regression testing needs to be used.  Once it has been brought into the ufs-weather-model repository, we can open a PR to update IP from 3.3.3 to 4.1.0.
