### ISSUE TITLE
Remove unsupported grids from valid_param_vals.sh

### ISSUE THREAD

**Issue by gsketefian** [ufs-community/ufs-srweather-app#86]

**Comment by JeffBeck-NOAA** [comment]
@gsketefian, can you please move this issue to the regional_workflow repo?  Thanks!

**Comment by JeffBeck-NOAA** [comment]
@gsketefian, is this resolved?  I believe we took care of this just prior to the release, correct?

**Comment by mkavulich** [comment]
This was completed long ago; valid grids are tracked in `valid_param_vals.yaml`
