### ISSUE TITLE
Verification tests `MET_verification_only_vx`, `MET_ensemble_verification_only_vx`, and `MET_ensemble_verification_only_vx_time_lag` fail on most platforms despite data being staged

### ISSUE THREAD

**Issue by mkavulich** [ufs-community/ufs-srweather-app#863]
## Expected behavior
Tests `MET_verification_only_vx`, `MET_ensemble_verification_only_vx`, and `MET_ensemble_verification_only_vx_time_lag` should succeed on platforms where data has been staged.

## Current behavior
Currently these tasks only succeed on Hera. On other platforms, the experiments fail in the "`check_post_output*`" task(s). These platforms need to have the variable  `TEST_VX_FCST_INPUT_BASEDIR` set to point to the staged data

## Machines affected
All except Hera

## Steps To Reproduce
Attempt to run one of the above-mentioned tests on any platform except Hera

## Detailed Description of Fix (optional)
Set `TEST_VX_FCST_INPUT_BASEDIR` appropriately on all platforms

**Comment by natalie-perlin** [comment]
This would be resolved with the [PR-826](https://github.com/ufs-community/ufs-srweather-app/pull/826)
