### ISSUE TITLE
A cron job can only be added if a crontab already exists.

### ISSUE THREAD

**Issue by VanderleiVargas-NOAA** [ufs-community/ufs-srweather-app#876]
## Expected behavior

WE2E tests should add jobs to cron.

## Current behavior

It seems that WE2E tests are only adding jobs to cron when crontab already exists in the system.

## Steps To Reproduce

Remove crontab with 
```crontab -r```
and try to run any WE2E test.

## Detailed Description of Fix

```
if ! crontab -l &> /dev/null ; then
# if crontab does not exist, create a black crontab
    echo "" | crontab -
fi
```

**Comment by mkavulich** [comment]
Thanks for reporting this issue! I was able to replicate it on Hera and will incorporate a fix into my draft test improvements PR #871
