### ISSUE TITLE
SRW App doesn't build on PW NOAA Cloud Platforms

### ISSUE THREAD

**Issue by EdwardSnyder-NOAA** [ufs-community/ufs-srweather-app#881]
## Expected behavior
The SRW App should build on the NOAA Cloud platforms.

## Current behavior
Currently, the SRW App cannot be built on the NOAA Cloud platforms as the [modulefiles](https://github.com/ufs-community/ufs-srweather-app/blob/develop/modulefiles/build_noaacloud_intel.lua) is using an outdated spack-stack.

## Machines affected
PW NOAA Cloud platforms (i.e. Azure, AWS, and GCP)

## Steps To Reproduce
Follow the [document instructions](https://ufs-srweather-app.readthedocs.io/en/latest/BuildSRW.html) to build the app. The error will occur when building the app.

## Detailed Description of Fix (optional)
We were able to build the SRW App on the NOAA Cloud platforms using a newer spack-stack. See the noaa cloud module file here: /contrib/Edward.Snyder/rrfs-container-test/byhand/update/ufs-srweather-app/modulefiles.

## Possible Implementation (optional)
Ensure the changes listed above work for the other two cloud platforms and create a PR to push these changes to develop branch.

**Comment by natalie-perlin** [comment]
Conda environments workflow_tools and regional_workflow_cmaq needed to be installed on Azure and GCP. 
Installed now on all the NOAA cloud systems (AWS, GCP, Azure), and could be used for SRW tests.
