### ISSUE TITLE
Consolidate "nco" WE2E tests

### ISSUE THREAD

**Issue by mkavulich** [ufs-community/ufs-srweather-app#895]
## Description
Originally in the workflow, running in nco or community mode was handled simply by a switch in the config file. In order to test nco mode, a set of nco-specific tests (now found under `tests/WE2E/test_configs/grids_extrn_mdls_suites_nco`)

## Solution
The `grids_extrn_mdls_suites_nco` subdirectory can probably be eliminated. All of these tests are duplicates of existing tests in `grids_extrn_mdls_suites_community`, with the only differences being they have the "RUN_ENVIR: nco" flag and use pre-staged grid/orog/sfc_climo data. Since the NCO flag is now applied through the workflow script (for Hera's GNU coverage tests), only the pre-staged data is being tested here, and that could definitely be consolidated down to fewer tests. 

## Requirements**
Test NCO mode with as few tests as possible.

## Acceptance Criteria (Definition of Done)
Remove/consolidate unnecessary NCO tests

**Comment by mkavulich** [comment]
Duplicate, see #896

**Comment by gsketefian** [comment]
@mkavulich  Sorry about the duplicate!
