### ISSUE TITLE
Remove any WE2E tests for NCO mode (names starting with "nco_") that test features that are already tested in community mode

### ISSUE THREAD

**Issue by gsketefian** [ufs-community/ufs-srweather-app#896]
## Description

 
There are currently 4 tests under 
```
ufs-srweather-app/tests/WE2E/test_configs/grids_extrn_mdls_suites_nco
```
(whose names start with "nco_") that by default run in NCO mode.  These need to be checked to see if the features they are testing are duplicated in the community mode tests.  If so, they should be removed since the WE2E testing script can now switch between NCO and community modes via a command-line flag.

## Solution

Compare the 4 NCO-mode tests to counterparts in the `grids_extrn_mdls_suites_community` and other subdirectories under `ufs-srweather-app/tests/WE2E/test_configs`.

## Acceptance Criteria (Definition of Done)

Report back on whether any of the 4 NCO-mode tests are duplicated in community mode and remove any that are.

**Comment by mkavulich** [comment]
This issue also brings up another good point: while much of this test functionality is duplicated between nco and community tests, we actually have no current community-mode tests that use staged grid/orog/sfc_climo data. That should probably be added as part of this process.

**Comment by MichaelLueken** [comment]
NCO mode WE2E tests were removed as part of PR #1060.  Closing issue now.
