### ISSUE TITLE
App build fails on wcoss2

### ISSUE THREAD

**Issue by chan-hoo** [ufs-community/ufs-srweather-app#903]
## Current behavior

-- Found sp: /apps/ops/prod/libs/intel/19.1.3.304/sp/2.3.3/lib/libsp_4.a (found version "2.3.3")
CMake Error at CMakeLists.txt:167 (find_package):
  Could not find a configuration file for package "w3emc" that is compatible
  with requested version "2.9.2".

  The following configuration files were considered but not accepted:

    /apps/ops/prod/libs/intel/19.1.3.304/w3emc/2.9.1/lib/cmake/w3emc/w3emc-config.cmake, version: 2.9.1

-- Configuring incomplete, errors occurred!

## Machines affected

WCOSS2

**Comment by natalie-perlin** [comment]
A #904 PR-904 opened would close this issue. The approach is to rearrange loading the modules.
