### ISSUE TITLE
Address the EE2 compliance to support the AQMv7 implementation

### ISSUE THREAD

**Issue by JianpingHuang-NOAA** [ufs-community/ufs-srweather-app#908]
@chan-hoo @MatthewPyle-NOAA 
Below are several changes we propose to better address EE2 compliance by following the NCO Implementation Standards (version 11.0.0) and AQMv6 convention to support AQMv7 implementation.
 
1) To define the following environment variables by following the EE2 requirement (https://www.nco.ncep.noaa.gov/idsb/implementation_standards/ImplementationStandards.v11.0.0.pdf) (See pages 4 and 5) (in the run.ver or job_preamble.sh or wcoss2.yaml files)

export HOMEaqm=$PACKAGEROOT/$model.$version
export USHaqm=${USHaqm:-${HOMEaqm}/ush}
export EXECaqm=${EXECaqm:-${HOMEaqm}/exec}
export PARMaqm=${PARMaqm:-${HOMEaqm}/parm}
export FIXaqm=${FIXaqm:-${HOMEaqm}/fix}
export UTILaqm=${UTILaqm:-${HOMEaqm}/util}

2) Change  the following environment variable names to FIXaqm in the ~/ush/job_preamble.sh  and ~/ush/machine/wcoss2.yaml files

export DCOMINbio="${DCOMINbio:-${DCOMINbio_dfv}}"
export DCOMINdust="${DCOMINdust:-${DCOMINdust_dfv}}"
export DCOMINcanopy="${DCOMINcanopy:-${DCOMINcanopy_dfv}}"
export DCOMINchem_lbcs="${DCOMINchem_lbcs:-${DCOMINchem_lbcs_dfv}}"
export DCOMINpt_src="${DCOMINpt_src:-${DCOMINpt_src_dfv}}"

3) All emissions input files should be put at /lfs/h1/ops/prod/com/aqm/$version/emission to be consistent with the current operational model, which can be define in the job_preamble.sh file. 
export COMINemi=${COMINemi:-$(compath.py -o $NET/${aqm_ver}/emission/)}
 
4) in the job_preamble.sh file
 if [ "${RUN_ENVIR}" = "nco" ]; then
    [[ "$WORKFLOW_MANAGER" = "rocoto" ]] && export COMROOT=$COMROOT
    export COMIN="${COMIN:-$(compath.py -o ${NET}/${model_ver}/${RUN}.${PDY}/${cyc})}"
    export COMOUT="${COMOUT:-$(compath.py -o ${NET}/${model_ver}/${RUN}.${PDY}/${cyc})}"
    export COMINm1="${COMINm1:-$(compath.py -o ${NET}/${model_ver}/${RUN}.${PDYm1})}"

    export COMINgfs="${COMINgfs:-$(compath.py ${envir}/gfs/${gfs_ver})}"
    export COMINgefs="${COMINgefs:-$(compath.py ${envir}/gefs/${gefs_ver})}"
 ...

Should we do the same things for ecflow too ? @lgannoaa 

5) copy /lfs/h2/emc/lam/noscrub/UFS_SRW_App/develop/fix/fix_am 
         and other files at  /lfs/h2/emc/lam/noscrub/UFS_SRW_App/develop 
 to ${FIXaqm}

**Comment by MatthewPyle-NOAA** [comment]
@JianpingHuang-NOAA Do you have a branch or code on disk where I could see these changes?  At first glance what you've said sounds reasonable, but would help me to see what you've described in the context of the overall workflow.

**Comment by lgannoaa** [comment]
@JianpingHuang-NOAA 
If your question to me is about statement:
if [ "${RUN_ENVIR}" = "nco" ]; then

My recommendation is that the ecflow running in NCO is for production only. They will be wired in RUN_ENVIR=nco from ecflow root environment. This kind if statement should not be in ecflow job scripts (*.ecf).

**Comment by JianpingHuang-NOAA** [comment]
@MatthewPyle-NOAA  I didn't because it requires not only changing the files job_preamble.sh, wcoss2.yaml, config_defaults.yaml, but also the job scripts and ex-scripts.

**Comment by JianpingHuang-NOAA** [comment]
@chan-hoo  Can you address Lin's comments on the "nco" statement?

**Comment by chan-hoo** [comment]
@JianpingHuang-NOAA, as far as I know, the ecflow job-card scripts (*.ecf) do not have any if-statements for RUN_ENVIR.

**Comment by JianpingHuang-NOAA** [comment]
@chan-hoo  Can you get this done by next week?   Thanks !

**Comment by chan-hoo** [comment]
@JianpingHuang-NOAA, No, I can't. I am working on the RRFS project. This is your idea. You can make change and open a PR to the branch directly.

**Comment by JianpingHuang-NOAA** [comment]
@chan-hoo @MatthewPyle-NOAA @bbakernoaa 

I created a feature branch to address the AQMv7_EE2 issues by modifying job_preamble.sh, wcoss2.yaml,  config_defaults.yaml, and other related scripts, etc. The details can be found on the following link

[config_defaults.yaml](https://github.com/JianpingHuang-NOAA/ufs-srweather-app/tree/feature/AQMv7_EE2)

I completed a test with the above feature branch and compared the model raw forecast and bias-correction results with those generated by the original SRW-app workflow (https://github.com/ufs-community/ufs-srweather-app/tree/production/AQM.v7. They are identical.  

However, I met an issue of specifying environmental variables in Section of "cpl_aqm_parm:" in the wcoss2.yaml file. 

The workflow runs successfully if I define the absolute paths for those environmental variables in above section. 
For instance, the following definition is fine
FIXaqmnexus: /lfs/h2/emc/physics/noscrub/jianping.huang/nwdev/packages/aqm.v7.0.84d/fix/nexus

However, the job failed if I define 
FIXaqmnexus: ${HOMEaqm}/fix/nexus

Please see an example log file on Cactus

/lfs/h2/emc/ptmp/jianping.huang/emc.para/output/20230918_failed/nexus_emission_2023091800_s01.id_1695134551.log

The issue is that the FIXaqmnexus treats ${HOMEaqm} as character string rather than a predefined variable. 

Below is what I defined in the config_default.yaml file  
 FIXaqmnexus: "{{ FIXaqmnexus }}"

at /lfs/h2/emc/physics/noscrub/jianping.huang/nwdev/packages/aqm.v7.0.84d/ush

But it does not work.

Any suggestions?  @chan-hoo  @bbakernoaa

**Comment by MatthewPyle-NOAA** [comment]
@JianpingHuang-NOAA - I would try getting rid of the double quotes surrounding these items.  

cp "${FIXaqmnexus}/${NEXUS_GRID_FN}" "${DATA}/grid_spec.nc"

Make it more like the cp statements above and below it in /lfs/h2/emc/physics/noscrub/jianping.huang/nwdev/packages/aqm.v7.0.84d/scripts/exregional_nexus_emission.sh

**Comment by JianpingHuang-NOAA** [comment]
@MatthewPyle-NOAA  Thanks for checking this.  I did as you suggested but the problem remains. 

If you look at the **var_defn.sh** file on Cactus at the following location

/lfs/h2/emc/physics/noscrub/jianping.huang/para/c84d/2023091800

**FIXaqmnexus='${HOMEaqm}/fix/nexus'**

It seems that the FIXaqmnexus treats "HOMEaqm" as a character string rather than an environmental variable.  That is the issue. In fact, I saw the var_defn.sh has a similar variable definition in "platform" section like 

RUN_CMD_FCST='mpiexec -n ${PE_MEMBER01} -ppn ${PPN_RUN_FCST} --cpu-bind core -depth ${OMP_NUM_THREADS_RUN_FCST}'

My question for Chan-Hoo, can I move those environmental variables from [cpl_aqm_parm] to [platform] sections in the var_defn.sh file?

/lfs/h2/emc/physics/noscrub/jianping.huang/para/c84d/2023091800/var_defns.sh  (Cactus).

**Comment by JianpingHuang-NOAA** [comment]
@chan-hoo

**Comment by MatthewPyle-NOAA** [comment]
@JianpingHuang-NOAA It looks like only the FIXaqmnexus definition in the var_defns.sh file uses HOMEaqm in a subsequent definition.  The other paths that technically are under $HOMEaqm have the entire path defined in var_defns.sh, such as:

JOBSdir='/lfs/h2/emc/physics/noscrub/jianping.huang/nwdev/packages/aqm.v7.0.84d/jobs'
SORCdir='/lfs/h2/emc/physics/noscrub/jianping.huang/nwdev/packages/aqm.v7.0.84d/sorc'
PARMdir='/lfs/h2/emc/physics/noscrub/jianping.huang/nwdev/packages/aqm.v7.0.84d/parm'
FIXdir='/lfs/h2/emc/physics/noscrub/jianping.huang/nwdev/packages/aqm.v7.0.84d/fix'

**Comment by JianpingHuang-NOAA** [comment]
@MatthewPyle-NOAA That is a good catch. This is just a test by using FIXaqmnexus at this moment. Once it works, we need to define all other environmental variables in Section of cpl_aqm_parm of wcoss2.yaml in the same way to avoid using personal directory for other users.  

cpl_aqm_parm:
  FIXaqmconfig: /lfs/h2/emc/physics/noscrub/jianping.huang/nwdev/packages/aqm.v7.0.84d/fix/aqm/epa/data
  FIXaqmbio: /lfs/h2/emc/physics/noscrub/jianping.huang/nwdev/packages/aqm.v7.0.84d/fix/bio
  FIXaqmdust: /lfs/h2/emc/physics/noscrub/jianping.huang/nwdev/packages/aqm.v7.0.84d/fix/FENGSHA
  FIXaqmcanopy: /lfs/h2/emc/physics/noscrub/jianping.huang/nwdev/packages/aqm.v7.0.84d/fix/canopy
    #DCOMINfire_dfv: /lfs/h1/ops/dev/dcom 
  DCOMINfire: /lfs/h2/emc/physics/noscrub/kai.wang/RAVE_fire/RAVE_NA_NRT/RAVE_raw_scaleup
  FIXaqmchem_lbcs: /lfs/h2/emc/physics/noscrub/jianping.huang/nwdev/packages/aqm.v7.0.84d/fix/chem_lbcs/AQM_NA13km_AM4_v1
  COMINgefs: /lfs/h1/ops/prod/com/gefs/v12.3
  COMINemispt: /lfs/h2/emc/physics/noscrub/Youhua.Tang/nei2016v1-pt/v2023-01-PT
  DCOMINairnow: /lfs/h1/ops/prod/dcom
  COMINbicor: /lfs/h2/emc/physics/noscrub/jianping.huang/Bias_correction/aqmv7.0.84d
  COMOUTbicor: /lfs/h2/emc/physics/noscrub/jianping.huang/Bias_correction/aqmv7.0.84d
  COMINemis: /lfs/h2/emc/lam/noscrub/RRFS_CMAQ/nexus_emissions
  #FIXaqmnexus: /lfs/h2/emc/physics/noscrub/jianping.huang/nwdev/packages/aqm.v7.0.84d/fix/nexus
  FIXaqmnexus: ${HOMEaqm}/fix/nexus
  FIXaqmnexus_gfs_sfc: /lfs/h2/emc/physics/noscrub/jianping.huang/nwdev/packages/aqm.v7.0.84d/fix/gfs

**Comment by HaixiaLiu-NOAA** [comment]
@chan-hoo can you help take a look at this issue and see if you have a solution? Thank you

**Comment by chan-hoo** [comment]
@HaixiaLiu-NOAA, I don't have a direct solution. I emailed @JianpingHuang-NOAA about my idea yesterday. That was what I could suggest.
