### ISSUE TITLE
[production/AQM.v7] Operational requirement: Enhancement of production/AQM.v7 workflow for handling various missing input files (e.g., restart) with IT test 

### ISSUE THREAD

**Issue by JianpingHuang-NOAA** [ufs-community/ufs-srweather-app#926]
## Description
AQMv7 real-time testing encountered several failures due to missing restart files from the previous cycle last week when Cactus was not stable. To enhance our workflow and address such scenarios effectively, we propose the following approach:

1) Handling Missing Restart Files:
If restart files from the previous cycle are missing, we will utilize restart files from the previous two cycles.
If both sets of restart files be unavailable, we will resort to using restart files from the previous three cycles.
In the rare event that all restart files are still unavailable, we nee d to create climatology-based Initial Condition (IC) files as a backup.

2) Extension to missing other input Files:
We need to develop a similar capability for managing other input files, such as GEFS-aerosol output files. These files are for generating aerosol Lateral Boundary Conditions (LBCs) used in AQMV7 forecast runs.

It's worth noting that we have developed such a capability to address missing RAVE data files.

**Comment by HaixiaLiu-NOAA** [comment]
@chan-hoo please work with Jianping to meet these IT test requirements.

**Comment by chan-hoo** [comment]
@JianpingHuang-NOAA, which tasks failed in the above case? `aqm_ics`, `aqm_lbcs`, `run_fcst`?

**Comment by JianpingHuang-NOAA** [comment]
@chan-hoo  The failures are related to the run_fcst jobs.   BTW, Kai and I have come out a solution to deal with the failures due to missing restart files in the previous cycle runs.  I will open a PR for your review by tomorrow.

**Comment by chan-hoo** [comment]
@JianpingHuang-NOAA, got it!

**Comment by JianpingHuang-NOAA** [comment]
@chan-hoo  We need to include MAKE_LBCS as the 2nd dependency for triggering the job AQM_LBCs.    Below is what I did 

    <dependency>
      **<and>
        <taskdep task="&TN_MAKE_ICS;"/>**
        <taskdep task="&TN_MAKE_LBCS;"/>
      **<and>**
    </dependency>

in the ~/parm/FV3LAM_wflow.xml.   After I adding those lines, the workflow stops running . What else do I need to change?  Thanks

**Comment by chan-hoo** [comment]
@JianpingHuang-NOAA, the double asterisks are not necessary and the second `<and>` should be `</and>`. Can you try the following?
```
<dependency>
  <and>
    <taskdep task="&TN_MAKE_ICS;"/>
    <taskdep task="&TN_MAKE_LBCS;"/>
  </and>
</dependency>
```

**Comment by JianpingHuang-NOAA** [comment]
@chan-hoo   That is what exactly I did. Please check the modified xml file at 

/lfs/h2/emc/physics/noscrub/jianping.huang/nwdev/packages/aqm.v7.0.85d/parm > vim FV3LAM_wflow.xml_new

The double stars (**)  was caused by adding "Bold" when I pasted those lines on Github.

**Comment by JianpingHuang-NOAA** [comment]
Below is the error message that I got  when I lunched the "FV3LAM_wflow.sh"

+ print_msg.sh[203]: local msg_header msg_footer err_msg
+ print_msg.sh[213]: '[' main = main ']'
++ print_msg.sh[224]: printf '\nERROR:
  From script:  "launch_FV3LAM_wflow.sh"
  Full path to script:  "/lfs/h2/emc/physics/noscrub/jianping.huang/nwdev/packages/aqm.v7.0.85d/ush/launch_FV3LAM_wflow.sh"
'
+ print_msg.sh[221]: msg_header='
ERROR:
  From script:  "launch_FV3LAM_wflow.sh"
  Full path to script:  "/lfs/h2/emc/physics/noscrub/jianping.huang/nwdev/packages/aqm.v7.0.85d/ush/launch_FV3LAM_wflow.sh"'
++ print_msg.sh[235]: printf '\nExiting with nonzero status.'
+ print_msg.sh[235]: msg_footer='
Exiting with nonzero status.'
+ print_msg.sh[244]: '[' 1 -gt 1 ']'
+ print_msg.sh[272]: '[' 1 -eq 0 ']'
+ print_msg.sh[274]: '[' 1 -eq 1 ']'
+ print_msg.sh[275]: err_msg='\nCall to "rocotorun" failed with return code 1.'
+ print_msg.sh[278]: printf 'FATAL ERROR: 
ERROR:
  From script:  "launch_FV3LAM_wflow.sh"
  Full path to script:  "/lfs/h2/emc/physics/noscrub/jianping.huang/nwdev/packages/aqm.v7.0.85d/ush/launch_FV3LAM_wflow.sh"\nCall to "rocotorun" failed with return code 1.
Exiting with nonzero status.\n'
FATAL ERROR: 
ERROR:
  From script:  "launch_FV3LAM_wflow.sh"
  Full path to script:  "/lfs/h2/emc/physics/noscrub/jianping.huang/nwdev/packages/aqm.v7.0.85d/ush/launch_FV3LAM_wflow.sh"
Call to "rocotorun" failed with return code 1.
Exiting with nonzero status.

**Comment by chan-hoo** [comment]
@JianpingHuang-NOAA, the second `<and>` should be `</and>`. Please add `/` between `<` and `a`.

**Comment by JianpingHuang-NOAA** [comment]
That is a trick. Thanks @chan-hoo
