### ISSUE TITLE
hpc-stack still used for SRW, and the hpc-stack repository needs to be updated

### ISSUE THREAD

**Issue by natalie-perlin** [ufs-community/ufs-srweather-app#929]
## Description
HPC-stack is still used for SRW, Tier 1 platforms Derecho and Gaea C5, and also Linux and MacOS.  This software stack appears no longer be supported by NOAA-EMC, yet https://github.com/NOAA-EPIC/hpc-stack is maintained by EPIC and could be updated in a more timely manner.

## Solution
Bring the repository https://github.com/NOAA-EPIC/hpc-stack up to date to reflect changes in installation scripts, methods, software versions, new packages, and new RDHPCs machines. There is an existing PR that addresses many of the updates in both NOAA-EPIC repository https://github.com/NOAA-EPIC/hpc-stack/pull/14 and NOAA-EMC repository https://github.com/NOAA-EMC/hpc-stack/pull/525.

## Related to (optional)
SRW 2.2. release

**Comment by MichaelLueken** [comment]
@natalie-perlin Given that we have successfully released SRW v2.2.0 and that the SRW App has fully transitioned to using spack-stack, can this issue be closed?

**Comment by MichaelLueken** [comment]
Closing issue now.  If you feel this issue hasn't been addressed, please feel free to either reopen this issue or open a new issue.
