### ISSUE TITLE
[production/AQMv.7] all the product-generation related jobs failed with SENDDBN testing

### ISSUE THREAD

**Issue by JianpingHuang-NOAA** [ufs-community/ufs-srweather-app#948]
## Description
The following four jobs failed during the SENDDBN testing. Below are the details.

1) aqm_bias_correction_o3_06.o106725951:/lfs/h2/emc/global/noscrub/lin.gan/para/packages/aqm.v7.0/scripts/exregional_bias_correction_o3.sh: line 404: DBNALERT_TYPE: unbound variable

2) aqm_bias_correction_pm25_06.o106725948:/lfs/h2/emc/global/noscrub/lin.gan/para/packages/aqm.v7.0/scripts/exregional_bias_correction_pm25.sh: line 458: DBNALERT_TYPE: unbound variable
3) aqm_post_stat_o3_06.o106725949:/lfs/h2/emc/global/noscrub/lin.gan/para/packages/aqm.v7.0/scripts/exregional_post_stat_o3.sh: line 282: DBNALERT_TYPE: unbound variable
4) aqm_post_stat_pm25_06.o106725950:/lfs/h2/emc/global/noscrub/lin.gan/para/packages/aqm.v7.0/scripts/exregional_post_stat_pm25.sh: line 153: DBNALERT_TYPE: unbound variable

**Comment by HaixiaLiu-NOAA** [comment]
can be closed according to Jianping

**Comment by JianpingHuang-NOAA** [comment]
Done
