### ISSUE TITLE
Update documentation for v2.2.0 release

### ISSUE THREAD

**Issue by gspetro-NOAA** [ufs-community/ufs-srweather-app#949]
## Description
Add a variety of updates required for the v2.2.0 release, including: 
- Information on changes since v2.1.0 release
- Update all hyperlinks, data paths, git clone command, container commands, and version numbers to reflect content of release
- Update LAM grid chapter to include RRFS_NA_13km grid
- Update DOI/citation in docs & README
- Update VX chapter w/new release info

## Solution
Merge these updates into the appropriate RST files in the release branch.

**Comment by MichaelLueken** [comment]
All documentation updates for the SRW v2.2 release have been made and merged via PR #950 and #953.  Closing issue now.
