### ISSUE TITLE
staging location of WE2E data on tier 1 platforms

### ISSUE THREAD

**Issue by jwolff-ncar** [ufs-community/ufs-srweather-app#96]
Update paths in run_experiments.sh to point to data in the group space rather than personal directories.

For example, consider changing:
extrn_mdl_source_basedir="/scratch2/BMC/det/Gerard.Ketefian/UFS_CAM/staged_extrn_mdl_files"
to 
extrn_mdl_source_basedir="/scratch2/BMC/det/UFS_SRW_app/v1p0/model_data"

This will require ensuring all necessary data is copied to the group space. 

This is not time sensitive (i.e., not required for the release) but wanted to mention it as a way to consolidate where files live.

**Comment by jwolff-ncar** [comment]
It will be helpful to have a list of staged data locations on the tier 1 platforms listed in the Chapter 9 of the SRW App Users Guide (https://ufs-srweather-app.readthedocs.io/en/latest/WE2Etests.html). We need to be sure they are not in personal directories.

**Comment by jwolff-ncar** [comment]
@JulieSchramm Would you be willing to help with documenting where these are now so we can identify what needs to be moved to a group space? We do have the GST data in a group space so we can likely use that same template for the WE2E tests dates we need as well. (And we may be able to consolidate those dates to a few to keep down on the number of files we need.)

**Comment by mkavulich** [comment]
Superseded by #231
