### ISSUE TITLE
[Production/AQM.v7] AQMv7 delivery issues (from NCO)

### ISSUE THREAD

**Issue by JianpingHuang-NOAA** [ufs-community/ufs-srweather-app#964]
We received the following issues regarding the AQMv7 delivery package from NCO

1) Files in jobs/ and scripts/ are named with “regional” e.g. JREGIONAL_*/exregional_* . These should be named using the model name “aqm” e.g. JAQM_/exaqm_  

2) In the home directory there are lots of files and unapproved directories that will need to be moved. (see approved directories in Table 3 of implementation standards)

3) Directories: etc/, manage_externals/, tests/

Files: auto_build_exec.sh,  devbuild.sh, devclean.sh, environment.yml, Externals.cfg, rename_model.sh, [ufs_srweather_app_meta.h.in](http://ufs_srweather_app_meta.h.in/), [ufs_srweather_app.settings.in](http://ufs_srweather_app.settings.in/)

4) All build-related scripts should be in sorc/ 

5) Remove all references to developer work areas and all development tools (Sec. IV-C-10). e.g.:

“RUN_ENVIR” sections in if statements

Test files in ush/: machine/*.yaml files, rocoto_fake_slurm/, python_utils/test_data, test_retrieve_data.py, etc

All non-wcoss related files under modulefiles/

6) Compilation:

6.1) Auto_build_exec.sh should be in sorc/, not the home directory

6.2) lots of warnings were found in compilation log that will need to be addressed: see /lfs/h1/nco/ptmp/carlos.m.diaz/aqm.v7.0.0/buildup.log

6.3) Sec. IV-B–5: Code must compile without errors or warnings. Errors and warnings may not be suppressed, and the compiler warning level ("-W" options) must be at least the default one. 

6.4) Please add -traceback flag to all compilation

There should be a way to execute all makefile targets (e.g. debug, clean) through the master script 

7) Scripts should be invoked directly. I see lots of instances calling 'python3 <script.py>' instead of ‘./<script..py>’

The AQMv7 delivery package is located at https://github.com/ufs-community/ufs-srweather-app/releases/tag/production%2FAQM.v7.0.0

**Comment by JianpingHuang-NOAA** [comment]
I have created a feature branch (below) to address part of issues highlighted above

https://github.com/JianpingHuang-NOAA/ufs-srweather-app/tree/feature/AQMv7_release_v4
(or local copy on Dogwood: /lfs/h2/emc/physics/noscrub/jianping.huang/nwdev/packages/aqm.v7.0.88b/ush)

The issues has included the fixes for issues 1), 2), part of 3), 5) and 7) 

@chan-hoo @brian.curtis@noaa.gov  

 I need your help on issues 2), 3), 4) (can be ignored), and 6), please kindly commence your works using my feature branch, 'feature/AQMv7_release_v4' as the starting point.

Regarding the warning issues. I will reach out to Barry (@bbakernoaa) for NEXUS and CMAQ, Wen for UPP, Raffaele for the coupler, Brian for UFS,  Dave for bias-correction, Kai and myself for post-processing and product generation.  

Thanks,

**Comment by chan-hoo** [comment]
@JianpingHuang-NOAA, Is there any reason why you want to use your feature branch? If not, I'll update the `production/AQM.v7` directly. I can fix the items 1-5, 6.1, and 7. I expect I'll be able to finish them by this Thursday. Is this good for you?

**Comment by JianpingHuang-NOAA** [comment]
No other reasons and just wanted to save some of your time. I have changed
(including deleting) many files and completed tests. The updated branch can
reproduce our NRT runs’ results. If you are ok, I can immediately open a PR
to merge all the changes to the production/AQM.v7 branch.

Jianping

**Comment by chan-hoo** [comment]
Yes, please go ahead.

**Comment by JianpingHuang-NOAA** [comment]
Please see PR 965
<https://github.com/ufs-community/ufs-srweather-app/pull/965>

Thanks,

Jianping

**Comment by JianpingHuang-NOAA** [comment]
@chan-hoo  Steven suggests to move "https://github.com/ufs-community/ufs-srweather-app/blob/production/AQM.v7/ush/machine/wcoss2.yaml" to ~/parm since it is a parm-like file

**Comment by chan-hoo** [comment]
@JianpingHuang-NOAA, I've updated the `production/AQM.v7` branch for the above items: 2, 3, 4, 5, 6.1, and Steven's suggestion (move `ush/machine` to `parm`). Please check out the latest branch and test your NRT. If you have any problems, please let me know (cc'ing @HaixiaLiu-NOAA here).

**Comment by JianpingHuang-NOAA** [comment]
@chan-hoo  Thanks for your quick response. I am testing it now.

**Comment by JianpingHuang-NOAA** [comment]
@chan-hoo I have completed the tests with the updated production/AQM.v7 for 20231106 at 00z and 06z. Both model raw and bias-correction results are identical to those from the NRT runs which used the original workflow.
