### ISSUE TITLE
[production/AQM.v7] Module task double-loading issue with local.lua file

### ISSUE THREAD

**Issue by JianpingHuang-NOAA** [ufs-community/ufs-srweather-app#970]
In the current AQMv7 package, many task local lua files have a double loading issue  while loading ".python_regional_workflow".  For instance,

**cat nexus_emission.local.lua** 
load("**python_regional_workflow**")

load(pathJoin("PrgEnv-intel", os.getenv("PrgEnv_intel_ver")))
load(pathJoin("intel", os.getenv("intel_ver")))
load(pathJoin("craype", os.getenv("craype_ver")))
load(pathJoin("cray-mpich", os.getenv("cray_mpich_ver")))
load(pathJoin("cmake", os.getenv("cmake_ver")))

load(pathJoin("cray-pals", os.getenv("cray_pals_ver")))

load(pathJoin("hdf5", os.getenv("hdf5_ver")))
load(pathJoin("netcdf", os.getenv("netcdf_ver")))
load(pathJoin("esmf", os.getenv("esmf_ver")))

load(pathJoin("udunits", os.getenv("udunits_ver")))
load(pathJoin("gsl", os.getenv("gsl_ver")))
load(pathJoin("nco", os.getenv("nco_ver")))

==========
cat python_regional_workflow.lua  
load(pathJoin("PrgEnv-intel", os.getenv("PrgEnv_intel_ver")))
load(pathJoin("craype", os.getenv("craype_ver")))
load(pathJoin("intel", os.getenv("intel_ver")))
load(pathJoin("python", os.getenv("python_ver")))
load(pathJoin("prod_util", os.getenv("prod_util_ver")))

===========
You can see that modules PrgEnv-intel, craype, intel have been loaded by two times. 

The details can be found at https://github.com/JianpingHuang-NOAA/ufs-srweather-app/blob/feature/AQMv7_release_v6/modulefiles/tasks/wcoss2/nexus_emission.local.lua

So, we need to revise all local.lua files to fix the double loading issue

**Comment by chan-hoo** [comment]
@JianpingHuang-NOAA, Now all modules are loaded directly from the ecflow scripts. we can remove the `modulefiles/task` direcoty.
