### ISSUE TITLE
[production/AQM.v7]  Using standard environmental variable names

### ISSUE THREAD

**Issue by JianpingHuang-NOAA** [ufs-community/ufs-srweather-app#971]
According to implementation EE2 requirements for AQMv7, we have to use aqm-dependent variable names such as USHaqm and EXECaqm rather than  USHdir and EXECdir. The issue has been found in all the JAQM and exaqm scripts.

**Comment by chan-hoo** [comment]
@JianpingHuang-NOAA, Who commented this? As far as I know, Steven confirmed that we could use `*dir` except for `HOMEaqm`. @MatthewPyle-NOAA, is this correct?

**Comment by MatthewPyle-NOAA** [comment]
@chan-hoo it was at least at one point about a year ago.  From September 2022 - seemed like he preferred things like PARM rather than PARMdir.  But given their prickliness with the first handoff, it would be safest to make things be like PARMaqm (for example).  


```
For the initial implementation, would this work:
HOMErrfs
USH
FIX
EXEC

Then we explore changing this standard with the next transition to something like:
HOMErrfs
USHDIR
FIXDIR
BINDIR
```

**Comment by JianpingHuang-NOAA** [comment]
@chan-hoo  I got this comment from Carlos (NCO) who is working on the implementation of AQMv7
