### ISSUE TITLE
[production/AQM.v7] Hard-coded paths in any scripts or version numbers outside of run.ver/build.ver

### ISSUE THREAD

**Issue by JianpingHuang-NOAA** [ufs-community/ufs-srweather-app#972]
According to NOC, make sure there's no hard-coded paths in any scripts or version numbers outside of run.ver/build.ver. 

e.g.  ush/etc/lmod-setup.sh:54:   export BASH_ENV="/usr/local/lmod/8.3.1/init/bash"

**Comment by chan-hoo** [comment]
@JianpingHuang-NOAA, The `etc/lmod_setup.sh` is only used while compiling for ecFlow since the modules are loaded directly from the ecflow script. I'll remove the line for calling this script. Therefore, we can remove the `ush/etc` directory.

**Comment by chan-hoo** [comment]
@JianpingHuang-NOAA, I've remove it.

**Comment by JianpingHuang-NOAA** [comment]
@chan-hoo Please have a double check and make sure that no hard-coded paths in any scripts or version numbers outside of run.ver/build.ver.  Thanks !
