### ISSUE TITLE
missed build_hera_gnu.env for Hera gnu setting

### ISSUE THREAD

**Issue by panll** [ufs-community/ufs-srweather-app#98]
I am trying to test UFS SRWEATHER-APP with GNU compiler on Hera, and don't find the file build_hera_gnu.env under the env directory.
If the GNU compiler is supported on Hera, that file is needed.
https://docs.google.com/spreadsheets/d/1C05XGZbGAHy67lQ2qgzlQ7Eqft7Qg9eGc4Wn4BbZFag/edit#gid=0

Thanks!

**Comment by JulieSchramm** [comment]
Hi Linlin,

You must have heard our meeting.  Mike is going to get the SRW App to build
on Hera with GNU and make the file.

**Comment by panll** [comment]
Great, thanks!

**Comment by mkavulich** [comment]
@panll I looked into adding an environment file for GNU on Hera, and while all executables do build, there are problems in both the workflow and segfaults in UFS_UTILS. These problems can be solved but I think it's too late in the game to be debugging these issues for the release.

@climbfuji I'd recommend we not support GNU on Hera for the release, but we can discuss this further if there are objections.

**Comment by climbfuji** [comment]
> @panll I looked into adding an environment file for GNU on Hera, and while all executables do build, there are problems in both the workflow and segfaults in UFS_UTILS. These problems can be solved but I think it's too late in the game to be debugging these issues for the release.
> 
> @climbfuji I'd recommend we not support GNU on Hera for the release, but we can discuss this further if there are objections.

Fine with me, as long as cheyenne.gnu and other generic gnu platforms work. Let's fix it for the develop branch.

**Comment by panll** [comment]
Thanks， Dom, for checking that. @climbfuji

**Comment by JulieSchramm** [comment]
Run fails for GNU build on Hera with the message:

/contrib/miniconda3/4.5.12/lib/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by ufs-srweather-app/bin/chgres_cube)

@christinaholtNOAA May be able to update the library.

**Comment by mkavulich** [comment]
This was resolved some time ago, building and running with GNU compilers can now be done on Hera.
